$axure.loadCurrentPage({
  "url":"关于问药.html",
  "generationDate":new Date(1409493106550.95),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"f890fe0287764e8496ae49eda75aab09",
    "type":"Axure:Page",
    "name":"关于问药",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"应用字体",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"c080b8006bf54190a601b3e250801fd6",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":100,
              "y":50},
            "size":{
              "width":320,
              "height":480}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"79b1e540683e40d7bd7a32049fe81633",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":100,
                  "y":50},
                "size":{
                  "width":320,
                  "height":480}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/我的问药/u0.png"}},
{
          "id":"eeb3770ed0eb4f0084c3ec7debddedde",
          "label":"top",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":100,
              "y":50},
            "size":{
              "width":320,
              "height":20},
            "rotation":"0",
            "textRotation":"0",
            "borderWidth":"0",
            "cornerRadiusTopLeft":"0"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"c2b7ab11d8ed46ce80279d4cf3f20b94",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":100,
                  "y":50},
                "size":{
                  "width":320,
                  "height":20},
                "rotation":"0",
                "textRotation":"0",
                "borderWidth":"0",
                "cornerRadiusTopLeft":"0"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/我的问药/top_u2.png"}},
{
          "id":"908875171011450e905534cccc660c5c",
          "label":"药店列表",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontSize":"16px",
            "horizontalAlignment":"left",
            "location":{
              "x":100,
              "y":70},
            "size":{
              "width":320,
              "height":35}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"bd548ba86bc7428ba3b027265ddb3042",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"16px",
                "horizontalAlignment":"left",
                "location":{
                  "x":100,
                  "y":70},
                "size":{
                  "width":320,
                  "height":35}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/我的问药/u12.png"}},
{
          "id":"e60f44dd0f0f4d19b66899192954cc09",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":108,
              "y":80},
            "size":{
              "width":20,
              "height":15},
            "borderWidth":"-1",
            "borderFill":{
              "fillType":"solid",
              "color":0xFF000000}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"41bf15beda554844b0fdfba522b7f897",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":108,
                  "y":80},
                "size":{
                  "width":20,
                  "height":15},
                "borderWidth":"-1",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF000000}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/咨询药店/u25.png"}},
{
          "id":"5815f8e2c2e841f890319693cbb66019",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontSize":"16px",
            "location":{
              "x":220,
              "y":115},
            "size":{
              "width":70,
              "height":70},
            "cornerRadiusTopLeft":"20"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"9c90c46d6e8a4671bacb0b0f0c2c45b2",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"16px",
                "location":{
                  "x":220,
                  "y":115},
                "size":{
                  "width":70,
                  "height":70},
                "cornerRadiusTopLeft":"20"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/关于问药/u8.png"}},
{
          "id":"91adcbb2a0224c38958eee20b2e530eb",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"16px",
            "horizontalAlignment":"center",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF000000,
              "opacity":1},
            "location":{
              "x":177,
              "y":190},
            "size":{
              "width":160,
              "height":19}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"1ede6e4c4d2643d7bad37f9dcf386bcb",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"16px",
                "horizontalAlignment":"center",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF000000,
                  "opacity":1},
                "location":{
                  "x":177,
                  "y":190},
                "size":{
                  "width":160,
                  "height":19}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"d999b670f6b248499edc61afa642bb8f",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":100,
              "y":219},
            "size":{
              "width":320,
              "height":40},
            "borderFill":{
              "fillType":"solid",
              "color":0xFF999999}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"258095fe519d4b048b2171c13ba080d3",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":100,
                  "y":219},
                "size":{
                  "width":320,
                  "height":40},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF999999}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/我/u42.png"}},
{
          "id":"b02bc32537f240ac8f0c3f84611801ca",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"14px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF000000,
              "opacity":1},
            "location":{
              "x":118,
              "y":233},
            "size":{
              "width":72,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"a18dec9035bb4fb9ac4cb6f32b587d0b",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"14px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF000000,
                  "opacity":1},
                "location":{
                  "x":118,
                  "y":233},
                "size":{
                  "width":72,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "annotation":{
            "描述":"内容是一个web网页，app直接把网页加载过来即可；"},
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"1bf892501d664311aa656d4e48d25493",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":100,
              "y":258},
            "size":{
              "width":320,
              "height":40},
            "borderFill":{
              "fillType":"solid",
              "color":0xFF999999}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"2b6079e5eae9451c8d209b871e386150",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":100,
                  "y":258},
                "size":{
                  "width":320,
                  "height":40},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF999999}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/我/u42.png"}},
{
          "id":"7f6adfe94ee14ef88f976118c340748b",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"14px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF000000,
              "opacity":1},
            "location":{
              "x":118,
              "y":271},
            "size":{
              "width":72,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"7d133a69f86c4b3da412e22303b94f68",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"14px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF000000,
                  "opacity":1},
                "location":{
                  "x":118,
                  "y":271},
                "size":{
                  "width":72,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "annotation":{
            "描述":"1、默认值来源于app首次打开时联网检测的结果；若未发现新版本，则显示“已经是最新版本”；若发现新版本且用户暂未更新，则显示“发现新版本”并且显示红点标记；<br>2、点击行则联网检测是否有新版本，有则弹框显示新版本介绍；无则浮层提示“当前已是最新版本”；"},
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"e4d5862c62fc49198cbf69b5dd245e9d",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "verticalAlignment":"middle",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF666666,
              "opacity":1},
            "location":{
              "x":330,
              "y":266},
            "size":{
              "width":81,
              "height":23}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"f9dd3db384ab46ad9cec84056fa05b4e",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "verticalAlignment":"middle",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF666666,
                  "opacity":1},
                "location":{
                  "x":330,
                  "y":266},
                "size":{
                  "width":81,
                  "height":23}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"7ecebf8f7a6447c1b6cbfc3dc2331e86",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":100,
              "y":375},
            "size":{
              "width":320,
              "height":40},
            "borderFill":{
              "fillType":"solid",
              "color":0xFF999999}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"926e18ce2acd4d2889a4599d69360150",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":100,
                  "y":375},
                "size":{
                  "width":320,
                  "height":40},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF999999}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/我/u42.png"}},
{
          "id":"b013f742d904494081c45972a64b555d",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":100,
              "y":414},
            "size":{
              "width":320,
              "height":40},
            "borderFill":{
              "fillType":"solid",
              "color":0xFF999999}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"fa88a52d008b4adc8d3fbb18d40b471a",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":100,
                  "y":414},
                "size":{
                  "width":320,
                  "height":40},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF999999}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/我/u42.png"}},
{
          "id":"d30f7c114def4b388e24b1de602f3bb7",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"14px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF000000,
              "opacity":1},
            "location":{
              "x":118,
              "y":386},
            "size":{
              "width":74,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"522bdada066d446cada8ca0c4a51d1b9",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"14px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF000000,
                  "opacity":1},
                "location":{
                  "x":118,
                  "y":386},
                "size":{
                  "width":74,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"d34864762e7841d891cf12c541212a36",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"14px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF000000,
              "opacity":1},
            "location":{
              "x":118,
              "y":425},
            "size":{
              "width":74,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"7fabb8e36fcf4489af8da5d50395c57b",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"14px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF000000,
                  "opacity":1},
                "location":{
                  "x":118,
                  "y":425},
                "size":{
                  "width":74,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"985b3d133b6b4d23a956be078c703749",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":100,
              "y":297},
            "size":{
              "width":320,
              "height":40},
            "borderFill":{
              "fillType":"solid",
              "color":0xFF999999}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"3d6e0565a80646be8bcfb194781d56cf",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":100,
                  "y":297},
                "size":{
                  "width":320,
                  "height":40},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF999999}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/我/u42.png"}},
{
          "id":"43309fae62724bdc8df0a925abd95453",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":100,
              "y":336},
            "size":{
              "width":320,
              "height":40},
            "borderFill":{
              "fillType":"solid",
              "color":0xFF999999}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"d2ab4f101970473397266ac04e09a6c3",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":100,
                  "y":336},
                "size":{
                  "width":320,
                  "height":40},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF999999}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/我/u42.png"}},
{
          "id":"9fc0eb1d7c914d11826eabe4e377db4d",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"14px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF000000,
              "opacity":1},
            "location":{
              "x":118,
              "y":311},
            "size":{
              "width":57,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"743e41327a424053aab3feb461d0eb57",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"14px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF000000,
                  "opacity":1},
                "location":{
                  "x":118,
                  "y":311},
                "size":{
                  "width":57,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"83830bbde0194a89a193a9c631541c6e",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"14px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF000000,
              "opacity":1},
            "location":{
              "x":118,
              "y":349},
            "size":{
              "width":57,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"974d20bc0080469e8fb0f7400b2d8004",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"14px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF000000,
                  "opacity":1},
                "location":{
                  "x":118,
                  "y":349},
                "size":{
                  "width":57,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"5b89d1933e7945c2bfcdde722cf553e0",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":390,
              "y":308},
            "size":{
              "width":18,
              "height":18},
            "borderWidth":"-1",
            "borderFill":{
              "fillType":"solid",
              "color":0xFF000000}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"a9ba90e4699543228bf7082c37e01fba",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":390,
                  "y":308},
                "size":{
                  "width":18,
                  "height":18},
                "borderWidth":"-1",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF000000}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/横条提醒/u80.png"}},
{
          "id":"3e7afcad7ad347e0b6fbedf53ded739f",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":390,
              "y":349},
            "size":{
              "width":18,
              "height":18},
            "borderWidth":"-1",
            "borderFill":{
              "fillType":"solid",
              "color":0xFF000000}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"d74b9fbeae9e47a096eeb8e154cf2852",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":390,
                  "y":349},
                "size":{
                  "width":18,
                  "height":18},
                "borderWidth":"-1",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF000000}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/横条提醒/u80.png"}},
{
          "id":"5dc6b08a2ef24e54b26f82d1e1097c13",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":390,
              "y":388},
            "size":{
              "width":18,
              "height":18},
            "borderWidth":"-1",
            "borderFill":{
              "fillType":"solid",
              "color":0xFF000000}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"4155cf3a1c9c4a6486bad74298b2384b",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":390,
                  "y":388},
                "size":{
                  "width":18,
                  "height":18},
                "borderWidth":"-1",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF000000}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/横条提醒/u80.png"}},
{
          "id":"e8f8694028354c4b8fd1436138fb12e6",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":390,
              "y":429},
            "size":{
              "width":18,
              "height":18},
            "borderWidth":"-1",
            "borderFill":{
              "fillType":"solid",
              "color":0xFF000000}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"8989c612c14a4a419b693d5884024574",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":390,
                  "y":429},
                "size":{
                  "width":18,
                  "height":18},
                "borderWidth":"-1",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF000000}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/横条提醒/u80.png"}},
{
          "id":"847f3319189d4182a9be3d0a6aa92693",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":390,
              "y":230},
            "size":{
              "width":18,
              "height":18},
            "borderWidth":"-1",
            "borderFill":{
              "fillType":"solid",
              "color":0xFF000000}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"e0c1d3219c204b488c120df0757fda90",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":390,
                  "y":230},
                "size":{
                  "width":18,
                  "height":18},
                "borderWidth":"-1",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF000000}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/横条提醒/u80.png"}},
{
          "id":"456112f70199458c9bee78bf516d5744",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":500,
              "y":50},
            "size":{
              "width":320,
              "height":480}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"ddc215ba865e4ac2a0c28458cabb905c",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":500,
                  "y":50},
                "size":{
                  "width":320,
                  "height":480}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/我的问药/u0.png"}},
{
          "id":"f3d57716509a4a69a43e172946402906",
          "label":"top",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":500,
              "y":50},
            "size":{
              "width":320,
              "height":20},
            "rotation":"0",
            "textRotation":"0",
            "borderWidth":"0",
            "cornerRadiusTopLeft":"0"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"86ccdc3d2ad046f29a273b1c86cbd0d0",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":500,
                  "y":50},
                "size":{
                  "width":320,
                  "height":20},
                "rotation":"0",
                "textRotation":"0",
                "borderWidth":"0",
                "cornerRadiusTopLeft":"0"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/我的问药/top_u2.png"}},
{
          "id":"2bb2fba4835c4daeaaa1f5abdf9735d8",
          "label":"药店列表",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontSize":"16px",
            "horizontalAlignment":"left",
            "location":{
              "x":500,
              "y":70},
            "size":{
              "width":320,
              "height":35}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"dba548d498174cdda90089e729a6e5a9",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"16px",
                "horizontalAlignment":"left",
                "location":{
                  "x":500,
                  "y":70},
                "size":{
                  "width":320,
                  "height":35}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/我的问药/u12.png"}},
{
          "id":"87811449e1ea4e5193aee1972a42eac9",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":508,
              "y":80},
            "size":{
              "width":20,
              "height":15},
            "borderWidth":"-1",
            "borderFill":{
              "fillType":"solid",
              "color":0xFF000000}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"249e4a7002764e3b9a58635e1cbf7241",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":508,
                  "y":80},
                "size":{
                  "width":20,
                  "height":15},
                "borderWidth":"-1",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF000000}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/咨询药店/u25.png"}},
{
          "id":"c6870b52f0024f0a9f5fefeddb3a8b2c",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "fontName":"'Arial Normal', 'Arial'",
            "fontSize":"14px",
            "fontWeight":"400",
            "location":{
              "x":516,
              "y":118},
            "size":{
              "width":134,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"b2b029d1f68d4cba8ea68891ca4cb975",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Normal', 'Arial'",
                "fontSize":"14px",
                "fontWeight":"400",
                "location":{
                  "x":516,
                  "y":118},
                "size":{
                  "width":134,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"41caf260c77f4cc398eba4b1d8e4e4bf",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"14px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF000000,
              "opacity":1},
            "location":{
              "x":517,
              "y":160},
            "size":{
              "width":83,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"f952c62414d340ce90a2c86c36a85b22",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"14px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF000000,
                  "opacity":1},
                "location":{
                  "x":517,
                  "y":160},
                "size":{
                  "width":83,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"9e545f6b0bc449e19b18bf0eeb77dd6a",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF666666,
              "opacity":1},
            "location":{
              "x":529,
              "y":187},
            "size":{
              "width":268,
              "height":32}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"669392ec7b5546129d0c95949eda7ce8",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF666666,
                  "opacity":1},
                "location":{
                  "x":529,
                  "y":187},
                "size":{
                  "width":268,
                  "height":32}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"1d98f598d20c43a59976da177173fa96",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":533,
              "y":229},
            "size":{
              "width":263,
              "height":100}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"53fe89ccdf864309a4995eeac75e3790",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":533,
                  "y":229},
                "size":{
                  "width":263,
                  "height":100}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/关于问药/u62.png"}},
{
          "id":"4b0a91607519400c81d20a19cca6556e",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"14px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF000000,
              "opacity":1},
            "location":{
              "x":516,
              "y":349},
            "size":{
              "width":83,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"fdfdf4656cf446b29cbdfcac81f36a22",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"14px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF000000,
                  "opacity":1},
                "location":{
                  "x":516,
                  "y":349},
                "size":{
                  "width":83,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"860f57736ebf480d9d19622a4bd39d11",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF666666,
              "opacity":1},
            "location":{
              "x":528,
              "y":372},
            "size":{
              "width":268,
              "height":32}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"8dc2700d6b434c30bc3fdfeb3ca85a0f",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF666666,
                  "opacity":1},
                "location":{
                  "x":528,
                  "y":372},
                "size":{
                  "width":268,
                  "height":32}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"0f163b2d8328493fb8d8a044dc1abb16",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":532,
              "y":414},
            "size":{
              "width":263,
              "height":100}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"847bc5ce55144844aea60a039ac924fa",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":532,
                  "y":414},
                "size":{
                  "width":263,
                  "height":100}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/关于问药/u62.png"}},
{
          "id":"44623fc27a8944eca9bea2e2ef78a1d1",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":508,
              "y":137},
            "size":{
              "width":302,
              "height":10},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFCCCCCC}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/关于问药/u70_line.png"}},
{
          "id":"9e03914dd77e4e46a7ae07570e6e022d",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":900,
              "y":50},
            "size":{
              "width":320,
              "height":480}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"dee58ecc20af4879a304e639da69106d",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":900,
                  "y":50},
                "size":{
                  "width":320,
                  "height":480}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/我的问药/u0.png"}},
{
          "id":"a0b42f8bc1e0433fa614f10034ab2713",
          "label":"top",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":900,
              "y":50},
            "size":{
              "width":320,
              "height":20},
            "rotation":"0",
            "textRotation":"0",
            "borderWidth":"0",
            "cornerRadiusTopLeft":"0"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"64160b9364b043eaa00b2efcd3c55a6c",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":900,
                  "y":50},
                "size":{
                  "width":320,
                  "height":20},
                "rotation":"0",
                "textRotation":"0",
                "borderWidth":"0",
                "cornerRadiusTopLeft":"0"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/我的问药/top_u2.png"}},
{
          "id":"cb3f3ad1a3b44e9383628a37e6f0e111",
          "label":"药店列表",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontSize":"16px",
            "horizontalAlignment":"left",
            "location":{
              "x":900,
              "y":70},
            "size":{
              "width":320,
              "height":35}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"7b57fee775ad444488d57d8ecf957a94",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"16px",
                "horizontalAlignment":"left",
                "location":{
                  "x":900,
                  "y":70},
                "size":{
                  "width":320,
                  "height":35}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/我的问药/u12.png"}},
{
          "id":"824997005627447fa555a537220af289",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":908,
              "y":80},
            "size":{
              "width":20,
              "height":15},
            "borderWidth":"-1",
            "borderFill":{
              "fillType":"solid",
              "color":0xFF000000}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"e19b02cb42614be5b807abc47aa9c44a",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":908,
                  "y":80},
                "size":{
                  "width":20,
                  "height":15},
                "borderWidth":"-1",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF000000}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/咨询药店/u25.png"}},
{
          "id":"4f496202720240f3a136ff7b53aadbaf",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"15px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF000000,
              "opacity":1},
            "location":{
              "x":1175,
              "y":80},
            "size":{
              "width":36,
              "height":17}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"08e213a86d9347eab1a6c333ee7c5dd6",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"15px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF000000,
                  "opacity":1},
                "location":{
                  "x":1175,
                  "y":80},
                "size":{
                  "width":36,
                  "height":17}},
              "adaptiveStyles":{
}}],
          "annotation":{
            "描述":"点击提交按钮：<br>1.若输入的意见为空浮层提示&quot;内容不能为空&quot;。<br>2.提交成功时浮层提示提交成功，并且通过全维药事工号向用户发送消息：您的反馈我们已经收到，谢谢！请加入我们的QQ交流群：(产品交流群)，您可以在群里直接跟我们交流。"},
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"691281b7911a48d5875b5cf4bb0ff248",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":1196,
              "y":149},
            "size":{
              "width":15,
              "height":11},
            "borderWidth":"-1",
            "borderFill":{
              "fillType":"solid",
              "color":0xFF000000}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"4e4474789d2b4e10adaf000bc3437afd",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":1196,
                  "y":149},
                "size":{
                  "width":15,
                  "height":11},
                "borderWidth":"-1",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF000000}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/横条提醒/u80.png"}},
{
          "id":"88643b9f508e45ecb4ffc9ff0da76b40",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":1196,
              "y":225},
            "size":{
              "width":15,
              "height":11},
            "borderWidth":"-1",
            "borderFill":{
              "fillType":"solid",
              "color":0xFF000000}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"ce9d107844e0486aa5e0f0c92554f377",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":1196,
                  "y":225},
                "size":{
                  "width":15,
                  "height":11},
                "borderWidth":"-1",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF000000}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/横条提醒/u80.png"}},
{
          "id":"4f5b475463d2404d91022d4b187cb88a",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":1196,
              "y":188},
            "size":{
              "width":15,
              "height":11},
            "borderWidth":"-1",
            "borderFill":{
              "fillType":"solid",
              "color":0xFF000000}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"20ec81f289d14e11b0581c742fff5ac4",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":1196,
                  "y":188},
                "size":{
                  "width":15,
                  "height":11},
                "borderWidth":"-1",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF000000}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/横条提醒/u80.png"}},
{
          "id":"53dfbb001db04980b2d9f64859a77fcd",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":909,
              "y":266},
            "size":{
              "width":301,
              "height":35},
            "borderFill":{
              "fillType":"solid",
              "color":0xFF999999}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"db728c55c27f4fbeb8737cc70ea83c36",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":909,
                  "y":266},
                "size":{
                  "width":301,
                  "height":35},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF999999}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/关于问药/u87.png"}},
{
          "id":"459ae565bf814c2d87d9ed76a3e0e5be",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "horizontalAlignment":"left",
            "verticalAlignment":"top",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF999999,
              "opacity":1},
            "location":{
              "x":909,
              "y":115},
            "size":{
              "width":301,
              "height":141}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"d232eff9c0ae422ca0c7f7a8abd85010",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "horizontalAlignment":"left",
                "verticalAlignment":"top",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF999999,
                  "opacity":1},
                "location":{
                  "x":909,
                  "y":115},
                "size":{
                  "width":301,
                  "height":141}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/关于问药/u89.png"}},
{
          "id":"4370f7b0330c4e6ebe217437ccb70c11",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"14px",
            "horizontalAlignment":"center",
            "verticalAlignment":"middle",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF999999,
              "opacity":1},
            "location":{
              "x":1140,
              "y":227},
            "size":{
              "width":60,
              "height":24}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"973e0bc4ab9049d2ac1eb0cdd82049e0",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"14px",
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF999999,
                  "opacity":1},
                "location":{
                  "x":1140,
                  "y":227},
                "size":{
                  "width":60,
                  "height":24}},
              "adaptiveStyles":{
}}],
          "annotation":{
            "描述":"最多输入300个字,实时显示还能输入多少个字"},
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"cf8fec415a924db9b3d3ff89dd484157",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"14px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF999999,
              "opacity":1},
            "location":{
              "x":914,
              "y":278},
            "size":{
              "width":270,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"f2dbf853564048259cb326235d13b972",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"14px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF999999,
                  "opacity":1},
                "location":{
                  "x":914,
                  "y":278},
                "size":{
                  "width":270,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"5eb6956f64c844e595c33babe64284d5",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF999999,
              "opacity":1},
            "location":{
              "x":913,
              "y":128},
            "size":{
              "width":266,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"4c75493331994baaa59a35fa696a43b2",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF999999,
                  "opacity":1},
                "location":{
                  "x":913,
                  "y":128},
                "size":{
                  "width":266,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"b35a563f3d1d4202b268b62bb1cdf874",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":1310,
              "y":48},
            "size":{
              "width":320,
              "height":480}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"86ca9eb8b1e04accbadd97d82e073dc9",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":1310,
                  "y":48},
                "size":{
                  "width":320,
                  "height":480}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/我的问药/u0.png"}},
{
          "id":"25ce4fa7d447431a832d07a068d1a7a1",
          "label":"top",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":1310,
              "y":48},
            "size":{
              "width":320,
              "height":20},
            "rotation":"0",
            "textRotation":"0",
            "borderWidth":"0",
            "cornerRadiusTopLeft":"0"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"b55e2c886a394aa6b8c8fa6ac0fec961",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":1310,
                  "y":48},
                "size":{
                  "width":320,
                  "height":20},
                "rotation":"0",
                "textRotation":"0",
                "borderWidth":"0",
                "cornerRadiusTopLeft":"0"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/我的问药/top_u2.png"}},
{
          "id":"9192824d6ffe49a0b1e8500e123d6347",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":1310,
              "y":68},
            "size":{
              "width":320,
              "height":40}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"a53f4572720d4c05acc41bbd0d193df4",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":1310,
                  "y":68},
                "size":{
                  "width":320,
                  "height":40}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/药店详情/u2.png"}},
{
          "id":"077b7fe9dc0a43219348df5955787b9f",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":1316,
              "y":78},
            "size":{
              "width":22,
              "height":22},
            "borderWidth":"-1",
            "borderFill":{
              "fillType":"solid",
              "color":0xFF000000}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"65054270b7a64f72a3c4f723aa4a32cb",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":1316,
                  "y":78},
                "size":{
                  "width":22,
                  "height":22},
                "borderWidth":"-1",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF000000}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/咨询药店/u25.png"}},
{
          "id":"0ab6f77e136d49cfb0a76296014cd1e1",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "fontName":"'Arial Normal', 'Arial'",
            "fontSize":"16px",
            "fontWeight":"400",
            "location":{
              "x":1342,
              "y":80},
            "size":{
              "width":65,
              "height":19}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"c60c302a2ca8464190dd95f0e7bbcb91",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Normal', 'Arial'",
                "fontSize":"16px",
                "fontWeight":"400",
                "location":{
                  "x":1342,
                  "y":80},
                "size":{
                  "width":65,
                  "height":19}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"fb836c0be96a47da85017c1c6ee8a9fd",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF666666,
              "opacity":1},
            "location":{
              "x":1436,
              "y":116},
            "size":{
              "width":62,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"809746d7174542f1bdc0bc89bac0ee34",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF666666,
                  "opacity":1},
                "location":{
                  "x":1436,
                  "y":116},
                "size":{
                  "width":62,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"bf56e4dc9daf417bb3c81980cd41fda9",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":1310,
              "y":484},
            "size":{
              "width":320,
              "height":45}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"9a8e3862de4c4bd6be71edbea693d126",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":1310,
                  "y":484},
                "size":{
                  "width":320,
                  "height":45}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/举报药店/u42.png"}},
{
          "id":"53bdf7a9988a4524b971cc73fc861e49",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":1318,
              "y":488},
            "size":{
              "width":305,
              "height":35},
            "borderFill":{
              "fillType":"solid",
              "color":0xFF999999},
            "cornerRadiusTopLeft":"8"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"5695cab07a09448aaea2f1e47d1357c8",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":1318,
                  "y":488},
                "size":{
                  "width":305,
                  "height":35},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF999999},
                "cornerRadiusTopLeft":"8"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/举报药店/u44.png"}},
{
          "id":"a72fe797bd0f4e42a3b130658f431c0a",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":1587,
              "y":492},
            "size":{
              "width":30,
              "height":30}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"0b41285fdfcf4fe0a5a17e6e5173e4df",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":1587,
                  "y":492},
                "size":{
                  "width":30,
                  "height":30}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/举报药店/u46.png"}},
{
          "id":"7e2e48225ded498084955f64e2945975",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "fontName":"'Arial Normal', 'Arial'",
            "fontSize":"16px",
            "fontWeight":"400",
            "location":{
              "x":1310,
              "y":19},
            "size":{
              "width":185,
              "height":19}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"087a9b9e897840e89023429394443903",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Normal', 'Arial'",
                "fontSize":"16px",
                "fontWeight":"400",
                "location":{
                  "x":1310,
                  "y":19},
                "size":{
                  "width":185,
                  "height":19}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"21c46b64ad5f410dadf8200411f31bb9",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFCCCCCC,
              "opacity":1},
            "location":{
              "x":1319,
              "y":142},
            "size":{
              "width":45,
              "height":45},
            "borderFill":{
              "fillType":"solid",
              "color":0xFF999999}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"f0884844d8534e04bda7cdeee91b11b7",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC,
                  "opacity":1},
                "location":{
                  "x":1319,
                  "y":142},
                "size":{
                  "width":45,
                  "height":45},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF999999}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/我的问药/u34.png"}},
{
          "id":"e19917d955394152878dcb9c7941afba",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontSize":"12px",
            "horizontalAlignment":"left",
            "verticalAlignment":"top",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF000000,
              "opacity":1},
            "location":{
              "x":1371,
              "y":142},
            "size":{
              "width":230,
              "height":88},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFCCCCCC},
            "cornerRadiusTopLeft":"10"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"2505aa995f084908b63f654d076d16c1",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"12px",
                "horizontalAlignment":"left",
                "verticalAlignment":"top",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF000000,
                  "opacity":1},
                "location":{
                  "x":1371,
                  "y":142},
                "size":{
                  "width":230,
                  "height":88},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC},
                "cornerRadiusTopLeft":"10"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/关于问药/u119.png"}},
{
          "id":"48b8f16d0d3e4136bcd028a181e3bdb9",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"14px",
            "location":{
              "x":1386,
              "y":150},
            "size":{
              "width":204,
              "height":69}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"0de670b865c947c38687bee1482143e5",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"14px",
                "location":{
                  "x":1386,
                  "y":150},
                "size":{
                  "width":204,
                  "height":69}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"17a79496234e4809871c1009545fcc76",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":901,
              "y":313},
            "size":{
              "width":318,
              "height":216},
            "borderWidth":"-1",
            "borderFill":{
              "fillType":"solid",
              "color":0xFF000000}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"deca9b179c004e96bf94c3fc0017108c",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":901,
                  "y":313},
                "size":{
                  "width":318,
                  "height":216},
                "borderWidth":"-1",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF000000}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/添加用药/u132.png"}},
{
          "id":"7621bd87994d40469029470e93369fc7",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "fontName":"'Arial Normal', 'Arial'",
            "fontSize":"16px",
            "fontWeight":"400",
            "location":{
              "x":100,
              "y":21},
            "size":{
              "width":65,
              "height":19}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"3761fe32d0914615abee5865e19993a4",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Normal', 'Arial'",
                "fontSize":"16px",
                "fontWeight":"400",
                "location":{
                  "x":100,
                  "y":21},
                "size":{
                  "width":65,
                  "height":19}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"10b204e4276d4d7abe6f667c07ce550f",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "fontName":"'Arial Normal', 'Arial'",
            "fontSize":"16px",
            "fontWeight":"400",
            "location":{
              "x":500,
              "y":21},
            "size":{
              "width":65,
              "height":19}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"0aae77ecb50d4b2b994b9112f45ce46c",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Normal', 'Arial'",
                "fontSize":"16px",
                "fontWeight":"400",
                "location":{
                  "x":500,
                  "y":21},
                "size":{
                  "width":65,
                  "height":19}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"c83885214887457286c9e276a66fcfd9",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "fontName":"'Arial Normal', 'Arial'",
            "fontSize":"16px",
            "fontWeight":"400",
            "location":{
              "x":900,
              "y":21},
            "size":{
              "width":65,
              "height":19}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"a75318a117424902a0d7fa41b96cfa1c",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Normal', 'Arial'",
                "fontSize":"16px",
                "fontWeight":"400",
                "location":{
                  "x":900,
                  "y":21},
                "size":{
                  "width":65,
                  "height":19}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}}]}},
  "masters":{
},
  "objectPaths":{
    "c080b8006bf54190a601b3e250801fd6":{
      "scriptId":"u0"},
    "79b1e540683e40d7bd7a32049fe81633":{
      "scriptId":"u1"},
    "eeb3770ed0eb4f0084c3ec7debddedde":{
      "scriptId":"u2"},
    "c2b7ab11d8ed46ce80279d4cf3f20b94":{
      "scriptId":"u3"},
    "908875171011450e905534cccc660c5c":{
      "scriptId":"u4"},
    "bd548ba86bc7428ba3b027265ddb3042":{
      "scriptId":"u5"},
    "e60f44dd0f0f4d19b66899192954cc09":{
      "scriptId":"u6"},
    "41bf15beda554844b0fdfba522b7f897":{
      "scriptId":"u7"},
    "5815f8e2c2e841f890319693cbb66019":{
      "scriptId":"u8"},
    "9c90c46d6e8a4671bacb0b0f0c2c45b2":{
      "scriptId":"u9"},
    "91adcbb2a0224c38958eee20b2e530eb":{
      "scriptId":"u10"},
    "1ede6e4c4d2643d7bad37f9dcf386bcb":{
      "scriptId":"u11"},
    "d999b670f6b248499edc61afa642bb8f":{
      "scriptId":"u12"},
    "258095fe519d4b048b2171c13ba080d3":{
      "scriptId":"u13"},
    "b02bc32537f240ac8f0c3f84611801ca":{
      "scriptId":"u14"},
    "a18dec9035bb4fb9ac4cb6f32b587d0b":{
      "scriptId":"u15"},
    "1bf892501d664311aa656d4e48d25493":{
      "scriptId":"u16"},
    "2b6079e5eae9451c8d209b871e386150":{
      "scriptId":"u17"},
    "7f6adfe94ee14ef88f976118c340748b":{
      "scriptId":"u18"},
    "7d133a69f86c4b3da412e22303b94f68":{
      "scriptId":"u19"},
    "e4d5862c62fc49198cbf69b5dd245e9d":{
      "scriptId":"u20"},
    "f9dd3db384ab46ad9cec84056fa05b4e":{
      "scriptId":"u21"},
    "7ecebf8f7a6447c1b6cbfc3dc2331e86":{
      "scriptId":"u22"},
    "926e18ce2acd4d2889a4599d69360150":{
      "scriptId":"u23"},
    "b013f742d904494081c45972a64b555d":{
      "scriptId":"u24"},
    "fa88a52d008b4adc8d3fbb18d40b471a":{
      "scriptId":"u25"},
    "d30f7c114def4b388e24b1de602f3bb7":{
      "scriptId":"u26"},
    "522bdada066d446cada8ca0c4a51d1b9":{
      "scriptId":"u27"},
    "d34864762e7841d891cf12c541212a36":{
      "scriptId":"u28"},
    "7fabb8e36fcf4489af8da5d50395c57b":{
      "scriptId":"u29"},
    "985b3d133b6b4d23a956be078c703749":{
      "scriptId":"u30"},
    "3d6e0565a80646be8bcfb194781d56cf":{
      "scriptId":"u31"},
    "43309fae62724bdc8df0a925abd95453":{
      "scriptId":"u32"},
    "d2ab4f101970473397266ac04e09a6c3":{
      "scriptId":"u33"},
    "9fc0eb1d7c914d11826eabe4e377db4d":{
      "scriptId":"u34"},
    "743e41327a424053aab3feb461d0eb57":{
      "scriptId":"u35"},
    "83830bbde0194a89a193a9c631541c6e":{
      "scriptId":"u36"},
    "974d20bc0080469e8fb0f7400b2d8004":{
      "scriptId":"u37"},
    "5b89d1933e7945c2bfcdde722cf553e0":{
      "scriptId":"u38"},
    "a9ba90e4699543228bf7082c37e01fba":{
      "scriptId":"u39"},
    "3e7afcad7ad347e0b6fbedf53ded739f":{
      "scriptId":"u40"},
    "d74b9fbeae9e47a096eeb8e154cf2852":{
      "scriptId":"u41"},
    "5dc6b08a2ef24e54b26f82d1e1097c13":{
      "scriptId":"u42"},
    "4155cf3a1c9c4a6486bad74298b2384b":{
      "scriptId":"u43"},
    "e8f8694028354c4b8fd1436138fb12e6":{
      "scriptId":"u44"},
    "8989c612c14a4a419b693d5884024574":{
      "scriptId":"u45"},
    "847f3319189d4182a9be3d0a6aa92693":{
      "scriptId":"u46"},
    "e0c1d3219c204b488c120df0757fda90":{
      "scriptId":"u47"},
    "456112f70199458c9bee78bf516d5744":{
      "scriptId":"u48"},
    "ddc215ba865e4ac2a0c28458cabb905c":{
      "scriptId":"u49"},
    "f3d57716509a4a69a43e172946402906":{
      "scriptId":"u50"},
    "86ccdc3d2ad046f29a273b1c86cbd0d0":{
      "scriptId":"u51"},
    "2bb2fba4835c4daeaaa1f5abdf9735d8":{
      "scriptId":"u52"},
    "dba548d498174cdda90089e729a6e5a9":{
      "scriptId":"u53"},
    "87811449e1ea4e5193aee1972a42eac9":{
      "scriptId":"u54"},
    "249e4a7002764e3b9a58635e1cbf7241":{
      "scriptId":"u55"},
    "c6870b52f0024f0a9f5fefeddb3a8b2c":{
      "scriptId":"u56"},
    "b2b029d1f68d4cba8ea68891ca4cb975":{
      "scriptId":"u57"},
    "41caf260c77f4cc398eba4b1d8e4e4bf":{
      "scriptId":"u58"},
    "f952c62414d340ce90a2c86c36a85b22":{
      "scriptId":"u59"},
    "9e545f6b0bc449e19b18bf0eeb77dd6a":{
      "scriptId":"u60"},
    "669392ec7b5546129d0c95949eda7ce8":{
      "scriptId":"u61"},
    "1d98f598d20c43a59976da177173fa96":{
      "scriptId":"u62"},
    "53fe89ccdf864309a4995eeac75e3790":{
      "scriptId":"u63"},
    "4b0a91607519400c81d20a19cca6556e":{
      "scriptId":"u64"},
    "fdfdf4656cf446b29cbdfcac81f36a22":{
      "scriptId":"u65"},
    "860f57736ebf480d9d19622a4bd39d11":{
      "scriptId":"u66"},
    "8dc2700d6b434c30bc3fdfeb3ca85a0f":{
      "scriptId":"u67"},
    "0f163b2d8328493fb8d8a044dc1abb16":{
      "scriptId":"u68"},
    "847bc5ce55144844aea60a039ac924fa":{
      "scriptId":"u69"},
    "44623fc27a8944eca9bea2e2ef78a1d1":{
      "scriptId":"u70"},
    "9e03914dd77e4e46a7ae07570e6e022d":{
      "scriptId":"u71"},
    "dee58ecc20af4879a304e639da69106d":{
      "scriptId":"u72"},
    "a0b42f8bc1e0433fa614f10034ab2713":{
      "scriptId":"u73"},
    "64160b9364b043eaa00b2efcd3c55a6c":{
      "scriptId":"u74"},
    "cb3f3ad1a3b44e9383628a37e6f0e111":{
      "scriptId":"u75"},
    "7b57fee775ad444488d57d8ecf957a94":{
      "scriptId":"u76"},
    "824997005627447fa555a537220af289":{
      "scriptId":"u77"},
    "e19b02cb42614be5b807abc47aa9c44a":{
      "scriptId":"u78"},
    "4f496202720240f3a136ff7b53aadbaf":{
      "scriptId":"u79"},
    "08e213a86d9347eab1a6c333ee7c5dd6":{
      "scriptId":"u80"},
    "691281b7911a48d5875b5cf4bb0ff248":{
      "scriptId":"u81"},
    "4e4474789d2b4e10adaf000bc3437afd":{
      "scriptId":"u82"},
    "88643b9f508e45ecb4ffc9ff0da76b40":{
      "scriptId":"u83"},
    "ce9d107844e0486aa5e0f0c92554f377":{
      "scriptId":"u84"},
    "4f5b475463d2404d91022d4b187cb88a":{
      "scriptId":"u85"},
    "20ec81f289d14e11b0581c742fff5ac4":{
      "scriptId":"u86"},
    "53dfbb001db04980b2d9f64859a77fcd":{
      "scriptId":"u87"},
    "db728c55c27f4fbeb8737cc70ea83c36":{
      "scriptId":"u88"},
    "459ae565bf814c2d87d9ed76a3e0e5be":{
      "scriptId":"u89"},
    "d232eff9c0ae422ca0c7f7a8abd85010":{
      "scriptId":"u90"},
    "4370f7b0330c4e6ebe217437ccb70c11":{
      "scriptId":"u91"},
    "973e0bc4ab9049d2ac1eb0cdd82049e0":{
      "scriptId":"u92"},
    "cf8fec415a924db9b3d3ff89dd484157":{
      "scriptId":"u93"},
    "f2dbf853564048259cb326235d13b972":{
      "scriptId":"u94"},
    "5eb6956f64c844e595c33babe64284d5":{
      "scriptId":"u95"},
    "4c75493331994baaa59a35fa696a43b2":{
      "scriptId":"u96"},
    "b35a563f3d1d4202b268b62bb1cdf874":{
      "scriptId":"u97"},
    "86ca9eb8b1e04accbadd97d82e073dc9":{
      "scriptId":"u98"},
    "25ce4fa7d447431a832d07a068d1a7a1":{
      "scriptId":"u99"},
    "b55e2c886a394aa6b8c8fa6ac0fec961":{
      "scriptId":"u100"},
    "9192824d6ffe49a0b1e8500e123d6347":{
      "scriptId":"u101"},
    "a53f4572720d4c05acc41bbd0d193df4":{
      "scriptId":"u102"},
    "077b7fe9dc0a43219348df5955787b9f":{
      "scriptId":"u103"},
    "65054270b7a64f72a3c4f723aa4a32cb":{
      "scriptId":"u104"},
    "0ab6f77e136d49cfb0a76296014cd1e1":{
      "scriptId":"u105"},
    "c60c302a2ca8464190dd95f0e7bbcb91":{
      "scriptId":"u106"},
    "fb836c0be96a47da85017c1c6ee8a9fd":{
      "scriptId":"u107"},
    "809746d7174542f1bdc0bc89bac0ee34":{
      "scriptId":"u108"},
    "bf56e4dc9daf417bb3c81980cd41fda9":{
      "scriptId":"u109"},
    "9a8e3862de4c4bd6be71edbea693d126":{
      "scriptId":"u110"},
    "53bdf7a9988a4524b971cc73fc861e49":{
      "scriptId":"u111"},
    "5695cab07a09448aaea2f1e47d1357c8":{
      "scriptId":"u112"},
    "a72fe797bd0f4e42a3b130658f431c0a":{
      "scriptId":"u113"},
    "0b41285fdfcf4fe0a5a17e6e5173e4df":{
      "scriptId":"u114"},
    "7e2e48225ded498084955f64e2945975":{
      "scriptId":"u115"},
    "087a9b9e897840e89023429394443903":{
      "scriptId":"u116"},
    "21c46b64ad5f410dadf8200411f31bb9":{
      "scriptId":"u117"},
    "f0884844d8534e04bda7cdeee91b11b7":{
      "scriptId":"u118"},
    "e19917d955394152878dcb9c7941afba":{
      "scriptId":"u119"},
    "2505aa995f084908b63f654d076d16c1":{
      "scriptId":"u120"},
    "48b8f16d0d3e4136bcd028a181e3bdb9":{
      "scriptId":"u121"},
    "0de670b865c947c38687bee1482143e5":{
      "scriptId":"u122"},
    "17a79496234e4809871c1009545fcc76":{
      "scriptId":"u123"},
    "deca9b179c004e96bf94c3fc0017108c":{
      "scriptId":"u124"},
    "7621bd87994d40469029470e93369fc7":{
      "scriptId":"u125"},
    "3761fe32d0914615abee5865e19993a4":{
      "scriptId":"u126"},
    "10b204e4276d4d7abe6f667c07ce550f":{
      "scriptId":"u127"},
    "0aae77ecb50d4b2b994b9112f45ce46c":{
      "scriptId":"u128"},
    "c83885214887457286c9e276a66fcfd9":{
      "scriptId":"u129"},
    "a75318a117424902a0d7fa41b96cfa1c":{
      "scriptId":"u130"}}});