$axure.loadCurrentPage({
  "url":"删除消息.html",
  "generationDate":new Date(1409493103885.8),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"308212d4d86445ea80573e1622fc6941",
    "type":"Axure:Page",
    "name":"删除消息",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"应用字体",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"255a0f5e97d345aa897b928d9b1b968e",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":100,
              "y":50},
            "size":{
              "width":320,
              "height":480}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"aeec5658ac584f6690b03deebdd59f60",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":100,
                  "y":50},
                "size":{
                  "width":320,
                  "height":480}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/我的问药/u0.png"}},
{
          "id":"01d9aadcebe242fab7c3719e8ab6ad54",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":375,
              "y":296},
            "size":{
              "width":35,
              "height":35},
            "borderWidth":"-1",
            "borderFill":{
              "fillType":"solid",
              "color":0xFF000000}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"19d296eaf51e476dbe026300e184594b",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":375,
                  "y":296},
                "size":{
                  "width":35,
                  "height":35},
                "borderWidth":"-1",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF000000}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/发起咨询/u24.png"}},
{
          "id":"c2a61f9d7e1d47718078b42bb919cfd1",
          "label":"top",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":100,
              "y":50},
            "size":{
              "width":320,
              "height":20},
            "rotation":"0",
            "textRotation":"0",
            "borderWidth":"0",
            "cornerRadiusTopLeft":"0"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"b3ba243573364bd6ab5da392afaefe9d",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":100,
                  "y":50},
                "size":{
                  "width":320,
                  "height":20},
                "rotation":"0",
                "textRotation":"0",
                "borderWidth":"0",
                "cornerRadiusTopLeft":"0"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/我的问药/top_u2.png"}},
{
          "id":"591671c86914463e9d2cd48ece78a102",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":100,
              "y":70},
            "size":{
              "width":320,
              "height":40}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"43c2a67801ba4de5bde9f580a91218c2",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":100,
                  "y":70},
                "size":{
                  "width":320,
                  "height":40}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/药店详情/u2.png"}},
{
          "id":"3c50b0499c4b4bb9a21866383c9944b5",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":106,
              "y":80},
            "size":{
              "width":22,
              "height":22},
            "borderWidth":"-1",
            "borderFill":{
              "fillType":"solid",
              "color":0xFF000000}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"aabe6edd2d1b4ce29b90770de4ff9802",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":106,
                  "y":80},
                "size":{
                  "width":22,
                  "height":22},
                "borderWidth":"-1",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF000000}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/咨询药店/u25.png"}},
{
          "id":"138ee85ae9944f449cbbccc6b3b2d379",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "fontName":"'Arial Normal', 'Arial'",
            "fontSize":"16px",
            "fontWeight":"400",
            "location":{
              "x":132,
              "y":82},
            "size":{
              "width":101,
              "height":19}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"7a1a20fbb5cc4834ab398a32657924fc",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Normal', 'Arial'",
                "fontSize":"16px",
                "fontWeight":"400",
                "location":{
                  "x":132,
                  "y":82},
                "size":{
                  "width":101,
                  "height":19}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"6534ad7f0b6b46949f47582200d7357c",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "horizontalAlignment":"left",
            "location":{
              "x":160,
              "y":144},
            "size":{
              "width":210,
              "height":106},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFCCCCCC},
            "cornerRadiusTopLeft":"10"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"ab05f706b902433db9f8926566322d15",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "horizontalAlignment":"left",
                "location":{
                  "x":160,
                  "y":144},
                "size":{
                  "width":210,
                  "height":106},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC},
                "cornerRadiusTopLeft":"10"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/发起咨询/u34.png"}},
{
          "id":"eae008170b4c48f3a581bcdbcb73a0bc",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF666666,
              "opacity":1},
            "location":{
              "x":224,
              "y":118},
            "size":{
              "width":67,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"7fd89f4673d747ce835cf153d21396f2",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF666666,
                  "opacity":1},
                "location":{
                  "x":224,
                  "y":118},
                "size":{
                  "width":67,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"034d6629f4f74107914e7ac24c4a723f",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "horizontalAlignment":"left",
            "location":{
              "x":160,
              "y":296},
            "size":{
              "width":210,
              "height":35},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFCCCCCC},
            "cornerRadiusTopLeft":"10"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"81b4c08e9a0f440dad73d5ee64c3ffc4",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "horizontalAlignment":"left",
                "location":{
                  "x":160,
                  "y":296},
                "size":{
                  "width":210,
                  "height":35},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC},
                "cornerRadiusTopLeft":"10"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/发起咨询/u38.png"}},
{
          "id":"906beed55003407e8fae1a4a1ae9ce62",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":340,
              "y":302},
            "size":{
              "width":22,
              "height":22}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"9436a730049d45ccb4fa3e3910b5ab46",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":340,
                  "y":302},
                "size":{
                  "width":22,
                  "height":22}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/发起咨询/u40.png"}},
{
          "id":"dbeaadb3a6db42c79b8d1f0b50228b32",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF666666,
              "opacity":1},
            "location":{
              "x":247,
              "y":270},
            "size":{
              "width":26,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"dd8bb38c3151470d8436cbfc32364fba",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF666666,
                  "opacity":1},
                "location":{
                  "x":247,
                  "y":270},
                "size":{
                  "width":26,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"3350771ac0384d8ea231fa30742efbc7",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":100,
              "y":486},
            "size":{
              "width":320,
              "height":45}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"3eba587752e2474aad7e8fe4b8589965",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":100,
                  "y":486},
                "size":{
                  "width":320,
                  "height":45}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/举报药店/u42.png"}},
{
          "id":"61852ac0b4ff4e77b6d4e0163ec52ac3",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "horizontalAlignment":"left",
            "location":{
              "x":108,
              "y":490},
            "size":{
              "width":305,
              "height":35},
            "borderFill":{
              "fillType":"solid",
              "color":0xFF999999},
            "cornerRadiusTopLeft":"8"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"f4d9691a83c34486b5f0d2201686ef29",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "horizontalAlignment":"left",
                "location":{
                  "x":108,
                  "y":490},
                "size":{
                  "width":305,
                  "height":35},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF999999},
                "cornerRadiusTopLeft":"8"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/举报药店/u44.png"}},
{
          "id":"47df8a40c01d4481a0f7182613c4f03a",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":378,
              "y":494},
            "size":{
              "width":30,
              "height":30}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"c64a23c909dd4b9e8734b8f8b43c41be",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":378,
                  "y":494},
                "size":{
                  "width":30,
                  "height":30}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/举报药店/u46.png"}},
{
          "id":"c8f969c9832948e19fd3abef0d5b87ff",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFCCCCCC,
              "opacity":1},
            "location":{
              "x":109,
              "y":144},
            "size":{
              "width":45,
              "height":45},
            "borderFill":{
              "fillType":"solid",
              "color":0xFF999999},
            "cornerRadiusTopLeft":"6"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"d8a534840db84ae8ac6b531454499a82",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC,
                  "opacity":1},
                "location":{
                  "x":109,
                  "y":144},
                "size":{
                  "width":45,
                  "height":45},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF999999},
                "cornerRadiusTopLeft":"6"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/发起咨询/u20.png"}},
{
          "id":"fd0c57b0c3bf4d9b9d3326eb4789ec2b",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "horizontalAlignment":"left",
            "location":{
              "x":160,
              "y":351},
            "size":{
              "width":210,
              "height":49},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFCCCCCC},
            "cornerRadiusTopLeft":"10"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"677ac9f344d04b8c8bb80401d1b876fe",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "horizontalAlignment":"left",
                "location":{
                  "x":160,
                  "y":351},
                "size":{
                  "width":210,
                  "height":49},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC},
                "cornerRadiusTopLeft":"10"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/删除消息/u30.png"}},
{
          "id":"08739ba6ca094ed5a25f96be510b122a",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFCCCCCC,
              "opacity":1},
            "location":{
              "x":109,
              "y":351},
            "size":{
              "width":45,
              "height":45},
            "borderFill":{
              "fillType":"solid",
              "color":0xFF999999},
            "cornerRadiusTopLeft":"6"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"d9861314886848ce93e97023dd5aa5ce",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC,
                  "opacity":1},
                "location":{
                  "x":109,
                  "y":351},
                "size":{
                  "width":45,
                  "height":45},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF999999},
                "cornerRadiusTopLeft":"6"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/发起咨询/u20.png"}},
{
          "id":"c9a7a435336948339c68bb7c8afefdb5",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "fill":{
              "fillType":"solid",
              "color":0x99333333},
            "location":{
              "x":230,
              "y":322},
            "size":{
              "width":70,
              "height":29}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"a77a889cb88d4d278a5f0b179940b7d3",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0x99333333},
                "location":{
                  "x":230,
                  "y":322},
                "size":{
                  "width":70,
                  "height":29}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/删除消息/u34.png"}},
{
          "id":"7360cb81650547b9955f2461c1c10a51",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":500,
              "y":50},
            "size":{
              "width":320,
              "height":480}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"38d120d606444608823524561b6555a9",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":500,
                  "y":50},
                "size":{
                  "width":320,
                  "height":480}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/我的问药/u0.png"}},
{
          "id":"398387eef85c4ee1a2b66ffd57d505b6",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":775,
              "y":296},
            "size":{
              "width":35,
              "height":35},
            "borderWidth":"-1",
            "borderFill":{
              "fillType":"solid",
              "color":0xFF000000}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"cf619a09bbcd40f48e6fcbc5504f79c2",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":775,
                  "y":296},
                "size":{
                  "width":35,
                  "height":35},
                "borderWidth":"-1",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF000000}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/发起咨询/u24.png"}},
{
          "id":"81ce11c299914d828a7f4c820baec2c4",
          "label":"top",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":500,
              "y":50},
            "size":{
              "width":320,
              "height":20},
            "rotation":"0",
            "textRotation":"0",
            "borderWidth":"0",
            "cornerRadiusTopLeft":"0"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"a2b8e8a8fd1743b28b3514828ae0c136",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":500,
                  "y":50},
                "size":{
                  "width":320,
                  "height":20},
                "rotation":"0",
                "textRotation":"0",
                "borderWidth":"0",
                "cornerRadiusTopLeft":"0"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/我的问药/top_u2.png"}},
{
          "id":"0ad9b4f4e1c249e2965d7c70827fb750",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":500,
              "y":70},
            "size":{
              "width":320,
              "height":40}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"d2a9ab10d16a474286be3d303706dc96",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":500,
                  "y":70},
                "size":{
                  "width":320,
                  "height":40}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/药店详情/u2.png"}},
{
          "id":"3feac245158343bca95511d1615acc9c",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":506,
              "y":80},
            "size":{
              "width":22,
              "height":22},
            "borderWidth":"-1",
            "borderFill":{
              "fillType":"solid",
              "color":0xFF000000}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"656410c57c7045778a7ba3e03eab6cc2",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":506,
                  "y":80},
                "size":{
                  "width":22,
                  "height":22},
                "borderWidth":"-1",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF000000}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/咨询药店/u25.png"}},
{
          "id":"37bbd3661a3d4462a8deb9b1bdf2d278",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "fontName":"'Arial Normal', 'Arial'",
            "fontSize":"16px",
            "fontWeight":"400",
            "location":{
              "x":532,
              "y":82},
            "size":{
              "width":101,
              "height":19}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"25e3e0ee5a884c529da9a257cbbe4fb7",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Normal', 'Arial'",
                "fontSize":"16px",
                "fontWeight":"400",
                "location":{
                  "x":532,
                  "y":82},
                "size":{
                  "width":101,
                  "height":19}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"ed272b3c155341d9adfa245147800528",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "horizontalAlignment":"left",
            "location":{
              "x":560,
              "y":144},
            "size":{
              "width":210,
              "height":106},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFCCCCCC},
            "cornerRadiusTopLeft":"10"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"81f66f1c00804dfd8e591bfc24ecc496",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "horizontalAlignment":"left",
                "location":{
                  "x":560,
                  "y":144},
                "size":{
                  "width":210,
                  "height":106},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC},
                "cornerRadiusTopLeft":"10"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/发起咨询/u34.png"}},
{
          "id":"0ea772f18e944b24b568b898411035c3",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF666666,
              "opacity":1},
            "location":{
              "x":624,
              "y":118},
            "size":{
              "width":67,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"4da10245ebd94b29a72dfe4251e1e8ee",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF666666,
                  "opacity":1},
                "location":{
                  "x":624,
                  "y":118},
                "size":{
                  "width":67,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"d26b4e335e7c4ed4851eb2534b75e52e",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "horizontalAlignment":"left",
            "location":{
              "x":560,
              "y":296},
            "size":{
              "width":210,
              "height":35},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFCCCCCC},
            "cornerRadiusTopLeft":"10"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"47121229c68e466f80fc7063ea5247b7",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "horizontalAlignment":"left",
                "location":{
                  "x":560,
                  "y":296},
                "size":{
                  "width":210,
                  "height":35},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC},
                "cornerRadiusTopLeft":"10"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/发起咨询/u38.png"}},
{
          "id":"ca69356ee34a49db88206f53cbde44e7",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":740,
              "y":302},
            "size":{
              "width":22,
              "height":22}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"3f8c0affde7e409788256376c14ad154",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":740,
                  "y":302},
                "size":{
                  "width":22,
                  "height":22}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/发起咨询/u40.png"}},
{
          "id":"a0fb327f0c9f41528e98b2c650be1c00",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF666666,
              "opacity":1},
            "location":{
              "x":647,
              "y":270},
            "size":{
              "width":26,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"4c4aada2710247beb1bddcc37dd0d8c0",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF666666,
                  "opacity":1},
                "location":{
                  "x":647,
                  "y":270},
                "size":{
                  "width":26,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"f5f208788274490696ea69d3fb864268",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":500,
              "y":486},
            "size":{
              "width":320,
              "height":45}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"83160e08e40f470ba992e9358603890d",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":500,
                  "y":486},
                "size":{
                  "width":320,
                  "height":45}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/举报药店/u42.png"}},
{
          "id":"f028a6808a794950b0948e889c3e391d",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "horizontalAlignment":"left",
            "location":{
              "x":508,
              "y":490},
            "size":{
              "width":305,
              "height":35},
            "borderFill":{
              "fillType":"solid",
              "color":0xFF999999},
            "cornerRadiusTopLeft":"8"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"17627017b0894640bcbd749c11ddf3d0",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "horizontalAlignment":"left",
                "location":{
                  "x":508,
                  "y":490},
                "size":{
                  "width":305,
                  "height":35},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF999999},
                "cornerRadiusTopLeft":"8"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/举报药店/u44.png"}},
{
          "id":"16f2d3de5e6a449a91954cd73ce6bcf5",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":778,
              "y":494},
            "size":{
              "width":30,
              "height":30}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"94c5c14cd6d941c39263c10637ee60aa",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":778,
                  "y":494},
                "size":{
                  "width":30,
                  "height":30}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/举报药店/u46.png"}},
{
          "id":"aa535f708d8342bd9ef66ee6546dde8e",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFCCCCCC,
              "opacity":1},
            "location":{
              "x":509,
              "y":144},
            "size":{
              "width":45,
              "height":45},
            "borderFill":{
              "fillType":"solid",
              "color":0xFF999999},
            "cornerRadiusTopLeft":"6"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"8e411f99e98a4ecd90d9f611c97b1073",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC,
                  "opacity":1},
                "location":{
                  "x":509,
                  "y":144},
                "size":{
                  "width":45,
                  "height":45},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF999999},
                "cornerRadiusTopLeft":"6"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/发起咨询/u20.png"}},
{
          "id":"f516dc8f9dc94101b1b3ca5e9fa0c7df",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "fontName":"'Arial Normal', 'Arial'",
            "fontSize":"16px",
            "fontWeight":"400",
            "location":{
              "x":100,
              "y":21},
            "size":{
              "width":129,
              "height":19}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"ec59e3afceb34beca3b61f5da4853391",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Normal', 'Arial'",
                "fontSize":"16px",
                "fontWeight":"400",
                "location":{
                  "x":100,
                  "y":21},
                "size":{
                  "width":129,
                  "height":19}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"49f3f741658348e7830b9f1df7b3bcde",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "fontName":"'Arial Normal', 'Arial'",
            "fontSize":"16px",
            "fontWeight":"400",
            "location":{
              "x":500,
              "y":21},
            "size":{
              "width":129,
              "height":19}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"bfd12dbb070b440dadcefb0e1ba99e11",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Normal', 'Arial'",
                "fontSize":"16px",
                "fontWeight":"400",
                "location":{
                  "x":500,
                  "y":21},
                "size":{
                  "width":129,
                  "height":19}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}}]}},
  "masters":{
},
  "objectPaths":{
    "255a0f5e97d345aa897b928d9b1b968e":{
      "scriptId":"u0"},
    "aeec5658ac584f6690b03deebdd59f60":{
      "scriptId":"u1"},
    "01d9aadcebe242fab7c3719e8ab6ad54":{
      "scriptId":"u2"},
    "19d296eaf51e476dbe026300e184594b":{
      "scriptId":"u3"},
    "c2a61f9d7e1d47718078b42bb919cfd1":{
      "scriptId":"u4"},
    "b3ba243573364bd6ab5da392afaefe9d":{
      "scriptId":"u5"},
    "591671c86914463e9d2cd48ece78a102":{
      "scriptId":"u6"},
    "43c2a67801ba4de5bde9f580a91218c2":{
      "scriptId":"u7"},
    "3c50b0499c4b4bb9a21866383c9944b5":{
      "scriptId":"u8"},
    "aabe6edd2d1b4ce29b90770de4ff9802":{
      "scriptId":"u9"},
    "138ee85ae9944f449cbbccc6b3b2d379":{
      "scriptId":"u10"},
    "7a1a20fbb5cc4834ab398a32657924fc":{
      "scriptId":"u11"},
    "6534ad7f0b6b46949f47582200d7357c":{
      "scriptId":"u12"},
    "ab05f706b902433db9f8926566322d15":{
      "scriptId":"u13"},
    "eae008170b4c48f3a581bcdbcb73a0bc":{
      "scriptId":"u14"},
    "7fd89f4673d747ce835cf153d21396f2":{
      "scriptId":"u15"},
    "034d6629f4f74107914e7ac24c4a723f":{
      "scriptId":"u16"},
    "81b4c08e9a0f440dad73d5ee64c3ffc4":{
      "scriptId":"u17"},
    "906beed55003407e8fae1a4a1ae9ce62":{
      "scriptId":"u18"},
    "9436a730049d45ccb4fa3e3910b5ab46":{
      "scriptId":"u19"},
    "dbeaadb3a6db42c79b8d1f0b50228b32":{
      "scriptId":"u20"},
    "dd8bb38c3151470d8436cbfc32364fba":{
      "scriptId":"u21"},
    "3350771ac0384d8ea231fa30742efbc7":{
      "scriptId":"u22"},
    "3eba587752e2474aad7e8fe4b8589965":{
      "scriptId":"u23"},
    "61852ac0b4ff4e77b6d4e0163ec52ac3":{
      "scriptId":"u24"},
    "f4d9691a83c34486b5f0d2201686ef29":{
      "scriptId":"u25"},
    "47df8a40c01d4481a0f7182613c4f03a":{
      "scriptId":"u26"},
    "c64a23c909dd4b9e8734b8f8b43c41be":{
      "scriptId":"u27"},
    "c8f969c9832948e19fd3abef0d5b87ff":{
      "scriptId":"u28"},
    "d8a534840db84ae8ac6b531454499a82":{
      "scriptId":"u29"},
    "fd0c57b0c3bf4d9b9d3326eb4789ec2b":{
      "scriptId":"u30"},
    "677ac9f344d04b8c8bb80401d1b876fe":{
      "scriptId":"u31"},
    "08739ba6ca094ed5a25f96be510b122a":{
      "scriptId":"u32"},
    "d9861314886848ce93e97023dd5aa5ce":{
      "scriptId":"u33"},
    "c9a7a435336948339c68bb7c8afefdb5":{
      "scriptId":"u34"},
    "a77a889cb88d4d278a5f0b179940b7d3":{
      "scriptId":"u35"},
    "7360cb81650547b9955f2461c1c10a51":{
      "scriptId":"u36"},
    "38d120d606444608823524561b6555a9":{
      "scriptId":"u37"},
    "398387eef85c4ee1a2b66ffd57d505b6":{
      "scriptId":"u38"},
    "cf619a09bbcd40f48e6fcbc5504f79c2":{
      "scriptId":"u39"},
    "81ce11c299914d828a7f4c820baec2c4":{
      "scriptId":"u40"},
    "a2b8e8a8fd1743b28b3514828ae0c136":{
      "scriptId":"u41"},
    "0ad9b4f4e1c249e2965d7c70827fb750":{
      "scriptId":"u42"},
    "d2a9ab10d16a474286be3d303706dc96":{
      "scriptId":"u43"},
    "3feac245158343bca95511d1615acc9c":{
      "scriptId":"u44"},
    "656410c57c7045778a7ba3e03eab6cc2":{
      "scriptId":"u45"},
    "37bbd3661a3d4462a8deb9b1bdf2d278":{
      "scriptId":"u46"},
    "25e3e0ee5a884c529da9a257cbbe4fb7":{
      "scriptId":"u47"},
    "ed272b3c155341d9adfa245147800528":{
      "scriptId":"u48"},
    "81f66f1c00804dfd8e591bfc24ecc496":{
      "scriptId":"u49"},
    "0ea772f18e944b24b568b898411035c3":{
      "scriptId":"u50"},
    "4da10245ebd94b29a72dfe4251e1e8ee":{
      "scriptId":"u51"},
    "d26b4e335e7c4ed4851eb2534b75e52e":{
      "scriptId":"u52"},
    "47121229c68e466f80fc7063ea5247b7":{
      "scriptId":"u53"},
    "ca69356ee34a49db88206f53cbde44e7":{
      "scriptId":"u54"},
    "3f8c0affde7e409788256376c14ad154":{
      "scriptId":"u55"},
    "a0fb327f0c9f41528e98b2c650be1c00":{
      "scriptId":"u56"},
    "4c4aada2710247beb1bddcc37dd0d8c0":{
      "scriptId":"u57"},
    "f5f208788274490696ea69d3fb864268":{
      "scriptId":"u58"},
    "83160e08e40f470ba992e9358603890d":{
      "scriptId":"u59"},
    "f028a6808a794950b0948e889c3e391d":{
      "scriptId":"u60"},
    "17627017b0894640bcbd749c11ddf3d0":{
      "scriptId":"u61"},
    "16f2d3de5e6a449a91954cd73ce6bcf5":{
      "scriptId":"u62"},
    "94c5c14cd6d941c39263c10637ee60aa":{
      "scriptId":"u63"},
    "aa535f708d8342bd9ef66ee6546dde8e":{
      "scriptId":"u64"},
    "8e411f99e98a4ecd90d9f611c97b1073":{
      "scriptId":"u65"},
    "f516dc8f9dc94101b1b3ca5e9fa0c7df":{
      "scriptId":"u66"},
    "ec59e3afceb34beca3b61f5da4853391":{
      "scriptId":"u67"},
    "49f3f741658348e7830b9f1df7b3bcde":{
      "scriptId":"u68"},
    "bfd12dbb070b440dadcefb0e1ba99e11":{
      "scriptId":"u69"}}});