$axure.loadCurrentPage({
  "url":"快速自查.html",
  "generationDate":new Date(1409456734214.09),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"c7e7e5b8a7c54972a58b4ff526cded84",
    "type":"Axure:Page",
    "name":"快速自查",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"应用字体",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"c77a5252372e4d01898b3e344ba6a968",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":100,
              "y":50},
            "size":{
              "width":320,
              "height":480}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"7b82cf26832e4cf084a1e8e35b43d3e9",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":100,
                  "y":50},
                "size":{
                  "width":320,
                  "height":480}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/我的问药/u0.png"}},
{
          "id":"d62889377e354afe9f4664983ed6aac0",
          "label":"top",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":100,
              "y":50},
            "size":{
              "width":320,
              "height":20},
            "rotation":"0",
            "textRotation":"0",
            "borderWidth":"0",
            "cornerRadiusTopLeft":"0"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"7d60095ccf2c48e1a356e9f87801d106",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":100,
                  "y":50},
                "size":{
                  "width":320,
                  "height":20},
                "rotation":"0",
                "textRotation":"0",
                "borderWidth":"0",
                "cornerRadiusTopLeft":"0"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/我的问药/top_u2.png"}},
{
          "id":"1ec9d25c59594cc29ba2f7efc95e0e0b",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontSize":"12px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF008000,
              "opacity":1},
            "location":{
              "x":180,
              "y":485},
            "size":{
              "width":81,
              "height":45}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"aee474663419430d816a20aaa11a17b5",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"12px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF008000,
                  "opacity":1},
                "location":{
                  "x":180,
                  "y":485},
                "size":{
                  "width":81,
                  "height":45}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/我的问药/u4.png"}},
{
          "id":"fe8b445e03ff49fbaa9b53f9d8c1523c",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontSize":"12px",
            "location":{
              "x":100,
              "y":485},
            "size":{
              "width":81,
              "height":45}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"3b17f5032d8242f6b0d901edd424e297",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"12px",
                "location":{
                  "x":100,
                  "y":485},
                "size":{
                  "width":81,
                  "height":45}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/我的问药/u4.png"}},
{
          "id":"6d87320881b24e06bdcef20f86ebc76c",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontSize":"12px",
            "location":{
              "x":260,
              "y":485},
            "size":{
              "width":81,
              "height":45}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"11483aa3a6b14fc6a42845ba6cf90f23",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"12px",
                "location":{
                  "x":260,
                  "y":485},
                "size":{
                  "width":81,
                  "height":45}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/我的问药/u4.png"}},
{
          "id":"f0d07e00ac504333b10689aa489a15db",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontSize":"12px",
            "location":{
              "x":340,
              "y":485},
            "size":{
              "width":80,
              "height":45}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"84f64875f556405d9e32948711c963d7",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"12px",
                "location":{
                  "x":340,
                  "y":485},
                "size":{
                  "width":80,
                  "height":45}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/我的问药/u10.png"}},
{
          "id":"531332b09865477294cc0d5212476978",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "horizontalAlignment":"left",
            "location":{
              "x":100,
              "y":70},
            "size":{
              "width":320,
              "height":35}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"38402224830645ad96b39588cc3c1032",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "horizontalAlignment":"left",
                "location":{
                  "x":100,
                  "y":70},
                "size":{
                  "width":320,
                  "height":35}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/我的问药/u12.png"}},
{
          "id":"c44da26454824d8ca8f8cbd5bebd6a83",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "location":{
              "x":100,
              "y":13},
            "size":{
              "width":19,
              "height":37}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"b0287d5219c447febbd36eab9570d7fe",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":100,
                  "y":13},
                "size":{
                  "width":19,
                  "height":37}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"ee9536d05c7b473a88a667e4ec4df3d4",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "fontName":"'Arial Normal', 'Arial'",
            "fontSize":"16px",
            "fontWeight":"400",
            "location":{
              "x":121,
              "y":22},
            "size":{
              "width":65,
              "height":19}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"1091587471b94ec0aeb91f361d8424fd",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Normal', 'Arial'",
                "fontSize":"16px",
                "fontWeight":"400",
                "location":{
                  "x":121,
                  "y":22},
                "size":{
                  "width":65,
                  "height":19}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"f80f5168e8d84f9b80b6ee4727de6737",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'Arial Negreta', 'Arial'",
            "fontWeight":"700",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "fill":{
              "fillType":"solid",
              "color":0xFFFF0000},
            "location":{
              "x":159,
              "y":487},
            "size":{
              "width":20,
              "height":20},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF},
            "cornerRadiusTopLeft":"50"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"61c7f2f2bd684a1687d51591ce0e18a3",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Negreta', 'Arial'",
                "fontWeight":"700",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFF0000},
                "location":{
                  "x":159,
                  "y":487},
                "size":{
                  "width":20,
                  "height":20},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF},
                "cornerRadiusTopLeft":"50"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/我的问药/u36.png"}},
{
          "id":"2a7a92196d8946acb1b98ae93ecced5d",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "horizontalAlignment":"left",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF999999,
              "opacity":1},
            "location":{
              "x":110,
              "y":125},
            "size":{
              "width":300,
              "height":33},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFCCCCCC},
            "cornerRadiusTopLeft":"1"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"edf8dbb512454bcda16a6c9af4871b95",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "horizontalAlignment":"left",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF999999,
                  "opacity":1},
                "location":{
                  "x":110,
                  "y":125},
                "size":{
                  "width":300,
                  "height":33},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC},
                "cornerRadiusTopLeft":"1"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/快速自查/u20.png"}},
{
          "id":"b859f8f1f6a74b17bfaa3c83d1cbdfbc",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":387,
              "y":132},
            "size":{
              "width":20,
              "height":22},
            "borderWidth":"-1",
            "borderFill":{
              "fillType":"solid",
              "color":0xFF000000}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"76649f2c705445b9b0c57fc427dc129d",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":387,
                  "y":132},
                "size":{
                  "width":20,
                  "height":22},
                "borderWidth":"-1",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF000000}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/我的问药/u20.png"}},
{
          "id":"a4e2c06208e9430b9afc8aefb421ec75",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":110,
              "y":177},
            "size":{
              "width":100,
              "height":80},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFCCCCCC}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"6be8ec0b5aa1418ca6ff2b2eaedcd7c1",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":110,
                  "y":177},
                "size":{
                  "width":100,
                  "height":80},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/快速自查/u24.png"}},
{
          "id":"d7d0520f89cb4d499e116cea054a4c45",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":209,
              "y":177},
            "size":{
              "width":100,
              "height":80},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFCCCCCC}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"0e5c0aa1da9645248918f696f4e66308",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":209,
                  "y":177},
                "size":{
                  "width":100,
                  "height":80},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/快速自查/u24.png"}},
{
          "id":"b8a62e70898c48db9703b506b18e1ef2",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":308,
              "y":177},
            "size":{
              "width":100,
              "height":80},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFCCCCCC}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"04b1f6dd3a8e437bb4e76959f9fac323",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":308,
                  "y":177},
                "size":{
                  "width":100,
                  "height":80},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/快速自查/u24.png"}},
{
          "id":"acfe1a9c55fc4518a9c10a8ff608c97e",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":110,
              "y":256},
            "size":{
              "width":100,
              "height":80},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFCCCCCC}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"14eb1a670e8246fc8b5d292a6f0938c5",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":110,
                  "y":256},
                "size":{
                  "width":100,
                  "height":80},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/快速自查/u24.png"}},
{
          "id":"5c28661babf14f5793a52b6e771343fd",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":209,
              "y":256},
            "size":{
              "width":100,
              "height":80},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFCCCCCC}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"57fce5c6e1c940ddbf841b150fcf0d3f",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":209,
                  "y":256},
                "size":{
                  "width":100,
                  "height":80},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/快速自查/u24.png"}},
{
          "id":"84c2d3773c98447a98f15621e1b6d6e6",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":308,
              "y":256},
            "size":{
              "width":100,
              "height":80},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFCCCCCC}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"672ef773cc974dd38c319849e4f3deae",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":308,
                  "y":256},
                "size":{
                  "width":100,
                  "height":80},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/快速自查/u24.png"}}]}},
  "masters":{
},
  "objectPaths":{
    "c77a5252372e4d01898b3e344ba6a968":{
      "scriptId":"u0"},
    "7b82cf26832e4cf084a1e8e35b43d3e9":{
      "scriptId":"u1"},
    "d62889377e354afe9f4664983ed6aac0":{
      "scriptId":"u2"},
    "7d60095ccf2c48e1a356e9f87801d106":{
      "scriptId":"u3"},
    "1ec9d25c59594cc29ba2f7efc95e0e0b":{
      "scriptId":"u4"},
    "aee474663419430d816a20aaa11a17b5":{
      "scriptId":"u5"},
    "fe8b445e03ff49fbaa9b53f9d8c1523c":{
      "scriptId":"u6"},
    "3b17f5032d8242f6b0d901edd424e297":{
      "scriptId":"u7"},
    "6d87320881b24e06bdcef20f86ebc76c":{
      "scriptId":"u8"},
    "11483aa3a6b14fc6a42845ba6cf90f23":{
      "scriptId":"u9"},
    "f0d07e00ac504333b10689aa489a15db":{
      "scriptId":"u10"},
    "84f64875f556405d9e32948711c963d7":{
      "scriptId":"u11"},
    "531332b09865477294cc0d5212476978":{
      "scriptId":"u12"},
    "38402224830645ad96b39588cc3c1032":{
      "scriptId":"u13"},
    "c44da26454824d8ca8f8cbd5bebd6a83":{
      "scriptId":"u14"},
    "b0287d5219c447febbd36eab9570d7fe":{
      "scriptId":"u15"},
    "ee9536d05c7b473a88a667e4ec4df3d4":{
      "scriptId":"u16"},
    "1091587471b94ec0aeb91f361d8424fd":{
      "scriptId":"u17"},
    "f80f5168e8d84f9b80b6ee4727de6737":{
      "scriptId":"u18"},
    "61c7f2f2bd684a1687d51591ce0e18a3":{
      "scriptId":"u19"},
    "2a7a92196d8946acb1b98ae93ecced5d":{
      "scriptId":"u20"},
    "edf8dbb512454bcda16a6c9af4871b95":{
      "scriptId":"u21"},
    "b859f8f1f6a74b17bfaa3c83d1cbdfbc":{
      "scriptId":"u22"},
    "76649f2c705445b9b0c57fc427dc129d":{
      "scriptId":"u23"},
    "a4e2c06208e9430b9afc8aefb421ec75":{
      "scriptId":"u24"},
    "6be8ec0b5aa1418ca6ff2b2eaedcd7c1":{
      "scriptId":"u25"},
    "d7d0520f89cb4d499e116cea054a4c45":{
      "scriptId":"u26"},
    "0e5c0aa1da9645248918f696f4e66308":{
      "scriptId":"u27"},
    "b8a62e70898c48db9703b506b18e1ef2":{
      "scriptId":"u28"},
    "04b1f6dd3a8e437bb4e76959f9fac323":{
      "scriptId":"u29"},
    "acfe1a9c55fc4518a9c10a8ff608c97e":{
      "scriptId":"u30"},
    "14eb1a670e8246fc8b5d292a6f0938c5":{
      "scriptId":"u31"},
    "5c28661babf14f5793a52b6e771343fd":{
      "scriptId":"u32"},
    "57fce5c6e1c940ddbf841b150fcf0d3f":{
      "scriptId":"u33"},
    "84c2d3773c98447a98f15621e1b6d6e6":{
      "scriptId":"u34"},
    "672ef773cc974dd38c319849e4f3deae":{
      "scriptId":"u35"}}});