$axure.loadCurrentPage({
  "url":"全维药事.html",
  "generationDate":new Date(1409493103076.75),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"c5db48a68d9841e7b6d2dad2183c07df",
    "type":"Axure:Page",
    "name":"全维药事",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"应用字体",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"f754e835064e4815b7cde0096a0a23be",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":100,
              "y":49},
            "size":{
              "width":320,
              "height":480}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"978ad995fc2b4f63b8af96cecfe75141",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":100,
                  "y":49},
                "size":{
                  "width":320,
                  "height":480}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/我的问药/u0.png"}},
{
          "id":"e22aa14071b24e96b6873f0cec1d8f01",
          "label":"top",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":100,
              "y":49},
            "size":{
              "width":320,
              "height":20},
            "rotation":"0",
            "textRotation":"0",
            "borderWidth":"0",
            "cornerRadiusTopLeft":"0"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"966111157bf140ad8517d0087c712304",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":100,
                  "y":49},
                "size":{
                  "width":320,
                  "height":20},
                "rotation":"0",
                "textRotation":"0",
                "borderWidth":"0",
                "cornerRadiusTopLeft":"0"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/我的问药/top_u2.png"}},
{
          "id":"087c7738c8eb4364bd590129e4de841c",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":100,
              "y":69},
            "size":{
              "width":320,
              "height":40}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"2ac9d88d75c1473185815be3b6fc9c7a",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":100,
                  "y":69},
                "size":{
                  "width":320,
                  "height":40}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/药店详情/u2.png"}},
{
          "id":"03817ba40bf349288da9413ad428a000",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":106,
              "y":79},
            "size":{
              "width":22,
              "height":22},
            "borderWidth":"-1",
            "borderFill":{
              "fillType":"solid",
              "color":0xFF000000}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"3a5b40d79fd74ab39d4b05f2d9284a5a",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":106,
                  "y":79},
                "size":{
                  "width":22,
                  "height":22},
                "borderWidth":"-1",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF000000}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/咨询药店/u25.png"}},
{
          "id":"9ec50e89179b4c5ab7d95b225bc4fe80",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "fontName":"'Arial Normal', 'Arial'",
            "fontSize":"16px",
            "fontWeight":"400",
            "location":{
              "x":132,
              "y":81},
            "size":{
              "width":65,
              "height":19}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"768a571dc21a4830b4d07f39391f6985",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Normal', 'Arial'",
                "fontSize":"16px",
                "fontWeight":"400",
                "location":{
                  "x":132,
                  "y":81},
                "size":{
                  "width":65,
                  "height":19}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"38fa98a7d4ca4df28afea660587991f7",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF666666,
              "opacity":1},
            "location":{
              "x":226,
              "y":117},
            "size":{
              "width":62,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"b6bb5cd8760845eb94af929c3f6a887c",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF666666,
                  "opacity":1},
                "location":{
                  "x":226,
                  "y":117},
                "size":{
                  "width":62,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"9d28191b264a464696de077ba2eaa246",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":100,
              "y":485},
            "size":{
              "width":320,
              "height":45}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"7fee0e28761a45d7ac6cca9dedf04d62",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":100,
                  "y":485},
                "size":{
                  "width":320,
                  "height":45}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/举报药店/u42.png"}},
{
          "id":"5ed64a13b7cf456c998f0f1c27976451",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":108,
              "y":489},
            "size":{
              "width":305,
              "height":35},
            "borderFill":{
              "fillType":"solid",
              "color":0xFF999999},
            "cornerRadiusTopLeft":"8"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"ec659aec60de4ecab6db24787ced6b3a",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":108,
                  "y":489},
                "size":{
                  "width":305,
                  "height":35},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF999999},
                "cornerRadiusTopLeft":"8"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/举报药店/u44.png"}},
{
          "id":"02117089dc00430a86c89c94fdc4b38a",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":377,
              "y":493},
            "size":{
              "width":30,
              "height":30}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"c41eaa5b726a41f497866a0897aa6b7e",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":377,
                  "y":493},
                "size":{
                  "width":30,
                  "height":30}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/举报药店/u46.png"}},
{
          "id":"cf41cb898b7c497a823f7777292ce616",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "fontName":"'Arial Normal', 'Arial'",
            "fontSize":"16px",
            "fontWeight":"400",
            "location":{
              "x":100,
              "y":21},
            "size":{
              "width":158,
              "height":19}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"994a753ba62f4b5b8fb7697f854277d1",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Normal', 'Arial'",
                "fontSize":"16px",
                "fontWeight":"400",
                "location":{
                  "x":100,
                  "y":21},
                "size":{
                  "width":158,
                  "height":19}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"a6722a0175884e8aa6462621a11f6401",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFCCCCCC,
              "opacity":1},
            "location":{
              "x":109,
              "y":143},
            "size":{
              "width":45,
              "height":45},
            "borderFill":{
              "fillType":"solid",
              "color":0xFF999999}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"fbe69cb3c9b14cdcb8f8078ec26fcd76",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC,
                  "opacity":1},
                "location":{
                  "x":109,
                  "y":143},
                "size":{
                  "width":45,
                  "height":45},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF999999}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/我的问药/u34.png"}},
{
          "id":"754068095c2c431798e051133dc12761",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":500,
              "y":49},
            "size":{
              "width":320,
              "height":480}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"8eda6b64e42943c2a4a6ef0e6bedf559",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":500,
                  "y":49},
                "size":{
                  "width":320,
                  "height":480}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/我的问药/u0.png"}},
{
          "id":"9d5e68c805df488e91948e142daf2176",
          "label":"top",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":500,
              "y":49},
            "size":{
              "width":320,
              "height":20},
            "rotation":"0",
            "textRotation":"0",
            "borderWidth":"0",
            "cornerRadiusTopLeft":"0"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"9a7f4e591175494e9b9966536b958dae",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":500,
                  "y":49},
                "size":{
                  "width":320,
                  "height":20},
                "rotation":"0",
                "textRotation":"0",
                "borderWidth":"0",
                "cornerRadiusTopLeft":"0"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/我的问药/top_u2.png"}},
{
          "id":"a628ea7ce20e4e4eba6fa2df9cb8bfdd",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":500,
              "y":69},
            "size":{
              "width":320,
              "height":40}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"6d1b12200b354bbda9ef35053b1fd608",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":500,
                  "y":69},
                "size":{
                  "width":320,
                  "height":40}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/药店详情/u2.png"}},
{
          "id":"d0ec8d23d67e479a9ee148260bf608d3",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":506,
              "y":79},
            "size":{
              "width":22,
              "height":22},
            "borderWidth":"-1",
            "borderFill":{
              "fillType":"solid",
              "color":0xFF000000}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"a48800120f9046cc8b3672402724224f",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":506,
                  "y":79},
                "size":{
                  "width":22,
                  "height":22},
                "borderWidth":"-1",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF000000}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/咨询药店/u25.png"}},
{
          "id":"d6b3924cc7a14dc3b682b0d9001fd154",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "fontName":"'Arial Normal', 'Arial'",
            "fontSize":"16px",
            "fontWeight":"400",
            "location":{
              "x":532,
              "y":81},
            "size":{
              "width":65,
              "height":19}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"13206f6cebec427a900b7121dc2d1e7c",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Normal', 'Arial'",
                "fontSize":"16px",
                "fontWeight":"400",
                "location":{
                  "x":532,
                  "y":81},
                "size":{
                  "width":65,
                  "height":19}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"d0567d22f26a4d108e0c6ac0e6c6a804",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "horizontalAlignment":"left",
            "location":{
              "x":560,
              "y":143},
            "size":{
              "width":230,
              "height":156},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFCCCCCC},
            "cornerRadiusTopLeft":"10"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"c202285f89f04bca8d06cb192fed35ee",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "horizontalAlignment":"left",
                "location":{
                  "x":560,
                  "y":143},
                "size":{
                  "width":230,
                  "height":156},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC},
                "cornerRadiusTopLeft":"10"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/全维药事/u32.png"}},
{
          "id":"159fa1eeb2d046768dfe48602bff16d0",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF666666,
              "opacity":1},
            "location":{
              "x":626,
              "y":117},
            "size":{
              "width":62,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"64b2a496aa77471f93489804c97254fd",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF666666,
                  "opacity":1},
                "location":{
                  "x":626,
                  "y":117},
                "size":{
                  "width":62,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"41b1f9b5cbdd4b929f72a06ac38e0e1a",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":500,
              "y":485},
            "size":{
              "width":320,
              "height":45}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"487dc26b1e214e5794d7a7dde99f56bd",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":500,
                  "y":485},
                "size":{
                  "width":320,
                  "height":45}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/举报药店/u42.png"}},
{
          "id":"b6afb6777ec6430994a339df7b449f5c",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":508,
              "y":489},
            "size":{
              "width":305,
              "height":35},
            "borderFill":{
              "fillType":"solid",
              "color":0xFF999999},
            "cornerRadiusTopLeft":"8"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"530216bf1a72403f82e63d07b4399f5c",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":508,
                  "y":489},
                "size":{
                  "width":305,
                  "height":35},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF999999},
                "cornerRadiusTopLeft":"8"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/举报药店/u44.png"}},
{
          "id":"58cda23e1c3f47abba39a0f5f83eff11",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":777,
              "y":493},
            "size":{
              "width":30,
              "height":30}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"af75959f0a0f4fb38e00d2130574ac61",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":777,
                  "y":493},
                "size":{
                  "width":30,
                  "height":30}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/举报药店/u46.png"}},
{
          "id":"89cbe0a4f7f04ff7ae0fe62e00d277b3",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFCCCCCC,
              "opacity":1},
            "location":{
              "x":509,
              "y":143},
            "size":{
              "width":45,
              "height":45},
            "borderFill":{
              "fillType":"solid",
              "color":0xFF999999}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"46ef509c037a40d9ac5cbfa94b4f844a",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC,
                  "opacity":1},
                "location":{
                  "x":509,
                  "y":143},
                "size":{
                  "width":45,
                  "height":45},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF999999}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/我的问药/u34.png"}},
{
          "id":"ffe6ec2e4d3047eda01f825ce85bd72e",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "fontName":"'Arial Normal', 'Arial'",
            "fontSize":"16px",
            "fontWeight":"400",
            "location":{
              "x":500,
              "y":21},
            "size":{
              "width":174,
              "height":19}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"a296da8ffe2a497ea4bd41344bb28c7a",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Normal', 'Arial'",
                "fontSize":"16px",
                "fontWeight":"400",
                "location":{
                  "x":500,
                  "y":21},
                "size":{
                  "width":174,
                  "height":19}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"adc18d42c8ba414894bc3c2f2bbf136d",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":778,
              "y":309},
            "size":{
              "width":35,
              "height":35},
            "borderWidth":"-1",
            "borderFill":{
              "fillType":"solid",
              "color":0xFF000000}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"37f68016a5ee4e00a7ae327e8b391d2f",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":778,
                  "y":309},
                "size":{
                  "width":35,
                  "height":35},
                "borderWidth":"-1",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF000000}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/发起咨询/u24.png"}},
{
          "id":"10a2bab1b31044c79f6bc844cdeafd0a",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "horizontalAlignment":"left",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF666666,
              "opacity":1},
            "location":{
              "x":670,
              "y":309},
            "size":{
              "width":103,
              "height":35},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFCCCCCC},
            "cornerRadiusTopLeft":"10"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"7235b6f0f31f4fa291bdad953d31cefc",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "horizontalAlignment":"left",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF666666,
                  "opacity":1},
                "location":{
                  "x":670,
                  "y":309},
                "size":{
                  "width":103,
                  "height":35},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC},
                "cornerRadiusTopLeft":"10"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/全维药事/u48.png"}},
{
          "id":"abb5a5c0188b417487afd7acc3809a6d",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFCCCCCC,
              "opacity":1},
            "location":{
              "x":509,
              "y":355},
            "size":{
              "width":45,
              "height":45},
            "borderFill":{
              "fillType":"solid",
              "color":0xFF999999}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"ff469f52c19b4ba5aefc01431ce8ca4e",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC,
                  "opacity":1},
                "location":{
                  "x":509,
                  "y":355},
                "size":{
                  "width":45,
                  "height":45},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF999999}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/我的问药/u34.png"}},
{
          "id":"1868eaf243e9458e8e2126f882a9bb72",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "horizontalAlignment":"left",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF666666,
              "opacity":1},
            "location":{
              "x":564,
              "y":355},
            "size":{
              "width":97,
              "height":35},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFCCCCCC},
            "cornerRadiusTopLeft":"10"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"86d0f58ac4724054afa1c7898cc8a1e9",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "horizontalAlignment":"left",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF666666,
                  "opacity":1},
                "location":{
                  "x":564,
                  "y":355},
                "size":{
                  "width":97,
                  "height":35},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC},
                "cornerRadiusTopLeft":"10"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/全维药事/u52.png"}},
{
          "id":"0b331998ca344031a24b6416ffef4525",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "horizontalAlignment":"left",
            "location":{
              "x":161,
              "y":143},
            "size":{
              "width":230,
              "height":156},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFCCCCCC},
            "cornerRadiusTopLeft":"10"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"325e8633d09141408d30b06c947f4794",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "horizontalAlignment":"left",
                "location":{
                  "x":161,
                  "y":143},
                "size":{
                  "width":230,
                  "height":156},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC},
                "cornerRadiusTopLeft":"10"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/全维药事/u32.png"}},
{
          "id":"0cd1a728c48d453c943f9b60138e1711",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":900,
              "y":49},
            "size":{
              "width":320,
              "height":480}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"5a68ec401ae2415284e1f73e1bbf152c",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":900,
                  "y":49},
                "size":{
                  "width":320,
                  "height":480}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/我的问药/u0.png"}},
{
          "id":"b284707f3f6047b2b47abbcb394e0248",
          "label":"top",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":900,
              "y":49},
            "size":{
              "width":320,
              "height":20},
            "rotation":"0",
            "textRotation":"0",
            "borderWidth":"0",
            "cornerRadiusTopLeft":"0"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"cf8b8f0675a044278b7e684744fdbf07",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":900,
                  "y":49},
                "size":{
                  "width":320,
                  "height":20},
                "rotation":"0",
                "textRotation":"0",
                "borderWidth":"0",
                "cornerRadiusTopLeft":"0"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/我的问药/top_u2.png"}},
{
          "id":"459276a88a4e46d58122b2797f001c74",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":900,
              "y":69},
            "size":{
              "width":320,
              "height":40}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"695796e299b44bbb9b5ea15899b21f58",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":900,
                  "y":69},
                "size":{
                  "width":320,
                  "height":40}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/药店详情/u2.png"}},
{
          "id":"aaf28966964a472b8474bdc7decb17f0",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":906,
              "y":79},
            "size":{
              "width":22,
              "height":22},
            "borderWidth":"-1",
            "borderFill":{
              "fillType":"solid",
              "color":0xFF000000}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"4b0b975e695843f8a374d2a21410ae44",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":906,
                  "y":79},
                "size":{
                  "width":22,
                  "height":22},
                "borderWidth":"-1",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF000000}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/咨询药店/u25.png"}},
{
          "id":"32602690b6e6473a89eca76ea9535dce",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "fontName":"'Arial Normal', 'Arial'",
            "fontSize":"16px",
            "fontWeight":"400",
            "location":{
              "x":932,
              "y":81},
            "size":{
              "width":65,
              "height":19}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"4e759e530f904a26b69b9cc6e1192ced",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Normal', 'Arial'",
                "fontSize":"16px",
                "fontWeight":"400",
                "location":{
                  "x":932,
                  "y":81},
                "size":{
                  "width":65,
                  "height":19}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"bbada909c44a4400b5a5e994dc575f4c",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":900,
              "y":485},
            "size":{
              "width":320,
              "height":45}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"4a90133e864843848ffd7d4bb691a632",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":900,
                  "y":485},
                "size":{
                  "width":320,
                  "height":45}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/举报药店/u42.png"}},
{
          "id":"ce26ada477de433d8433cf2931a37c5c",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":908,
              "y":489},
            "size":{
              "width":305,
              "height":35},
            "borderFill":{
              "fillType":"solid",
              "color":0xFF999999},
            "cornerRadiusTopLeft":"8"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"056059eb200d429ab5794489fddc74f7",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":908,
                  "y":489},
                "size":{
                  "width":305,
                  "height":35},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF999999},
                "cornerRadiusTopLeft":"8"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/举报药店/u44.png"}},
{
          "id":"3eb61c0d98974ab8895b36c757231b9f",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":1177,
              "y":493},
            "size":{
              "width":30,
              "height":30}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"eb35f730cebe43e18e6df340f9983946",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":1177,
                  "y":493},
                "size":{
                  "width":30,
                  "height":30}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/举报药店/u46.png"}},
{
          "id":"f8768d7cc7734ebcb8b97da5c16a1622",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "fontName":"'Arial Normal', 'Arial'",
            "fontSize":"16px",
            "fontWeight":"400",
            "location":{
              "x":900,
              "y":21},
            "size":{
              "width":206,
              "height":19}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"80445769ffbd4e55a41d01e8ec1d0c98",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Normal', 'Arial'",
                "fontSize":"16px",
                "fontWeight":"400",
                "location":{
                  "x":900,
                  "y":21},
                "size":{
                  "width":206,
                  "height":19}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"37f86e3938d44b6a890666a16248ee2f",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "horizontalAlignment":"left",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF666666,
              "opacity":1},
            "location":{
              "x":960,
              "y":143},
            "size":{
              "width":230,
              "height":66},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFCCCCCC},
            "cornerRadiusTopLeft":"10"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"2ea1aa49520b488ab733e17be75cd7f4",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "horizontalAlignment":"left",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF666666,
                  "opacity":1},
                "location":{
                  "x":960,
                  "y":143},
                "size":{
                  "width":230,
                  "height":66},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC},
                "cornerRadiusTopLeft":"10"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/举报药店/u48.png"}},
{
          "id":"83cd17ea726d4a3b875cece744a64fd5",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF666666,
              "opacity":1},
            "location":{
              "x":1026,
              "y":117},
            "size":{
              "width":62,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"e9099f842ce64f34985dcd31e6801586",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF666666,
                  "opacity":1},
                "location":{
                  "x":1026,
                  "y":117},
                "size":{
                  "width":62,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"f705eec4509b4977b07a65cf46dee810",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFCCCCCC,
              "opacity":1},
            "location":{
              "x":909,
              "y":143},
            "size":{
              "width":45,
              "height":45},
            "borderFill":{
              "fillType":"solid",
              "color":0xFF999999}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"e38c4913ab62405a87bd268d6785e83e",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC,
                  "opacity":1},
                "location":{
                  "x":909,
                  "y":143},
                "size":{
                  "width":45,
                  "height":45},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF999999}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/我的问药/u34.png"}},
{
          "id":"95bec766f1ba4df08e24a3700c45a944",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "horizontalAlignment":"left",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF666666,
              "opacity":1},
            "location":{
              "x":960,
              "y":255},
            "size":{
              "width":230,
              "height":66},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFCCCCCC},
            "cornerRadiusTopLeft":"10"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"a352a3f41b23400a906adc1bbeb8c9d6",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "horizontalAlignment":"left",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF666666,
                  "opacity":1},
                "location":{
                  "x":960,
                  "y":255},
                "size":{
                  "width":230,
                  "height":66},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC},
                "cornerRadiusTopLeft":"10"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/举报药店/u48.png"}},
{
          "id":"903c503b7735428aa454b599169910ea",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF666666,
              "opacity":1},
            "location":{
              "x":1026,
              "y":229},
            "size":{
              "width":62,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"6f4726266f074172a190bdbed2176d65",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF666666,
                  "opacity":1},
                "location":{
                  "x":1026,
                  "y":229},
                "size":{
                  "width":62,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"e579b45c08e54b7eb3971b6f7d9720c5",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFCCCCCC,
              "opacity":1},
            "location":{
              "x":909,
              "y":255},
            "size":{
              "width":45,
              "height":45},
            "borderFill":{
              "fillType":"solid",
              "color":0xFF999999}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"43900a71ed564bdbb8385126a8b58082",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC,
                  "opacity":1},
                "location":{
                  "x":909,
                  "y":255},
                "size":{
                  "width":45,
                  "height":45},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF999999}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/我的问药/u34.png"}},
{
          "id":"08acaa5352874dd190a68c645f6797aa",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":1300,
              "y":49},
            "size":{
              "width":320,
              "height":480}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"6bea48f1c10c4355924e40ed21bd40d4",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":1300,
                  "y":49},
                "size":{
                  "width":320,
                  "height":480}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/我的问药/u0.png"}},
{
          "id":"9a650674ff864463a2b0f79c2b21d376",
          "label":"top",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":1300,
              "y":49},
            "size":{
              "width":320,
              "height":20},
            "rotation":"0",
            "textRotation":"0",
            "borderWidth":"0",
            "cornerRadiusTopLeft":"0"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"4a9de95bfe0644dc806f283fa340168b",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":1300,
                  "y":49},
                "size":{
                  "width":320,
                  "height":20},
                "rotation":"0",
                "textRotation":"0",
                "borderWidth":"0",
                "cornerRadiusTopLeft":"0"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/我的问药/top_u2.png"}},
{
          "id":"148a7a16226d44baacb0cf657eaabe2c",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":1300,
              "y":69},
            "size":{
              "width":320,
              "height":40}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"189f54ba5bf54bbaa0026e3069cb67e7",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":1300,
                  "y":69},
                "size":{
                  "width":320,
                  "height":40}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/药店详情/u2.png"}},
{
          "id":"440696203352475ea71e3cf6ea362f06",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":1306,
              "y":79},
            "size":{
              "width":22,
              "height":22},
            "borderWidth":"-1",
            "borderFill":{
              "fillType":"solid",
              "color":0xFF000000}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"ce3b60f24d1944b282170b5e5fda3160",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":1306,
                  "y":79},
                "size":{
                  "width":22,
                  "height":22},
                "borderWidth":"-1",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF000000}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/咨询药店/u25.png"}},
{
          "id":"3b90925f0d90440eaac5bb566f61ed5b",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "fontName":"'Arial Normal', 'Arial'",
            "fontSize":"16px",
            "fontWeight":"400",
            "location":{
              "x":1332,
              "y":81},
            "size":{
              "width":65,
              "height":19}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"9c15545a75e64b1c9defac560d57bde6",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Normal', 'Arial'",
                "fontSize":"16px",
                "fontWeight":"400",
                "location":{
                  "x":1332,
                  "y":81},
                "size":{
                  "width":65,
                  "height":19}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"2d046e040ea9470e8ffc99efde1376df",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":1300,
              "y":485},
            "size":{
              "width":320,
              "height":45}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"c024cee70ca444de91ce2a1cc4df4bad",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":1300,
                  "y":485},
                "size":{
                  "width":320,
                  "height":45}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/举报药店/u42.png"}},
{
          "id":"912ca1b7ff92411ca2b51937a7d76c0f",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":1308,
              "y":489},
            "size":{
              "width":305,
              "height":35},
            "borderFill":{
              "fillType":"solid",
              "color":0xFF999999},
            "cornerRadiusTopLeft":"8"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"1650295fe3854abfa736407beb4a9f91",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":1308,
                  "y":489},
                "size":{
                  "width":305,
                  "height":35},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF999999},
                "cornerRadiusTopLeft":"8"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/举报药店/u44.png"}},
{
          "id":"192ee1c763ae412fae094e16c6c60239",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":1577,
              "y":493},
            "size":{
              "width":30,
              "height":30}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"1aa8c9512dc048afbadc05e8c96e341e",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":1577,
                  "y":493},
                "size":{
                  "width":30,
                  "height":30}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/举报药店/u46.png"}},
{
          "id":"4e95cbfe2dd9461590c11672bc85878f",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "fontName":"'Arial Normal', 'Arial'",
            "fontSize":"16px",
            "fontWeight":"400",
            "location":{
              "x":1300,
              "y":21},
            "size":{
              "width":174,
              "height":19}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"59b5524879ec4084b0a2f6e15c4db2e7",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Normal', 'Arial'",
                "fontSize":"16px",
                "fontWeight":"400",
                "location":{
                  "x":1300,
                  "y":21},
                "size":{
                  "width":174,
                  "height":19}},
              "adaptiveStyles":{
}}],
          "annotation":{
            "描述":"仅根据用户用药推送；"},
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"164a07fa544a4f6fb9a714045389fa9b",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":1700,
              "y":49},
            "size":{
              "width":320,
              "height":480}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"3fd60c755e4c45489b73d6f1fd0fa874",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":1700,
                  "y":49},
                "size":{
                  "width":320,
                  "height":480}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/我的问药/u0.png"}},
{
          "id":"f96bac9aea0a47c7a4a71625edf8669c",
          "label":"top",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":1700,
              "y":49},
            "size":{
              "width":320,
              "height":20},
            "rotation":"0",
            "textRotation":"0",
            "borderWidth":"0",
            "cornerRadiusTopLeft":"0"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"5b1d4d61671349f790a530b36f67910c",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":1700,
                  "y":49},
                "size":{
                  "width":320,
                  "height":20},
                "rotation":"0",
                "textRotation":"0",
                "borderWidth":"0",
                "cornerRadiusTopLeft":"0"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/我的问药/top_u2.png"}},
{
          "id":"24cb12e4caa24300a65fc78c7dedde6a",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":1700,
              "y":69},
            "size":{
              "width":320,
              "height":40}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"6aa072e7604c40e1958787a97013e4ec",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":1700,
                  "y":69},
                "size":{
                  "width":320,
                  "height":40}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/药店详情/u2.png"}},
{
          "id":"769d8d839ecb4b618270a371fe359473",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":1706,
              "y":79},
            "size":{
              "width":22,
              "height":22},
            "borderWidth":"-1",
            "borderFill":{
              "fillType":"solid",
              "color":0xFF000000}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"1aaeb64e7d294e3fb3b1a76e2cb5c793",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":1706,
                  "y":79},
                "size":{
                  "width":22,
                  "height":22},
                "borderWidth":"-1",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF000000}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/咨询药店/u25.png"}},
{
          "id":"48e1bbcc43d44d9db5e76170588b6754",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "fontName":"'Arial Normal', 'Arial'",
            "fontSize":"16px",
            "fontWeight":"400",
            "location":{
              "x":1732,
              "y":81},
            "size":{
              "width":97,
              "height":19}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"c2bca5b2a8794bd8ab1213407332d217",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Normal', 'Arial'",
                "fontSize":"16px",
                "fontWeight":"400",
                "location":{
                  "x":1732,
                  "y":81},
                "size":{
                  "width":97,
                  "height":19}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"5367df716f1c41728968ff793e252881",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":1700,
              "y":485},
            "size":{
              "width":320,
              "height":45}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"1c527ea375914b11b63061e10edf2cd2",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":1700,
                  "y":485},
                "size":{
                  "width":320,
                  "height":45}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/举报药店/u42.png"}},
{
          "id":"1044828d06714859aa7ec746f8083e3b",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":1708,
              "y":489},
            "size":{
              "width":305,
              "height":35},
            "borderFill":{
              "fillType":"solid",
              "color":0xFF999999},
            "cornerRadiusTopLeft":"8"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"a91ef6cac78144cfa13c350d2970165e",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":1708,
                  "y":489},
                "size":{
                  "width":305,
                  "height":35},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF999999},
                "cornerRadiusTopLeft":"8"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/举报药店/u44.png"}},
{
          "id":"d11cd756554a44a49fb4182b9fad2958",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":1977,
              "y":493},
            "size":{
              "width":30,
              "height":30}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"99b3861197eb4ed58d254fc2e279226d",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":1977,
                  "y":493},
                "size":{
                  "width":30,
                  "height":30}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/举报药店/u46.png"}},
{
          "id":"af6e56e6d4e64d2d8aa134316a052483",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "fontName":"'Arial Normal', 'Arial'",
            "fontSize":"16px",
            "fontWeight":"400",
            "location":{
              "x":1700,
              "y":21},
            "size":{
              "width":129,
              "height":19}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"208451b5638640b480cd734b63d43d20",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Normal', 'Arial'",
                "fontSize":"16px",
                "fontWeight":"400",
                "location":{
                  "x":1700,
                  "y":21},
                "size":{
                  "width":129,
                  "height":19}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"a9abe12b1dad471d921b2564e9c4df19",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFCCCCCC,
              "opacity":1},
            "location":{
              "x":1708,
              "y":119},
            "size":{
              "width":45,
              "height":45},
            "borderFill":{
              "fillType":"solid",
              "color":0xFF999999}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"35df289d6c99498094a236c6d3e8c000",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC,
                  "opacity":1},
                "location":{
                  "x":1708,
                  "y":119},
                "size":{
                  "width":45,
                  "height":45},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF999999}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/我的问药/u34.png"}},
{
          "id":"8aa51b404143418b805706c9e6058d0b",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "fontName":"'Arial Normal', 'Arial'",
            "fontSize":"14px",
            "fontWeight":"400",
            "location":{
              "x":1763,
              "y":133},
            "size":{
              "width":57,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"8f8e5b4fd64b4eb5a2895f4b8c621142",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Normal', 'Arial'",
                "fontSize":"14px",
                "fontWeight":"400",
                "location":{
                  "x":1763,
                  "y":133},
                "size":{
                  "width":57,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"bbb70602315043ee8915acd41e0a8dd0",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":1732,
              "y":181},
            "size":{
              "width":237,
              "height":64}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"8f8f2d3b25884a2c99d1d402d29efa1b",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":1732,
                  "y":181},
                "size":{
                  "width":237,
                  "height":64}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"c4b93fdb5e9b494691699b95501142fd",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "horizontalAlignment":"left",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF666666,
              "opacity":1},
            "location":{
              "x":1360,
              "y":145},
            "size":{
              "width":230,
              "height":145},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFCCCCCC},
            "cornerRadiusTopLeft":"10"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"9217e4fd40e4440f8cc7258f318f9632",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "horizontalAlignment":"left",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF666666,
                  "opacity":1},
                "location":{
                  "x":1360,
                  "y":145},
                "size":{
                  "width":230,
                  "height":145},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC},
                "cornerRadiusTopLeft":"10"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/全维药事/u128.png"}},
{
          "id":"0c384e2d0a764e85869829a8462b6e05",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF666666,
              "opacity":1},
            "location":{
              "x":1426,
              "y":119},
            "size":{
              "width":62,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"4f981c7caa0a407b9584fbe9b42df7f2",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF666666,
                  "opacity":1},
                "location":{
                  "x":1426,
                  "y":119},
                "size":{
                  "width":62,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"15aef58bcab14a1bab3ca9c1de1a1a5e",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFCCCCCC,
              "opacity":1},
            "location":{
              "x":1310,
              "y":145},
            "size":{
              "width":45,
              "height":45},
            "borderFill":{
              "fillType":"solid",
              "color":0xFF999999}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"945072f4ea804fb69ca1795c3f21fa66",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC,
                  "opacity":1},
                "location":{
                  "x":1310,
                  "y":145},
                "size":{
                  "width":45,
                  "height":45},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF999999}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/我的问药/u34.png"}},
{
          "id":"b2a112533587401d860bcf7b9beff14c",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "horizontalAlignment":"left",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF666666,
              "opacity":1},
            "location":{
              "x":1360,
              "y":329},
            "size":{
              "width":230,
              "height":133},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFCCCCCC},
            "cornerRadiusTopLeft":"10"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"9ad0810c8fbc43c9983a22153edf3bb1",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "horizontalAlignment":"left",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF666666,
                  "opacity":1},
                "location":{
                  "x":1360,
                  "y":329},
                "size":{
                  "width":230,
                  "height":133},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC},
                "cornerRadiusTopLeft":"10"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/全维药事/u134.png"}},
{
          "id":"77fca3f677c44bc5b229c43f66ab4065",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF666666,
              "opacity":1},
            "location":{
              "x":1426,
              "y":303},
            "size":{
              "width":62,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"222bacb5cf25445c92f0cd47e78cc7ce",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF666666,
                  "opacity":1},
                "location":{
                  "x":1426,
                  "y":303},
                "size":{
                  "width":62,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"3bf95447fa6b4245b1fb1277d9ed3146",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFCCCCCC,
              "opacity":1},
            "location":{
              "x":1310,
              "y":329},
            "size":{
              "width":45,
              "height":45},
            "borderFill":{
              "fillType":"solid",
              "color":0xFF999999}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"e8cbcc8570ba47dfb082551a22f6d2b6",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC,
                  "opacity":1},
                "location":{
                  "x":1310,
                  "y":329},
                "size":{
                  "width":45,
                  "height":45},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF999999}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/我的问药/u34.png"}},
{
          "id":"fca6d6843d014d929c2dcc8cca7f5099",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontSize":"11px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF666666,
              "opacity":1},
            "location":{
              "x":1827,
              "y":133},
            "size":{
              "width":31,
              "height":18},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFCCCCCC},
            "cornerRadiusTopLeft":"4"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"2039af5006fb48739a79896ef2ab126c",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"11px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF666666,
                  "opacity":1},
                "location":{
                  "x":1827,
                  "y":133},
                "size":{
                  "width":31,
                  "height":18},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC},
                "cornerRadiusTopLeft":"4"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/我的问药/u59.png"}}]}},
  "masters":{
},
  "objectPaths":{
    "f754e835064e4815b7cde0096a0a23be":{
      "scriptId":"u0"},
    "978ad995fc2b4f63b8af96cecfe75141":{
      "scriptId":"u1"},
    "e22aa14071b24e96b6873f0cec1d8f01":{
      "scriptId":"u2"},
    "966111157bf140ad8517d0087c712304":{
      "scriptId":"u3"},
    "087c7738c8eb4364bd590129e4de841c":{
      "scriptId":"u4"},
    "2ac9d88d75c1473185815be3b6fc9c7a":{
      "scriptId":"u5"},
    "03817ba40bf349288da9413ad428a000":{
      "scriptId":"u6"},
    "3a5b40d79fd74ab39d4b05f2d9284a5a":{
      "scriptId":"u7"},
    "9ec50e89179b4c5ab7d95b225bc4fe80":{
      "scriptId":"u8"},
    "768a571dc21a4830b4d07f39391f6985":{
      "scriptId":"u9"},
    "38fa98a7d4ca4df28afea660587991f7":{
      "scriptId":"u10"},
    "b6bb5cd8760845eb94af929c3f6a887c":{
      "scriptId":"u11"},
    "9d28191b264a464696de077ba2eaa246":{
      "scriptId":"u12"},
    "7fee0e28761a45d7ac6cca9dedf04d62":{
      "scriptId":"u13"},
    "5ed64a13b7cf456c998f0f1c27976451":{
      "scriptId":"u14"},
    "ec659aec60de4ecab6db24787ced6b3a":{
      "scriptId":"u15"},
    "02117089dc00430a86c89c94fdc4b38a":{
      "scriptId":"u16"},
    "c41eaa5b726a41f497866a0897aa6b7e":{
      "scriptId":"u17"},
    "cf41cb898b7c497a823f7777292ce616":{
      "scriptId":"u18"},
    "994a753ba62f4b5b8fb7697f854277d1":{
      "scriptId":"u19"},
    "a6722a0175884e8aa6462621a11f6401":{
      "scriptId":"u20"},
    "fbe69cb3c9b14cdcb8f8078ec26fcd76":{
      "scriptId":"u21"},
    "754068095c2c431798e051133dc12761":{
      "scriptId":"u22"},
    "8eda6b64e42943c2a4a6ef0e6bedf559":{
      "scriptId":"u23"},
    "9d5e68c805df488e91948e142daf2176":{
      "scriptId":"u24"},
    "9a7f4e591175494e9b9966536b958dae":{
      "scriptId":"u25"},
    "a628ea7ce20e4e4eba6fa2df9cb8bfdd":{
      "scriptId":"u26"},
    "6d1b12200b354bbda9ef35053b1fd608":{
      "scriptId":"u27"},
    "d0ec8d23d67e479a9ee148260bf608d3":{
      "scriptId":"u28"},
    "a48800120f9046cc8b3672402724224f":{
      "scriptId":"u29"},
    "d6b3924cc7a14dc3b682b0d9001fd154":{
      "scriptId":"u30"},
    "13206f6cebec427a900b7121dc2d1e7c":{
      "scriptId":"u31"},
    "d0567d22f26a4d108e0c6ac0e6c6a804":{
      "scriptId":"u32"},
    "c202285f89f04bca8d06cb192fed35ee":{
      "scriptId":"u33"},
    "159fa1eeb2d046768dfe48602bff16d0":{
      "scriptId":"u34"},
    "64b2a496aa77471f93489804c97254fd":{
      "scriptId":"u35"},
    "41b1f9b5cbdd4b929f72a06ac38e0e1a":{
      "scriptId":"u36"},
    "487dc26b1e214e5794d7a7dde99f56bd":{
      "scriptId":"u37"},
    "b6afb6777ec6430994a339df7b449f5c":{
      "scriptId":"u38"},
    "530216bf1a72403f82e63d07b4399f5c":{
      "scriptId":"u39"},
    "58cda23e1c3f47abba39a0f5f83eff11":{
      "scriptId":"u40"},
    "af75959f0a0f4fb38e00d2130574ac61":{
      "scriptId":"u41"},
    "89cbe0a4f7f04ff7ae0fe62e00d277b3":{
      "scriptId":"u42"},
    "46ef509c037a40d9ac5cbfa94b4f844a":{
      "scriptId":"u43"},
    "ffe6ec2e4d3047eda01f825ce85bd72e":{
      "scriptId":"u44"},
    "a296da8ffe2a497ea4bd41344bb28c7a":{
      "scriptId":"u45"},
    "adc18d42c8ba414894bc3c2f2bbf136d":{
      "scriptId":"u46"},
    "37f68016a5ee4e00a7ae327e8b391d2f":{
      "scriptId":"u47"},
    "10a2bab1b31044c79f6bc844cdeafd0a":{
      "scriptId":"u48"},
    "7235b6f0f31f4fa291bdad953d31cefc":{
      "scriptId":"u49"},
    "abb5a5c0188b417487afd7acc3809a6d":{
      "scriptId":"u50"},
    "ff469f52c19b4ba5aefc01431ce8ca4e":{
      "scriptId":"u51"},
    "1868eaf243e9458e8e2126f882a9bb72":{
      "scriptId":"u52"},
    "86d0f58ac4724054afa1c7898cc8a1e9":{
      "scriptId":"u53"},
    "0b331998ca344031a24b6416ffef4525":{
      "scriptId":"u54"},
    "325e8633d09141408d30b06c947f4794":{
      "scriptId":"u55"},
    "0cd1a728c48d453c943f9b60138e1711":{
      "scriptId":"u56"},
    "5a68ec401ae2415284e1f73e1bbf152c":{
      "scriptId":"u57"},
    "b284707f3f6047b2b47abbcb394e0248":{
      "scriptId":"u58"},
    "cf8b8f0675a044278b7e684744fdbf07":{
      "scriptId":"u59"},
    "459276a88a4e46d58122b2797f001c74":{
      "scriptId":"u60"},
    "695796e299b44bbb9b5ea15899b21f58":{
      "scriptId":"u61"},
    "aaf28966964a472b8474bdc7decb17f0":{
      "scriptId":"u62"},
    "4b0b975e695843f8a374d2a21410ae44":{
      "scriptId":"u63"},
    "32602690b6e6473a89eca76ea9535dce":{
      "scriptId":"u64"},
    "4e759e530f904a26b69b9cc6e1192ced":{
      "scriptId":"u65"},
    "bbada909c44a4400b5a5e994dc575f4c":{
      "scriptId":"u66"},
    "4a90133e864843848ffd7d4bb691a632":{
      "scriptId":"u67"},
    "ce26ada477de433d8433cf2931a37c5c":{
      "scriptId":"u68"},
    "056059eb200d429ab5794489fddc74f7":{
      "scriptId":"u69"},
    "3eb61c0d98974ab8895b36c757231b9f":{
      "scriptId":"u70"},
    "eb35f730cebe43e18e6df340f9983946":{
      "scriptId":"u71"},
    "f8768d7cc7734ebcb8b97da5c16a1622":{
      "scriptId":"u72"},
    "80445769ffbd4e55a41d01e8ec1d0c98":{
      "scriptId":"u73"},
    "37f86e3938d44b6a890666a16248ee2f":{
      "scriptId":"u74"},
    "2ea1aa49520b488ab733e17be75cd7f4":{
      "scriptId":"u75"},
    "83cd17ea726d4a3b875cece744a64fd5":{
      "scriptId":"u76"},
    "e9099f842ce64f34985dcd31e6801586":{
      "scriptId":"u77"},
    "f705eec4509b4977b07a65cf46dee810":{
      "scriptId":"u78"},
    "e38c4913ab62405a87bd268d6785e83e":{
      "scriptId":"u79"},
    "95bec766f1ba4df08e24a3700c45a944":{
      "scriptId":"u80"},
    "a352a3f41b23400a906adc1bbeb8c9d6":{
      "scriptId":"u81"},
    "903c503b7735428aa454b599169910ea":{
      "scriptId":"u82"},
    "6f4726266f074172a190bdbed2176d65":{
      "scriptId":"u83"},
    "e579b45c08e54b7eb3971b6f7d9720c5":{
      "scriptId":"u84"},
    "43900a71ed564bdbb8385126a8b58082":{
      "scriptId":"u85"},
    "08acaa5352874dd190a68c645f6797aa":{
      "scriptId":"u86"},
    "6bea48f1c10c4355924e40ed21bd40d4":{
      "scriptId":"u87"},
    "9a650674ff864463a2b0f79c2b21d376":{
      "scriptId":"u88"},
    "4a9de95bfe0644dc806f283fa340168b":{
      "scriptId":"u89"},
    "148a7a16226d44baacb0cf657eaabe2c":{
      "scriptId":"u90"},
    "189f54ba5bf54bbaa0026e3069cb67e7":{
      "scriptId":"u91"},
    "440696203352475ea71e3cf6ea362f06":{
      "scriptId":"u92"},
    "ce3b60f24d1944b282170b5e5fda3160":{
      "scriptId":"u93"},
    "3b90925f0d90440eaac5bb566f61ed5b":{
      "scriptId":"u94"},
    "9c15545a75e64b1c9defac560d57bde6":{
      "scriptId":"u95"},
    "2d046e040ea9470e8ffc99efde1376df":{
      "scriptId":"u96"},
    "c024cee70ca444de91ce2a1cc4df4bad":{
      "scriptId":"u97"},
    "912ca1b7ff92411ca2b51937a7d76c0f":{
      "scriptId":"u98"},
    "1650295fe3854abfa736407beb4a9f91":{
      "scriptId":"u99"},
    "192ee1c763ae412fae094e16c6c60239":{
      "scriptId":"u100"},
    "1aa8c9512dc048afbadc05e8c96e341e":{
      "scriptId":"u101"},
    "4e95cbfe2dd9461590c11672bc85878f":{
      "scriptId":"u102"},
    "59b5524879ec4084b0a2f6e15c4db2e7":{
      "scriptId":"u103"},
    "164a07fa544a4f6fb9a714045389fa9b":{
      "scriptId":"u104"},
    "3fd60c755e4c45489b73d6f1fd0fa874":{
      "scriptId":"u105"},
    "f96bac9aea0a47c7a4a71625edf8669c":{
      "scriptId":"u106"},
    "5b1d4d61671349f790a530b36f67910c":{
      "scriptId":"u107"},
    "24cb12e4caa24300a65fc78c7dedde6a":{
      "scriptId":"u108"},
    "6aa072e7604c40e1958787a97013e4ec":{
      "scriptId":"u109"},
    "769d8d839ecb4b618270a371fe359473":{
      "scriptId":"u110"},
    "1aaeb64e7d294e3fb3b1a76e2cb5c793":{
      "scriptId":"u111"},
    "48e1bbcc43d44d9db5e76170588b6754":{
      "scriptId":"u112"},
    "c2bca5b2a8794bd8ab1213407332d217":{
      "scriptId":"u113"},
    "5367df716f1c41728968ff793e252881":{
      "scriptId":"u114"},
    "1c527ea375914b11b63061e10edf2cd2":{
      "scriptId":"u115"},
    "1044828d06714859aa7ec746f8083e3b":{
      "scriptId":"u116"},
    "a91ef6cac78144cfa13c350d2970165e":{
      "scriptId":"u117"},
    "d11cd756554a44a49fb4182b9fad2958":{
      "scriptId":"u118"},
    "99b3861197eb4ed58d254fc2e279226d":{
      "scriptId":"u119"},
    "af6e56e6d4e64d2d8aa134316a052483":{
      "scriptId":"u120"},
    "208451b5638640b480cd734b63d43d20":{
      "scriptId":"u121"},
    "a9abe12b1dad471d921b2564e9c4df19":{
      "scriptId":"u122"},
    "35df289d6c99498094a236c6d3e8c000":{
      "scriptId":"u123"},
    "8aa51b404143418b805706c9e6058d0b":{
      "scriptId":"u124"},
    "8f8e5b4fd64b4eb5a2895f4b8c621142":{
      "scriptId":"u125"},
    "bbb70602315043ee8915acd41e0a8dd0":{
      "scriptId":"u126"},
    "8f8f2d3b25884a2c99d1d402d29efa1b":{
      "scriptId":"u127"},
    "c4b93fdb5e9b494691699b95501142fd":{
      "scriptId":"u128"},
    "9217e4fd40e4440f8cc7258f318f9632":{
      "scriptId":"u129"},
    "0c384e2d0a764e85869829a8462b6e05":{
      "scriptId":"u130"},
    "4f981c7caa0a407b9584fbe9b42df7f2":{
      "scriptId":"u131"},
    "15aef58bcab14a1bab3ca9c1de1a1a5e":{
      "scriptId":"u132"},
    "945072f4ea804fb69ca1795c3f21fa66":{
      "scriptId":"u133"},
    "b2a112533587401d860bcf7b9beff14c":{
      "scriptId":"u134"},
    "9ad0810c8fbc43c9983a22153edf3bb1":{
      "scriptId":"u135"},
    "77fca3f677c44bc5b229c43f66ab4065":{
      "scriptId":"u136"},
    "222bacb5cf25445c92f0cd47e78cc7ce":{
      "scriptId":"u137"},
    "3bf95447fa6b4245b1fb1277d9ed3146":{
      "scriptId":"u138"},
    "e8cbcc8570ba47dfb082551a22f6d2b6":{
      "scriptId":"u139"},
    "fca6d6843d014d929c2dcc8cca7f5099":{
      "scriptId":"u140"},
    "2039af5006fb48739a79896ef2ab126c":{
      "scriptId":"u141"}}});