$axure.loadCurrentPage({
  "url":"搜索用药.html",
  "generationDate":new Date(1409493102304.71),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"081a74c8d943407c8e7e7d36b7e7a985",
    "type":"Axure:Page",
    "name":"搜索用药",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"应用字体",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"f28470037ee741f68955c85e9543f640",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":900,
              "y":50},
            "size":{
              "width":320,
              "height":480}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"535af4cb6a7f424ca0e843071cf20dcc",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":900,
                  "y":50},
                "size":{
                  "width":320,
                  "height":480}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/我的问药/u0.png"}},
{
          "id":"a8e5f643eec04c94b402bbe6e920cce1",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":901,
              "y":314},
            "size":{
              "width":318,
              "height":216},
            "borderWidth":"-1",
            "borderFill":{
              "fillType":"solid",
              "color":0xFF000000}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"83f642d7debe46e68adfbe8e1b1fdf23",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":901,
                  "y":314},
                "size":{
                  "width":318,
                  "height":216},
                "borderWidth":"-1",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF000000}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/添加用药/u132.png"}},
{
          "id":"623d87b5ede44ff8b8c0cc28df53f576",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":100,
              "y":50},
            "size":{
              "width":320,
              "height":480}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"77be0b67ef3c42f48ab2c771e1017b79",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":100,
                  "y":50},
                "size":{
                  "width":320,
                  "height":480}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/我的问药/u0.png"}},
{
          "id":"149a16632fc4422a9bb4cba3de3e2522",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":101,
              "y":314},
            "size":{
              "width":318,
              "height":216},
            "borderWidth":"-1",
            "borderFill":{
              "fillType":"solid",
              "color":0xFF000000}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"8c40f77cc0bf47569c57da9ee82067b8",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":101,
                  "y":314},
                "size":{
                  "width":318,
                  "height":216},
                "borderWidth":"-1",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF000000}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/添加用药/u132.png"}},
{
          "id":"a5c6493603294482a50322bcd34c95b6",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":100,
              "y":70},
            "size":{
              "width":320,
              "height":40}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"b8862969844b4a65bde6e34b73cd43c7",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":100,
                  "y":70},
                "size":{
                  "width":320,
                  "height":40}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/药店详情/u2.png"}},
{
          "id":"a2b7324a212341208365a1701a78c70c",
          "label":"top",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":100,
              "y":50},
            "size":{
              "width":320,
              "height":20},
            "rotation":"0",
            "textRotation":"0",
            "borderWidth":"0",
            "cornerRadiusTopLeft":"0"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"94deaa577f084e52b4f7d701e24c366c",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":100,
                  "y":50},
                "size":{
                  "width":320,
                  "height":20},
                "rotation":"0",
                "textRotation":"0",
                "borderWidth":"0",
                "cornerRadiusTopLeft":"0"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/我的问药/top_u2.png"}},
{
          "id":"fb3d80ada7d6411aa802fef342ad543a",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontSize":"12px",
            "location":{
              "x":116,
              "y":146},
            "size":{
              "width":40,
              "height":20},
            "borderFill":{
              "fillType":"solid",
              "color":0xFF999999}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"43b241c89a7248bfb201f20b38ad310d",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"12px",
                "location":{
                  "x":116,
                  "y":146},
                "size":{
                  "width":40,
                  "height":20},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF999999}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/搜索用药/u12.png"}},
{
          "id":"44f0fe500d424b9c95c1f019cd3ec6ea",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontSize":"12px",
            "location":{
              "x":160,
              "y":146},
            "size":{
              "width":40,
              "height":20},
            "borderFill":{
              "fillType":"solid",
              "color":0xFF999999}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"ece49ccbcd1f4307be4f7c0b1ba7b62a",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"12px",
                "location":{
                  "x":160,
                  "y":146},
                "size":{
                  "width":40,
                  "height":20},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF999999}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/搜索用药/u12.png"}},
{
          "id":"ec9018dbb8ed41d593f28619d72b8dd3",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":108,
              "y":80},
            "size":{
              "width":22,
              "height":22},
            "borderWidth":"-1",
            "borderFill":{
              "fillType":"solid",
              "color":0xFF000000}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"c8fc2380bce941ba971f409384fa6cb1",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":108,
                  "y":80},
                "size":{
                  "width":22,
                  "height":22},
                "borderWidth":"-1",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF000000}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/咨询药店/u25.png"}},
{
          "id":"b65c99b8d382450f8e257d324bc3dffc",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontSize":"12px",
            "location":{
              "x":204,
              "y":146},
            "size":{
              "width":54,
              "height":20},
            "borderFill":{
              "fillType":"solid",
              "color":0xFF999999}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"6ac8dbe3c87f4e31b69bfaa6180ce3af",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"12px",
                "location":{
                  "x":204,
                  "y":146},
                "size":{
                  "width":54,
                  "height":20},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF999999}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/搜索用药/u18.png"}},
{
          "id":"d543ce263d304f1f8409e97cdef771f2",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "horizontalAlignment":"left",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFCCCCCC,
              "opacity":1},
            "location":{
              "x":130,
              "y":76},
            "size":{
              "width":280,
              "height":30},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFCCCCCC}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"f9a5a7fdb076444589d1c5b326188a0b",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "horizontalAlignment":"left",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC,
                  "opacity":1},
                "location":{
                  "x":130,
                  "y":76},
                "size":{
                  "width":280,
                  "height":30},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/搜索用药/u20.png"}},
{
          "id":"b966560e2304480c823349554c73a81e",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":140,
              "y":80},
            "size":{
              "width":20,
              "height":20},
            "borderWidth":"-1",
            "borderFill":{
              "fillType":"solid",
              "color":0xFF000000}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"7726384a6dc0464883011c9a4107d8a6",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":140,
                  "y":80},
                "size":{
                  "width":20,
                  "height":20},
                "borderWidth":"-1",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF000000}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/我的问药/u20.png"}},
{
          "id":"939f7de5dfec493e9e832bf2981b52ba",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF666666,
              "opacity":1},
            "location":{
              "x":116,
              "y":120},
            "size":{
              "width":79,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"875314294f4f4f2bac214dd1d1ccfcfc",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF666666,
                  "opacity":1},
                "location":{
                  "x":116,
                  "y":120},
                "size":{
                  "width":79,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"f98a2a2c69ae4c8f80354bfa12398b7f",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":500,
              "y":50},
            "size":{
              "width":320,
              "height":480}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"e656e609bb4e44c0aaeed42a15920891",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":500,
                  "y":50},
                "size":{
                  "width":320,
                  "height":480}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/我的问药/u0.png"}},
{
          "id":"1dbe0c1c25f8477b8e5ce8457cea8645",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":500,
              "y":70},
            "size":{
              "width":320,
              "height":40}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"fc11bd8498c04fdd8caef6172bce4141",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":500,
                  "y":70},
                "size":{
                  "width":320,
                  "height":40}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/药店详情/u2.png"}},
{
          "id":"bf888d8160b445e8bc61fd55fb02c846",
          "label":"top",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":500,
              "y":50},
            "size":{
              "width":320,
              "height":20},
            "rotation":"0",
            "textRotation":"0",
            "borderWidth":"0",
            "cornerRadiusTopLeft":"0"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"789276c05e9747c3955e60c75c929fb8",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":500,
                  "y":50},
                "size":{
                  "width":320,
                  "height":20},
                "rotation":"0",
                "textRotation":"0",
                "borderWidth":"0",
                "cornerRadiusTopLeft":"0"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/我的问药/top_u2.png"}},
{
          "id":"173b33454d944fc69ca8d724b1d90fa0",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":508,
              "y":80},
            "size":{
              "width":22,
              "height":22},
            "borderWidth":"-1",
            "borderFill":{
              "fillType":"solid",
              "color":0xFF000000}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"9ee81b7c29ae4da2a1c65cff2c353494",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":508,
                  "y":80},
                "size":{
                  "width":22,
                  "height":22},
                "borderWidth":"-1",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF000000}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/咨询药店/u25.png"}},
{
          "id":"01235bbfa1844902be01ee31b132a180",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "fontName":"'Arial Normal', 'Arial'",
            "fontSize":"16px",
            "fontWeight":"400",
            "location":{
              "x":534,
              "y":82},
            "size":{
              "width":33,
              "height":19}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"0a082181cafe497aa22c5270300a412c",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Normal', 'Arial'",
                "fontSize":"16px",
                "fontWeight":"400",
                "location":{
                  "x":534,
                  "y":82},
                "size":{
                  "width":33,
                  "height":19}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"ba96b7e30adb4a9c98db339b14764c8d",
          "label":"",
          "type":"verticalLine",
          "styleType":"verticalLine",
          "visible":true,
          "style":{
            "location":{
              "x":159,
              "y":82},
            "size":{
              "width":10,
              "height":20},
            "borderFill":{
              "fillType":"solid",
              "color":0xFF666666}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/搜索用药/u36_line.png"}},
{
          "id":"70ac51766e634ff0be3137b1465de774",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":900,
              "y":70},
            "size":{
              "width":320,
              "height":40}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"03607896538d4fd98de58e64e06927a0",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":900,
                  "y":70},
                "size":{
                  "width":320,
                  "height":40}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/药店详情/u2.png"}},
{
          "id":"d245623096cb47bea03f9ee6b57db391",
          "label":"top",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":900,
              "y":50},
            "size":{
              "width":320,
              "height":20},
            "rotation":"0",
            "textRotation":"0",
            "borderWidth":"0",
            "cornerRadiusTopLeft":"0"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"d689a9a434924d38b4f7e99402e7f1e4",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":900,
                  "y":50},
                "size":{
                  "width":320,
                  "height":20},
                "rotation":"0",
                "textRotation":"0",
                "borderWidth":"0",
                "cornerRadiusTopLeft":"0"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/我的问药/top_u2.png"}},
{
          "id":"6b704eb4254b462d8041e445d75e15e5",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":908,
              "y":80},
            "size":{
              "width":22,
              "height":22},
            "borderWidth":"-1",
            "borderFill":{
              "fillType":"solid",
              "color":0xFF000000}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"2e3b961358674f448f51fdd95fbbd709",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":908,
                  "y":80},
                "size":{
                  "width":22,
                  "height":22},
                "borderWidth":"-1",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF000000}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/咨询药店/u25.png"}},
{
          "id":"1fd7adfc8a464280b8e153d9a1cb8a14",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "horizontalAlignment":"left",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFCCCCCC,
              "opacity":1},
            "location":{
              "x":930,
              "y":76},
            "size":{
              "width":280,
              "height":30},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFCCCCCC}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"8a79261a747640ef9872a02a150b4891",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "horizontalAlignment":"left",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC,
                  "opacity":1},
                "location":{
                  "x":930,
                  "y":76},
                "size":{
                  "width":280,
                  "height":30},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/搜索用药/u20.png"}},
{
          "id":"743dea0b909846f7b7e0fc2d4dc04362",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":940,
              "y":80},
            "size":{
              "width":20,
              "height":20},
            "borderWidth":"-1",
            "borderFill":{
              "fillType":"solid",
              "color":0xFF000000}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"82c609456213498b970ffea43950844f",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":940,
                  "y":80},
                "size":{
                  "width":20,
                  "height":20},
                "borderWidth":"-1",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF000000}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/我的问药/u20.png"}},
{
          "id":"378aa906747a4d9ba2c2909b025b125a",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF000000,
              "opacity":1},
            "location":{
              "x":966,
              "y":84},
            "size":{
              "width":14,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"1d38d3bbd0f74b698d5a1a454d4e5072",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF000000,
                  "opacity":1},
                "location":{
                  "x":966,
                  "y":84},
                "size":{
                  "width":14,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"8a9313b3f4e547daa8a4c842157e0f0e",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontSize":"16px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF666666,
              "opacity":1},
            "location":{
              "x":1187,
              "y":78},
            "size":{
              "width":20,
              "height":25},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"729ffac4fe4645409c6eaa45adaceeaf",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"16px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF666666,
                  "opacity":1},
                "location":{
                  "x":1187,
                  "y":78},
                "size":{
                  "width":20,
                  "height":25},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/添加用药/u128.png"}},
{
          "id":"7dad51e0cbed4e249262fdfa9c8a8b58",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "fontName":"'Arial Normal', 'Arial'",
            "fontSize":"16px",
            "fontWeight":"400",
            "location":{
              "x":100,
              "y":22},
            "size":{
              "width":97,
              "height":19}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"19afbcc52ae9488188e80ce63de128c3",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Normal', 'Arial'",
                "fontSize":"16px",
                "fontWeight":"400",
                "location":{
                  "x":100,
                  "y":22},
                "size":{
                  "width":97,
                  "height":19}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"d59c6b49d14c461f9256f43bb1b7d64d",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "fontName":"'Arial Normal', 'Arial'",
            "fontSize":"16px",
            "fontWeight":"400",
            "location":{
              "x":500,
              "y":22},
            "size":{
              "width":65,
              "height":19}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"e8f68e25c6e54de3bf250cf42b218bcc",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Normal', 'Arial'",
                "fontSize":"16px",
                "fontWeight":"400",
                "location":{
                  "x":500,
                  "y":22},
                "size":{
                  "width":65,
                  "height":19}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"cea140a1a72444efa28ae126f8155f57",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "fontName":"'Arial Normal', 'Arial'",
            "fontSize":"16px",
            "fontWeight":"400",
            "location":{
              "x":900,
              "y":22},
            "size":{
              "width":97,
              "height":19}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"5a659fb33e96497a93a7eeb4ba0cd26f",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Normal', 'Arial'",
                "fontSize":"16px",
                "fontWeight":"400",
                "location":{
                  "x":900,
                  "y":22},
                "size":{
                  "width":97,
                  "height":19}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"e0114d458d684b5792d5917116976ec1",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "fontName":"'Arial Normal', 'Arial'",
            "fontSize":"15px",
            "fontWeight":"400",
            "location":{
              "x":580,
              "y":122},
            "size":{
              "width":100,
              "height":17}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"cb764578d35f43fd8d77def4ab77ce4e",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Normal', 'Arial'",
                "fontSize":"15px",
                "fontWeight":"400",
                "location":{
                  "x":580,
                  "y":122},
                "size":{
                  "width":100,
                  "height":17}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"7e2f743f973d4b3db074d6f6435567a2",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "fontName":"'Arial Normal', 'Arial'",
            "fontSize":"12px",
            "fontWeight":"400",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF666666,
              "opacity":1},
            "location":{
              "x":745,
              "y":122},
            "size":{
              "width":65,
              "height":15}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"a0d0f0a0e7184b0cbc656583fd3b42f8",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Normal', 'Arial'",
                "fontSize":"12px",
                "fontWeight":"400",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF666666,
                  "opacity":1},
                "location":{
                  "x":745,
                  "y":122},
                "size":{
                  "width":65,
                  "height":15}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"dde1958f082645dd8adf6c3db842b2ab",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontSize":"12px",
            "location":{
              "x":514,
              "y":198},
            "size":{
              "width":40,
              "height":20},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFCCCCCC}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"405d49decba94d3ba26af086e729e365",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"12px",
                "location":{
                  "x":514,
                  "y":198},
                "size":{
                  "width":40,
                  "height":20},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/添加用药/u265.png"}},
{
          "id":"b893ce0300c542e18716d5c07990abf4",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontSize":"12px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF00CC00,
              "opacity":1},
            "location":{
              "x":558,
              "y":198},
            "size":{
              "width":40,
              "height":20},
            "borderFill":{
              "fillType":"solid",
              "color":0xFF00CC00}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"24d2cf6cb8d54eb2969bf544b40a1565",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"12px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF00CC00,
                  "opacity":1},
                "location":{
                  "x":558,
                  "y":198},
                "size":{
                  "width":40,
                  "height":20},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF00CC00}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/搜索用药/u63.png"}},
{
          "id":"a56b73c80e1648c89bddb3501f8b0734",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":500,
              "y":228},
            "size":{
              "width":320,
              "height":10},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFCCCCCC}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/我的问药/u44_line.png"}},
{
          "id":"03b2ca5ce0014efbaa66c8227565cef4",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF999999,
              "opacity":1},
            "location":{
              "x":510,
              "y":122},
            "size":{
              "width":50,
              "height":50}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"09183de6ab8a41bbb9fd44bb4fde5b51",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF999999,
                  "opacity":1},
                "location":{
                  "x":510,
                  "y":122},
                "size":{
                  "width":50,
                  "height":50}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/添加用药/u274.png"}},
{
          "id":"624d7534cabd451b906046803f85a826",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontSize":"10px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF666666,
              "opacity":1},
            "location":{
              "x":580,
              "y":148},
            "size":{
              "width":35,
              "height":20},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFCCCCCC}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"bbf751d174454693853316b932e59ce6",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"10px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF666666,
                  "opacity":1},
                "location":{
                  "x":580,
                  "y":148},
                "size":{
                  "width":35,
                  "height":20},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/搜索用药/u68.png"}},
{
          "id":"df209574b49541018c723e0119f53569",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontSize":"10px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF666666,
              "opacity":1},
            "location":{
              "x":618,
              "y":148},
            "size":{
              "width":35,
              "height":20},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFCCCCCC}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"771ffb6b0edd47678992cfd59c967e01",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"10px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF666666,
                  "opacity":1},
                "location":{
                  "x":618,
                  "y":148},
                "size":{
                  "width":35,
                  "height":20},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/搜索用药/u68.png"}},
{
          "id":"ecd68acc6a91471785566e44cd588da9",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "fontName":"'Arial Normal', 'Arial'",
            "fontSize":"12px",
            "fontWeight":"400",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF666666,
              "opacity":1},
            "location":{
              "x":515,
              "y":178},
            "size":{
              "width":190,
              "height":15}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"bc2c1e5a280e425e883a2369b53e8e0d",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Normal', 'Arial'",
                "fontSize":"12px",
                "fontWeight":"400",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF666666,
                  "opacity":1},
                "location":{
                  "x":515,
                  "y":178},
                "size":{
                  "width":190,
                  "height":15}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"ea63591cd2844cd99917b7374dd9ba63",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "fontName":"'Arial Normal', 'Arial'",
            "fontSize":"15px",
            "fontWeight":"400",
            "location":{
              "x":580,
              "y":246},
            "size":{
              "width":100,
              "height":17}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"ed6e822f56b94e64b9d5d1872ae955ac",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Normal', 'Arial'",
                "fontSize":"15px",
                "fontWeight":"400",
                "location":{
                  "x":580,
                  "y":246},
                "size":{
                  "width":100,
                  "height":17}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"d0054c8fa21c4a1ea9e6eebbda9536d7",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "fontName":"'Arial Normal', 'Arial'",
            "fontSize":"12px",
            "fontWeight":"400",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF666666,
              "opacity":1},
            "location":{
              "x":745,
              "y":246},
            "size":{
              "width":65,
              "height":15}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"9fede28068574911b859515810a27101",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Normal', 'Arial'",
                "fontSize":"12px",
                "fontWeight":"400",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF666666,
                  "opacity":1},
                "location":{
                  "x":745,
                  "y":246},
                "size":{
                  "width":65,
                  "height":15}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"26b0f5b1e415417483da7669913dab06",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontSize":"12px",
            "location":{
              "x":514,
              "y":324},
            "size":{
              "width":40,
              "height":20},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFCCCCCC}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"67a120c466d1478c88e978f127cd1a8c",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"12px",
                "location":{
                  "x":514,
                  "y":324},
                "size":{
                  "width":40,
                  "height":20},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/添加用药/u265.png"}},
{
          "id":"8e78193902524a31b744462ac2bdb1cc",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontSize":"12px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF00CC00,
              "opacity":1},
            "location":{
              "x":558,
              "y":324},
            "size":{
              "width":40,
              "height":20},
            "borderFill":{
              "fillType":"solid",
              "color":0xFF00CC00}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"93234a0162d5427eb3703452d5fa74c9",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"12px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF00CC00,
                  "opacity":1},
                "location":{
                  "x":558,
                  "y":324},
                "size":{
                  "width":40,
                  "height":20},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF00CC00}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/搜索用药/u63.png"}},
{
          "id":"fad4697e6c1d45209d245b03968c1f09",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF999999,
              "opacity":1},
            "location":{
              "x":510,
              "y":248},
            "size":{
              "width":50,
              "height":50}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"c3b81bb2a28b420db509d055edcce912",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF999999,
                  "opacity":1},
                "location":{
                  "x":510,
                  "y":248},
                "size":{
                  "width":50,
                  "height":50}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/添加用药/u274.png"}},
{
          "id":"743bda6cc03e4a64820504949cc01536",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontSize":"10px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF666666,
              "opacity":1},
            "location":{
              "x":580,
              "y":274},
            "size":{
              "width":35,
              "height":20},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFCCCCCC}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"f1d7e59c3423400aa8d62bfa037f60f9",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"10px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF666666,
                  "opacity":1},
                "location":{
                  "x":580,
                  "y":274},
                "size":{
                  "width":35,
                  "height":20},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/搜索用药/u68.png"}},
{
          "id":"31f440c06042468f8f037f14ca7d75a8",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontSize":"10px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF666666,
              "opacity":1},
            "location":{
              "x":618,
              "y":274},
            "size":{
              "width":35,
              "height":20},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFCCCCCC}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"af9229849bbc4f1096fa7479b78d3680",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"10px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF666666,
                  "opacity":1},
                "location":{
                  "x":618,
                  "y":274},
                "size":{
                  "width":35,
                  "height":20},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/搜索用药/u68.png"}},
{
          "id":"386bbf0c23b94606be0d169b643561b1",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "fontName":"'Arial Normal', 'Arial'",
            "fontSize":"12px",
            "fontWeight":"400",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF666666,
              "opacity":1},
            "location":{
              "x":515,
              "y":304},
            "size":{
              "width":190,
              "height":15}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"1219c84b95644c8caf5469d747931be0",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Normal', 'Arial'",
                "fontSize":"12px",
                "fontWeight":"400",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF666666,
                  "opacity":1},
                "location":{
                  "x":515,
                  "y":304},
                "size":{
                  "width":190,
                  "height":15}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"fc8ce6a928b14285b55213d6f625a62f",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "fontName":"'Arial Normal', 'Arial'",
            "fontSize":"15px",
            "fontWeight":"400",
            "location":{
              "x":980,
              "y":122},
            "size":{
              "width":151,
              "height":17}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"e1262825aa23423083be163e699124ac",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Normal', 'Arial'",
                "fontSize":"15px",
                "fontWeight":"400",
                "location":{
                  "x":980,
                  "y":122},
                "size":{
                  "width":151,
                  "height":17}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"11f6c93838c6487db28fdb8e048085ea",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "fontName":"'Arial Normal', 'Arial'",
            "fontSize":"12px",
            "fontWeight":"400",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF666666,
              "opacity":1},
            "location":{
              "x":1145,
              "y":122},
            "size":{
              "width":65,
              "height":15}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"f27e437de60e4e05845d713d32297c17",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Normal', 'Arial'",
                "fontSize":"12px",
                "fontWeight":"400",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF666666,
                  "opacity":1},
                "location":{
                  "x":1145,
                  "y":122},
                "size":{
                  "width":65,
                  "height":15}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"94ed3973e6d9407fb73236c111406c59",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontSize":"12px",
            "location":{
              "x":914,
              "y":200},
            "size":{
              "width":40,
              "height":20},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFCCCCCC}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"e83591985d344462bc30dd93e61699ff",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"12px",
                "location":{
                  "x":914,
                  "y":200},
                "size":{
                  "width":40,
                  "height":20},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/添加用药/u265.png"}},
{
          "id":"7b4cf331a05244f0ae7da4683698a8d7",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontSize":"12px",
            "location":{
              "x":958,
              "y":200},
            "size":{
              "width":40,
              "height":20},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFCCCCCC}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"5cbd7f64df784d5ca5a92e3c8bcc6fe0",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"12px",
                "location":{
                  "x":958,
                  "y":200},
                "size":{
                  "width":40,
                  "height":20},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/添加用药/u265.png"}},
{
          "id":"68cdbed80a5d453ea93588ade1706b65",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF999999,
              "opacity":1},
            "location":{
              "x":910,
              "y":124},
            "size":{
              "width":50,
              "height":50}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"123cd71dd2244500a1b850b1e2aa5523",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF999999,
                  "opacity":1},
                "location":{
                  "x":910,
                  "y":124},
                "size":{
                  "width":50,
                  "height":50}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/添加用药/u274.png"}},
{
          "id":"87a4313b195e4083a84c647e3ea6fd27",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontSize":"10px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF666666,
              "opacity":1},
            "location":{
              "x":980,
              "y":150},
            "size":{
              "width":35,
              "height":20},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFCCCCCC}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"9cedf5ca401545d08b716b08854e17fa",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"10px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF666666,
                  "opacity":1},
                "location":{
                  "x":980,
                  "y":150},
                "size":{
                  "width":35,
                  "height":20},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/搜索用药/u68.png"}},
{
          "id":"ff968916395d4b46bcec7091b7360539",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontSize":"10px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF666666,
              "opacity":1},
            "location":{
              "x":1018,
              "y":150},
            "size":{
              "width":35,
              "height":20},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFCCCCCC}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"8abc16a6214d4092a546f1f3bd9a93ae",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"10px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF666666,
                  "opacity":1},
                "location":{
                  "x":1018,
                  "y":150},
                "size":{
                  "width":35,
                  "height":20},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/搜索用药/u68.png"}},
{
          "id":"cf08b8eb95db4220868a79ab78e1f92b",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "fontName":"'Arial Normal', 'Arial'",
            "fontSize":"12px",
            "fontWeight":"400",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF666666,
              "opacity":1},
            "location":{
              "x":915,
              "y":180},
            "size":{
              "width":190,
              "height":15}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"fc52514e405d489abe74adbd9c28cb53",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Normal', 'Arial'",
                "fontSize":"12px",
                "fontWeight":"400",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF666666,
                  "opacity":1},
                "location":{
                  "x":915,
                  "y":180},
                "size":{
                  "width":190,
                  "height":15}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"95350092b327481399dd61a437fe95d5",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":500,
              "y":350},
            "size":{
              "width":320,
              "height":10},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFCCCCCC}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/我的问药/u44_line.png"}},
{
          "id":"04a2238aedbc425a98ac5432f9f59f0d",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":900,
              "y":226},
            "size":{
              "width":320,
              "height":10},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFCCCCCC}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/我的问药/u44_line.png"}}]}},
  "masters":{
},
  "objectPaths":{
    "f28470037ee741f68955c85e9543f640":{
      "scriptId":"u0"},
    "535af4cb6a7f424ca0e843071cf20dcc":{
      "scriptId":"u1"},
    "a8e5f643eec04c94b402bbe6e920cce1":{
      "scriptId":"u2"},
    "83f642d7debe46e68adfbe8e1b1fdf23":{
      "scriptId":"u3"},
    "623d87b5ede44ff8b8c0cc28df53f576":{
      "scriptId":"u4"},
    "77be0b67ef3c42f48ab2c771e1017b79":{
      "scriptId":"u5"},
    "149a16632fc4422a9bb4cba3de3e2522":{
      "scriptId":"u6"},
    "8c40f77cc0bf47569c57da9ee82067b8":{
      "scriptId":"u7"},
    "a5c6493603294482a50322bcd34c95b6":{
      "scriptId":"u8"},
    "b8862969844b4a65bde6e34b73cd43c7":{
      "scriptId":"u9"},
    "a2b7324a212341208365a1701a78c70c":{
      "scriptId":"u10"},
    "94deaa577f084e52b4f7d701e24c366c":{
      "scriptId":"u11"},
    "fb3d80ada7d6411aa802fef342ad543a":{
      "scriptId":"u12"},
    "43b241c89a7248bfb201f20b38ad310d":{
      "scriptId":"u13"},
    "44f0fe500d424b9c95c1f019cd3ec6ea":{
      "scriptId":"u14"},
    "ece49ccbcd1f4307be4f7c0b1ba7b62a":{
      "scriptId":"u15"},
    "ec9018dbb8ed41d593f28619d72b8dd3":{
      "scriptId":"u16"},
    "c8fc2380bce941ba971f409384fa6cb1":{
      "scriptId":"u17"},
    "b65c99b8d382450f8e257d324bc3dffc":{
      "scriptId":"u18"},
    "6ac8dbe3c87f4e31b69bfaa6180ce3af":{
      "scriptId":"u19"},
    "d543ce263d304f1f8409e97cdef771f2":{
      "scriptId":"u20"},
    "f9a5a7fdb076444589d1c5b326188a0b":{
      "scriptId":"u21"},
    "b966560e2304480c823349554c73a81e":{
      "scriptId":"u22"},
    "7726384a6dc0464883011c9a4107d8a6":{
      "scriptId":"u23"},
    "939f7de5dfec493e9e832bf2981b52ba":{
      "scriptId":"u24"},
    "875314294f4f4f2bac214dd1d1ccfcfc":{
      "scriptId":"u25"},
    "f98a2a2c69ae4c8f80354bfa12398b7f":{
      "scriptId":"u26"},
    "e656e609bb4e44c0aaeed42a15920891":{
      "scriptId":"u27"},
    "1dbe0c1c25f8477b8e5ce8457cea8645":{
      "scriptId":"u28"},
    "fc11bd8498c04fdd8caef6172bce4141":{
      "scriptId":"u29"},
    "bf888d8160b445e8bc61fd55fb02c846":{
      "scriptId":"u30"},
    "789276c05e9747c3955e60c75c929fb8":{
      "scriptId":"u31"},
    "173b33454d944fc69ca8d724b1d90fa0":{
      "scriptId":"u32"},
    "9ee81b7c29ae4da2a1c65cff2c353494":{
      "scriptId":"u33"},
    "01235bbfa1844902be01ee31b132a180":{
      "scriptId":"u34"},
    "0a082181cafe497aa22c5270300a412c":{
      "scriptId":"u35"},
    "ba96b7e30adb4a9c98db339b14764c8d":{
      "scriptId":"u36"},
    "70ac51766e634ff0be3137b1465de774":{
      "scriptId":"u37"},
    "03607896538d4fd98de58e64e06927a0":{
      "scriptId":"u38"},
    "d245623096cb47bea03f9ee6b57db391":{
      "scriptId":"u39"},
    "d689a9a434924d38b4f7e99402e7f1e4":{
      "scriptId":"u40"},
    "6b704eb4254b462d8041e445d75e15e5":{
      "scriptId":"u41"},
    "2e3b961358674f448f51fdd95fbbd709":{
      "scriptId":"u42"},
    "1fd7adfc8a464280b8e153d9a1cb8a14":{
      "scriptId":"u43"},
    "8a79261a747640ef9872a02a150b4891":{
      "scriptId":"u44"},
    "743dea0b909846f7b7e0fc2d4dc04362":{
      "scriptId":"u45"},
    "82c609456213498b970ffea43950844f":{
      "scriptId":"u46"},
    "378aa906747a4d9ba2c2909b025b125a":{
      "scriptId":"u47"},
    "1d38d3bbd0f74b698d5a1a454d4e5072":{
      "scriptId":"u48"},
    "8a9313b3f4e547daa8a4c842157e0f0e":{
      "scriptId":"u49"},
    "729ffac4fe4645409c6eaa45adaceeaf":{
      "scriptId":"u50"},
    "7dad51e0cbed4e249262fdfa9c8a8b58":{
      "scriptId":"u51"},
    "19afbcc52ae9488188e80ce63de128c3":{
      "scriptId":"u52"},
    "d59c6b49d14c461f9256f43bb1b7d64d":{
      "scriptId":"u53"},
    "e8f68e25c6e54de3bf250cf42b218bcc":{
      "scriptId":"u54"},
    "cea140a1a72444efa28ae126f8155f57":{
      "scriptId":"u55"},
    "5a659fb33e96497a93a7eeb4ba0cd26f":{
      "scriptId":"u56"},
    "e0114d458d684b5792d5917116976ec1":{
      "scriptId":"u57"},
    "cb764578d35f43fd8d77def4ab77ce4e":{
      "scriptId":"u58"},
    "7e2f743f973d4b3db074d6f6435567a2":{
      "scriptId":"u59"},
    "a0d0f0a0e7184b0cbc656583fd3b42f8":{
      "scriptId":"u60"},
    "dde1958f082645dd8adf6c3db842b2ab":{
      "scriptId":"u61"},
    "405d49decba94d3ba26af086e729e365":{
      "scriptId":"u62"},
    "b893ce0300c542e18716d5c07990abf4":{
      "scriptId":"u63"},
    "24d2cf6cb8d54eb2969bf544b40a1565":{
      "scriptId":"u64"},
    "a56b73c80e1648c89bddb3501f8b0734":{
      "scriptId":"u65"},
    "03b2ca5ce0014efbaa66c8227565cef4":{
      "scriptId":"u66"},
    "09183de6ab8a41bbb9fd44bb4fde5b51":{
      "scriptId":"u67"},
    "624d7534cabd451b906046803f85a826":{
      "scriptId":"u68"},
    "bbf751d174454693853316b932e59ce6":{
      "scriptId":"u69"},
    "df209574b49541018c723e0119f53569":{
      "scriptId":"u70"},
    "771ffb6b0edd47678992cfd59c967e01":{
      "scriptId":"u71"},
    "ecd68acc6a91471785566e44cd588da9":{
      "scriptId":"u72"},
    "bc2c1e5a280e425e883a2369b53e8e0d":{
      "scriptId":"u73"},
    "ea63591cd2844cd99917b7374dd9ba63":{
      "scriptId":"u74"},
    "ed6e822f56b94e64b9d5d1872ae955ac":{
      "scriptId":"u75"},
    "d0054c8fa21c4a1ea9e6eebbda9536d7":{
      "scriptId":"u76"},
    "9fede28068574911b859515810a27101":{
      "scriptId":"u77"},
    "26b0f5b1e415417483da7669913dab06":{
      "scriptId":"u78"},
    "67a120c466d1478c88e978f127cd1a8c":{
      "scriptId":"u79"},
    "8e78193902524a31b744462ac2bdb1cc":{
      "scriptId":"u80"},
    "93234a0162d5427eb3703452d5fa74c9":{
      "scriptId":"u81"},
    "fad4697e6c1d45209d245b03968c1f09":{
      "scriptId":"u82"},
    "c3b81bb2a28b420db509d055edcce912":{
      "scriptId":"u83"},
    "743bda6cc03e4a64820504949cc01536":{
      "scriptId":"u84"},
    "f1d7e59c3423400aa8d62bfa037f60f9":{
      "scriptId":"u85"},
    "31f440c06042468f8f037f14ca7d75a8":{
      "scriptId":"u86"},
    "af9229849bbc4f1096fa7479b78d3680":{
      "scriptId":"u87"},
    "386bbf0c23b94606be0d169b643561b1":{
      "scriptId":"u88"},
    "1219c84b95644c8caf5469d747931be0":{
      "scriptId":"u89"},
    "fc8ce6a928b14285b55213d6f625a62f":{
      "scriptId":"u90"},
    "e1262825aa23423083be163e699124ac":{
      "scriptId":"u91"},
    "11f6c93838c6487db28fdb8e048085ea":{
      "scriptId":"u92"},
    "f27e437de60e4e05845d713d32297c17":{
      "scriptId":"u93"},
    "94ed3973e6d9407fb73236c111406c59":{
      "scriptId":"u94"},
    "e83591985d344462bc30dd93e61699ff":{
      "scriptId":"u95"},
    "7b4cf331a05244f0ae7da4683698a8d7":{
      "scriptId":"u96"},
    "5cbd7f64df784d5ca5a92e3c8bcc6fe0":{
      "scriptId":"u97"},
    "68cdbed80a5d453ea93588ade1706b65":{
      "scriptId":"u98"},
    "123cd71dd2244500a1b850b1e2aa5523":{
      "scriptId":"u99"},
    "87a4313b195e4083a84c647e3ea6fd27":{
      "scriptId":"u100"},
    "9cedf5ca401545d08b716b08854e17fa":{
      "scriptId":"u101"},
    "ff968916395d4b46bcec7091b7360539":{
      "scriptId":"u102"},
    "8abc16a6214d4092a546f1f3bd9a93ae":{
      "scriptId":"u103"},
    "cf08b8eb95db4220868a79ab78e1f92b":{
      "scriptId":"u104"},
    "fc52514e405d489abe74adbd9c28cb53":{
      "scriptId":"u105"},
    "95350092b327481399dd61a437fe95d5":{
      "scriptId":"u106"},
    "04a2238aedbc425a98ac5432f9f59f0d":{
      "scriptId":"u107"}}});