$axure.loadCurrentPage({
  "url":"健康指标.html",
  "generationDate":new Date(1409493104054.81),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"c3378449daf84a77b8dd337127705cb5",
    "type":"Axure:Page",
    "name":"健康指标",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"应用字体",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"dc2bb3889da04277a97ea932f77e6ae9",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":100,
              "y":50},
            "size":{
              "width":320,
              "height":480}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"7cd4c30e1e58452681d04dde8fe08334",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":100,
                  "y":50},
                "size":{
                  "width":320,
                  "height":480}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/我的问药/u0.png"}},
{
          "id":"b6eb4c39415f43f1a7653071e5527c60",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":100,
              "y":70},
            "size":{
              "width":320,
              "height":40}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"999f4c8adec147ce86fd0de45c7f6161",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":100,
                  "y":70},
                "size":{
                  "width":320,
                  "height":40}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/药店详情/u2.png"}},
{
          "id":"437e006564094761b98bc217f2e96fa2",
          "label":"top",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":100,
              "y":50},
            "size":{
              "width":320,
              "height":20},
            "rotation":"0",
            "textRotation":"0",
            "borderWidth":"0",
            "cornerRadiusTopLeft":"0"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"bcf33ae728ad4cca95e5e5559690b0ec",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":100,
                  "y":50},
                "size":{
                  "width":320,
                  "height":20},
                "rotation":"0",
                "textRotation":"0",
                "borderWidth":"0",
                "cornerRadiusTopLeft":"0"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/我的问药/top_u2.png"}},
{
          "id":"b102997874a34ce990cbe53b74cee4e5",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":108,
              "y":80},
            "size":{
              "width":22,
              "height":22},
            "borderWidth":"-1",
            "borderFill":{
              "fillType":"solid",
              "color":0xFF000000}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"70dc60c9c8b24768a90e54020bad350e",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":108,
                  "y":80},
                "size":{
                  "width":22,
                  "height":22},
                "borderWidth":"-1",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF000000}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/咨询药店/u25.png"}},
{
          "id":"23ced663be18460ba92ee052aa0eb367",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "fontName":"'Arial Normal', 'Arial'",
            "fontSize":"16px",
            "fontWeight":"400",
            "location":{
              "x":134,
              "y":82},
            "size":{
              "width":65,
              "height":19}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"a331964afa20421290cb4c17c221ac88",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Normal', 'Arial'",
                "fontSize":"16px",
                "fontWeight":"400",
                "location":{
                  "x":134,
                  "y":82},
                "size":{
                  "width":65,
                  "height":19}},
              "adaptiveStyles":{
}}],
          "annotation":{
            "描述":"1. 血压（BP）<br>2. 血脂<br>3. 血糖（GLU）<br>4. 宝宝心智发育水平<br>5.宝宝生长指标<br>6. 肝功能<br>7. 尿常规<br>8. 体温<br>9. 体重指数<br>10. 心率<br>11. 血常规<br>12. 乙肝两对半<br>13. 血淀粉酶（AWY）<br>14. 预产期<br>15. 甲状腺<br>16. 肾功"},
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"4dc3c204fcae4e999686fc959b298d09",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":105,
              "y":156},
            "size":{
              "width":309,
              "height":10},
            "borderFill":{
              "fillType":"solid",
              "color":0xFF949494}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/健康指标/u10_line.png"}},
{
          "id":"1e58b820b1b44c0886f39c700857edb8",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":105,
              "y":205},
            "size":{
              "width":309,
              "height":10},
            "borderFill":{
              "fillType":"solid",
              "color":0xFF949494}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/健康指标/u10_line.png"}},
{
          "id":"56a771377f434c6dac668601c737caf8",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":105,
              "y":257},
            "size":{
              "width":309,
              "height":10},
            "borderFill":{
              "fillType":"solid",
              "color":0xFF949494}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/健康指标/u10_line.png"}},
{
          "id":"5f7dad34f8fc4213b034ab2b3f641284",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":105,
              "y":310},
            "size":{
              "width":309,
              "height":10},
            "borderFill":{
              "fillType":"solid",
              "color":0xFF949494}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/健康指标/u10_line.png"}},
{
          "id":"9fa40cb940344aef81adf27380e672d3",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":121,
              "y":133},
            "size":{
              "width":71,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"066991e663b84e4aa6f8c640e8c3e44b",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":121,
                  "y":133},
                "size":{
                  "width":71,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"f09d044c3b8b420ea43657d8b8bcd822",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":121,
              "y":183},
            "size":{
              "width":27,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"129d8c9b19784535ad3d67cae2204784",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":121,
                  "y":183},
                "size":{
                  "width":27,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"0c7c035fa1a244049d3c96f2cefde427",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":121,
              "y":232},
            "size":{
              "width":27,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"ec89fe7c094d4ca2b0bd9c3023d6dc9a",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":121,
                  "y":232},
                "size":{
                  "width":27,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"8e4512fa634b42098d4071405a43ef60",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":115,
              "y":284},
            "size":{
              "width":40,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"cdcf6ab8a2d7457ebf3c124983371f00",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":115,
                  "y":284},
                "size":{
                  "width":40,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"078c3cbee6c84dcd84948cdd492059ad",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":105,
              "y":362},
            "size":{
              "width":309,
              "height":10},
            "borderFill":{
              "fillType":"solid",
              "color":0xFF949494}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/健康指标/u10_line.png"}},
{
          "id":"782eedd3a3664dc2a5332128e0d77c3e",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":105,
              "y":410},
            "size":{
              "width":309,
              "height":10},
            "borderFill":{
              "fillType":"solid",
              "color":0xFF949494}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/健康指标/u10_line.png"}},
{
          "id":"b4125b9bccc446009768c04d9068edad",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":105,
              "y":460},
            "size":{
              "width":309,
              "height":10},
            "borderFill":{
              "fillType":"solid",
              "color":0xFF949494}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/健康指标/u10_line.png"}},
{
          "id":"bf41b3cf6c254dfcabeafd64e235a74d",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":115,
              "y":336},
            "size":{
              "width":40,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"b4fbeee7e5034f52be588d19740808f2",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":115,
                  "y":336},
                "size":{
                  "width":40,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"66966a417d9e46ac95f3fb158bfa9e7c",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":115,
              "y":386},
            "size":{
              "width":40,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"35a11476d12142adb1bb1af2a2359327",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":115,
                  "y":386},
                "size":{
                  "width":40,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"462c83a2e08345f3aa54b603ae109b46",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":115,
              "y":434},
            "size":{
              "width":105,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"99d7cd816e9045cf94d935339f124dd7",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":115,
                  "y":434},
                "size":{
                  "width":105,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"09c6448ad9d44b6b8e358d04908f1050",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":387,
              "y":125},
            "size":{
              "width":25,
              "height":25},
            "borderWidth":"-1",
            "borderFill":{
              "fillType":"solid",
              "color":0xFF000000}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"c14b665724c14120ad1e45d6eb7c977e",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":387,
                  "y":125},
                "size":{
                  "width":25,
                  "height":25},
                "borderWidth":"-1",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF000000}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/健康指标/u31.png"}},
{
          "id":"4cf9169040224c8f8eae3b5e38436078",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":387,
              "y":177},
            "size":{
              "width":25,
              "height":25},
            "borderWidth":"-1",
            "borderFill":{
              "fillType":"solid",
              "color":0xFF000000}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"96e3f3321f304ee7ace9c58c15ccc8f2",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":387,
                  "y":177},
                "size":{
                  "width":25,
                  "height":25},
                "borderWidth":"-1",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF000000}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/健康指标/u31.png"}},
{
          "id":"9d5a4cd954224cbe820d14300a22096a",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":387,
              "y":228},
            "size":{
              "width":25,
              "height":25},
            "borderWidth":"-1",
            "borderFill":{
              "fillType":"solid",
              "color":0xFF000000}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"316f4ab5737c44a98cf7937385471af6",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":387,
                  "y":228},
                "size":{
                  "width":25,
                  "height":25},
                "borderWidth":"-1",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF000000}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/健康指标/u31.png"}},
{
          "id":"698e5fd067044c618fd6650dcfba6abe",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":387,
              "y":281},
            "size":{
              "width":25,
              "height":25},
            "borderWidth":"-1",
            "borderFill":{
              "fillType":"solid",
              "color":0xFF000000}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"03e28251a78b4b42bd4aa9038d24431d",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":387,
                  "y":281},
                "size":{
                  "width":25,
                  "height":25},
                "borderWidth":"-1",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF000000}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/健康指标/u31.png"}},
{
          "id":"fcfbc0e122e845479858b64eb3bb2f8a",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":387,
              "y":332},
            "size":{
              "width":25,
              "height":25},
            "borderWidth":"-1",
            "borderFill":{
              "fillType":"solid",
              "color":0xFF000000}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"844b23f92b424a3f9a159944579a2190",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":387,
                  "y":332},
                "size":{
                  "width":25,
                  "height":25},
                "borderWidth":"-1",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF000000}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/健康指标/u31.png"}},
{
          "id":"83cd750102d147279a0165756dd0ab6f",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":387,
              "y":382},
            "size":{
              "width":25,
              "height":25},
            "borderWidth":"-1",
            "borderFill":{
              "fillType":"solid",
              "color":0xFF000000}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"c4c3676491a745829bda3fd77b32043b",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":387,
                  "y":382},
                "size":{
                  "width":25,
                  "height":25},
                "borderWidth":"-1",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF000000}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/健康指标/u31.png"}},
{
          "id":"3916a8a787294e5d8c9e978a9a29a104",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":387,
              "y":430},
            "size":{
              "width":25,
              "height":25},
            "borderWidth":"-1",
            "borderFill":{
              "fillType":"solid",
              "color":0xFF000000}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"64e4d22332af40879810dce1a49b9750",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":387,
                  "y":430},
                "size":{
                  "width":25,
                  "height":25},
                "borderWidth":"-1",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF000000}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/健康指标/u31.png"}},
{
          "id":"f95a3b109cd24eb9b5a924016d184693",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":105,
              "y":510},
            "size":{
              "width":309,
              "height":10},
            "borderFill":{
              "fillType":"solid",
              "color":0xFF949494}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/健康指标/u10_line.png"}},
{
          "id":"115fa31da40c4dc6be174df7e80cd694",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":115,
              "y":483},
            "size":{
              "width":53,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"3d4d3b76029f46548cd0661c85df8ec0",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":115,
                  "y":483},
                "size":{
                  "width":53,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"6c669e256bed4172ac92478578f80f21",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":387,
              "y":480},
            "size":{
              "width":25,
              "height":25},
            "borderWidth":"-1",
            "borderFill":{
              "fillType":"solid",
              "color":0xFF000000}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"93423be0c9834edfb92b94bd48f81e55",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":387,
                  "y":480},
                "size":{
                  "width":25,
                  "height":25},
                "borderWidth":"-1",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF000000}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/健康指标/u31.png"}},
{
          "id":"e078de3d7858435d861cee0cd46f959e",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":500,
              "y":50},
            "size":{
              "width":320,
              "height":480}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"f9dd3d9585a345e4a66b1fa46cf363f1",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":500,
                  "y":50},
                "size":{
                  "width":320,
                  "height":480}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/我的问药/u0.png"}},
{
          "id":"33bd983549de4629a3e35a412b20d8b0",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":500,
              "y":70},
            "size":{
              "width":320,
              "height":40}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"77045c7f95ba4d3980900283b3855af9",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":500,
                  "y":70},
                "size":{
                  "width":320,
                  "height":40}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/药店详情/u2.png"}},
{
          "id":"3b9799465e38416d8d7e5366522c2b1e",
          "label":"top",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":500,
              "y":50},
            "size":{
              "width":320,
              "height":20},
            "rotation":"0",
            "textRotation":"0",
            "borderWidth":"0",
            "cornerRadiusTopLeft":"0"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"de6febb501d94b9d95182277ad0d534b",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":500,
                  "y":50},
                "size":{
                  "width":320,
                  "height":20},
                "rotation":"0",
                "textRotation":"0",
                "borderWidth":"0",
                "cornerRadiusTopLeft":"0"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/我的问药/top_u2.png"}},
{
          "id":"a179282918a4411ebc9d71004a1f9f09",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":508,
              "y":80},
            "size":{
              "width":22,
              "height":22},
            "borderWidth":"-1",
            "borderFill":{
              "fillType":"solid",
              "color":0xFF000000}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"e20c206da71346fb8cc6db4d7e7ea81e",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":508,
                  "y":80},
                "size":{
                  "width":22,
                  "height":22},
                "borderWidth":"-1",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF000000}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/咨询药店/u25.png"}},
{
          "id":"742f8a7c1b404904a435f7e4c0e6b912",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "fontName":"'Arial Normal', 'Arial'",
            "fontSize":"16px",
            "fontWeight":"400",
            "location":{
              "x":534,
              "y":82},
            "size":{
              "width":87,
              "height":19}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"63f36d4e279d43dc805b1cdec37c6203",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Normal', 'Arial'",
                "fontSize":"16px",
                "fontWeight":"400",
                "location":{
                  "x":534,
                  "y":82},
                "size":{
                  "width":87,
                  "height":19}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"6a9fb1b290ff4bd08ac32ae985a482eb",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":507,
              "y":120},
            "size":{
              "width":163,
              "height":14}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"bfbd449b6cf64d9cbd9f4aa0241efe33",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":507,
                  "y":120},
                "size":{
                  "width":163,
                  "height":14}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"ea4d71e216794032930a9683c80dea25",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":507,
              "y":211},
            "size":{
              "width":276,
              "height":55}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"5e2f1d530f644fa180a41cf4a0f6067c",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":507,
                  "y":211},
                "size":{
                  "width":276,
                  "height":55}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"ce5e7e5140854a35ad425b8d6a3526ce",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":507,
              "y":277},
            "size":{
              "width":276,
              "height":135}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"a1f7ef74140743fd90e760def28e55d5",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":507,
                  "y":277},
                "size":{
                  "width":276,
                  "height":135}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"7450293b600b48e186b89d55aeada382",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":507,
              "y":413},
            "size":{
              "width":276,
              "height":55}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"ad0b6ed3908f41a99c09c7a77b024d3a",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":507,
                  "y":413},
                "size":{
                  "width":276,
                  "height":55}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"2f1466493eb84830acc981737f3d66ac",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFA1A1A1},
            "location":{
              "x":813,
              "y":308},
            "size":{
              "width":7,
              "height":70},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFF},
            "cornerRadiusTopLeft":"2"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"0d8d1773a33b4383b0d02b69fc8dd7df",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFA1A1A1},
                "location":{
                  "x":813,
                  "y":308},
                "size":{
                  "width":7,
                  "height":70},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFF},
                "cornerRadiusTopLeft":"2"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/健康指标/u68.png"}},
{
          "id":"ea960b388dc9469c8ac7ef046e3da1ec",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":510,
              "y":237},
            "size":{
              "width":300,
              "height":32}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"4cd4b42c9633447f91e1de358e32d40d",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":510,
                  "y":237},
                "size":{
                  "width":300,
                  "height":32}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"0f24b7f16f6848c3af21e18682d220d3",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":510,
              "y":144},
            "size":{
              "width":300,
              "height":48}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"5f92e44146f64549ad91257c1c46b5e8",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":510,
                  "y":144},
                "size":{
                  "width":300,
                  "height":48}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}}]}},
  "masters":{
},
  "objectPaths":{
    "dc2bb3889da04277a97ea932f77e6ae9":{
      "scriptId":"u0"},
    "7cd4c30e1e58452681d04dde8fe08334":{
      "scriptId":"u1"},
    "b6eb4c39415f43f1a7653071e5527c60":{
      "scriptId":"u2"},
    "999f4c8adec147ce86fd0de45c7f6161":{
      "scriptId":"u3"},
    "437e006564094761b98bc217f2e96fa2":{
      "scriptId":"u4"},
    "bcf33ae728ad4cca95e5e5559690b0ec":{
      "scriptId":"u5"},
    "b102997874a34ce990cbe53b74cee4e5":{
      "scriptId":"u6"},
    "70dc60c9c8b24768a90e54020bad350e":{
      "scriptId":"u7"},
    "23ced663be18460ba92ee052aa0eb367":{
      "scriptId":"u8"},
    "a331964afa20421290cb4c17c221ac88":{
      "scriptId":"u9"},
    "4dc3c204fcae4e999686fc959b298d09":{
      "scriptId":"u10"},
    "1e58b820b1b44c0886f39c700857edb8":{
      "scriptId":"u11"},
    "56a771377f434c6dac668601c737caf8":{
      "scriptId":"u12"},
    "5f7dad34f8fc4213b034ab2b3f641284":{
      "scriptId":"u13"},
    "9fa40cb940344aef81adf27380e672d3":{
      "scriptId":"u14"},
    "066991e663b84e4aa6f8c640e8c3e44b":{
      "scriptId":"u15"},
    "f09d044c3b8b420ea43657d8b8bcd822":{
      "scriptId":"u16"},
    "129d8c9b19784535ad3d67cae2204784":{
      "scriptId":"u17"},
    "0c7c035fa1a244049d3c96f2cefde427":{
      "scriptId":"u18"},
    "ec89fe7c094d4ca2b0bd9c3023d6dc9a":{
      "scriptId":"u19"},
    "8e4512fa634b42098d4071405a43ef60":{
      "scriptId":"u20"},
    "cdcf6ab8a2d7457ebf3c124983371f00":{
      "scriptId":"u21"},
    "078c3cbee6c84dcd84948cdd492059ad":{
      "scriptId":"u22"},
    "782eedd3a3664dc2a5332128e0d77c3e":{
      "scriptId":"u23"},
    "b4125b9bccc446009768c04d9068edad":{
      "scriptId":"u24"},
    "bf41b3cf6c254dfcabeafd64e235a74d":{
      "scriptId":"u25"},
    "b4fbeee7e5034f52be588d19740808f2":{
      "scriptId":"u26"},
    "66966a417d9e46ac95f3fb158bfa9e7c":{
      "scriptId":"u27"},
    "35a11476d12142adb1bb1af2a2359327":{
      "scriptId":"u28"},
    "462c83a2e08345f3aa54b603ae109b46":{
      "scriptId":"u29"},
    "99d7cd816e9045cf94d935339f124dd7":{
      "scriptId":"u30"},
    "09c6448ad9d44b6b8e358d04908f1050":{
      "scriptId":"u31"},
    "c14b665724c14120ad1e45d6eb7c977e":{
      "scriptId":"u32"},
    "4cf9169040224c8f8eae3b5e38436078":{
      "scriptId":"u33"},
    "96e3f3321f304ee7ace9c58c15ccc8f2":{
      "scriptId":"u34"},
    "9d5a4cd954224cbe820d14300a22096a":{
      "scriptId":"u35"},
    "316f4ab5737c44a98cf7937385471af6":{
      "scriptId":"u36"},
    "698e5fd067044c618fd6650dcfba6abe":{
      "scriptId":"u37"},
    "03e28251a78b4b42bd4aa9038d24431d":{
      "scriptId":"u38"},
    "fcfbc0e122e845479858b64eb3bb2f8a":{
      "scriptId":"u39"},
    "844b23f92b424a3f9a159944579a2190":{
      "scriptId":"u40"},
    "83cd750102d147279a0165756dd0ab6f":{
      "scriptId":"u41"},
    "c4c3676491a745829bda3fd77b32043b":{
      "scriptId":"u42"},
    "3916a8a787294e5d8c9e978a9a29a104":{
      "scriptId":"u43"},
    "64e4d22332af40879810dce1a49b9750":{
      "scriptId":"u44"},
    "f95a3b109cd24eb9b5a924016d184693":{
      "scriptId":"u45"},
    "115fa31da40c4dc6be174df7e80cd694":{
      "scriptId":"u46"},
    "3d4d3b76029f46548cd0661c85df8ec0":{
      "scriptId":"u47"},
    "6c669e256bed4172ac92478578f80f21":{
      "scriptId":"u48"},
    "93423be0c9834edfb92b94bd48f81e55":{
      "scriptId":"u49"},
    "e078de3d7858435d861cee0cd46f959e":{
      "scriptId":"u50"},
    "f9dd3d9585a345e4a66b1fa46cf363f1":{
      "scriptId":"u51"},
    "33bd983549de4629a3e35a412b20d8b0":{
      "scriptId":"u52"},
    "77045c7f95ba4d3980900283b3855af9":{
      "scriptId":"u53"},
    "3b9799465e38416d8d7e5366522c2b1e":{
      "scriptId":"u54"},
    "de6febb501d94b9d95182277ad0d534b":{
      "scriptId":"u55"},
    "a179282918a4411ebc9d71004a1f9f09":{
      "scriptId":"u56"},
    "e20c206da71346fb8cc6db4d7e7ea81e":{
      "scriptId":"u57"},
    "742f8a7c1b404904a435f7e4c0e6b912":{
      "scriptId":"u58"},
    "63f36d4e279d43dc805b1cdec37c6203":{
      "scriptId":"u59"},
    "6a9fb1b290ff4bd08ac32ae985a482eb":{
      "scriptId":"u60"},
    "bfbd449b6cf64d9cbd9f4aa0241efe33":{
      "scriptId":"u61"},
    "ea4d71e216794032930a9683c80dea25":{
      "scriptId":"u62"},
    "5e2f1d530f644fa180a41cf4a0f6067c":{
      "scriptId":"u63"},
    "ce5e7e5140854a35ad425b8d6a3526ce":{
      "scriptId":"u64"},
    "a1f7ef74140743fd90e760def28e55d5":{
      "scriptId":"u65"},
    "7450293b600b48e186b89d55aeada382":{
      "scriptId":"u66"},
    "ad0b6ed3908f41a99c09c7a77b024d3a":{
      "scriptId":"u67"},
    "2f1466493eb84830acc981737f3d66ac":{
      "scriptId":"u68"},
    "0d8d1773a33b4383b0d02b69fc8dd7df":{
      "scriptId":"u69"},
    "ea960b388dc9469c8ac7ef046e3da1ec":{
      "scriptId":"u70"},
    "4cd4b42c9633447f91e1de358e32d40d":{
      "scriptId":"u71"},
    "0f24b7f16f6848c3af21e18682d220d3":{
      "scriptId":"u72"},
    "5f92e44146f64549ad91257c1c46b5e8":{
      "scriptId":"u73"}}});