$axure.loadCurrentPage({
  "url":"发起咨询.html",
  "generationDate":new Date(1409493101138.64),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"17d85d0ddaa1488d89e5a885fecc3122",
    "type":"Axure:Page",
    "name":"发起咨询",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"应用字体",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"941eda22cb6a4c45ba35a3acf63862c5",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":100,
              "y":48},
            "size":{
              "width":320,
              "height":480}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"5a779e6ada754fd8bcdae426c1931b89",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":100,
                  "y":48},
                "size":{
                  "width":320,
                  "height":480}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/我的问药/u0.png"}},
{
          "id":"da69fe8608ea40bcbdb3415725a6ca93",
          "label":"top",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":100,
              "y":48},
            "size":{
              "width":320,
              "height":20},
            "rotation":"0",
            "textRotation":"0",
            "borderWidth":"0",
            "cornerRadiusTopLeft":"0"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"219c7462756e45a6897a017069e3fae7",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":100,
                  "y":48},
                "size":{
                  "width":320,
                  "height":20},
                "rotation":"0",
                "textRotation":"0",
                "borderWidth":"0",
                "cornerRadiusTopLeft":"0"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/我的问药/top_u2.png"}},
{
          "id":"8d1dad9cc4a84a2ba27f60d2c12b0dc8",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":100,
              "y":68},
            "size":{
              "width":320,
              "height":40}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"e63618d98454498bbdd42614c83f7638",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":100,
                  "y":68},
                "size":{
                  "width":320,
                  "height":40}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/药店详情/u2.png"}},
{
          "id":"0e0b1ba0e6324c5c9e641674388d04b1",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "fontName":"'Arial Normal', 'Arial'",
            "fontSize":"16px",
            "fontWeight":"400",
            "location":{
              "x":132,
              "y":80},
            "size":{
              "width":101,
              "height":19}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"be38b149652144a2995fe773c7b8efdb",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Normal', 'Arial'",
                "fontSize":"16px",
                "fontWeight":"400",
                "location":{
                  "x":132,
                  "y":80},
                "size":{
                  "width":101,
                  "height":19}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"536e3e087ea846f98f9b25a9aa9bc157",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "horizontalAlignment":"left",
            "location":{
              "x":160,
              "y":142},
            "size":{
              "width":210,
              "height":40},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFCCCCCC},
            "cornerRadiusTopLeft":"10"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"213df2b12a67494dbcdd5e8e8204cc2c",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "horizontalAlignment":"left",
                "location":{
                  "x":160,
                  "y":142},
                "size":{
                  "width":210,
                  "height":40},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC},
                "cornerRadiusTopLeft":"10"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/发起咨询/u8.png"}},
{
          "id":"1d05e901c8734bab84463ddc5317d1dd",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF666666,
              "opacity":1},
            "location":{
              "x":244,
              "y":116},
            "size":{
              "width":33,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"d507fb3174a44a53863c2604091c027c",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF666666,
                  "opacity":1},
                "location":{
                  "x":244,
                  "y":116},
                "size":{
                  "width":33,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"cc399efadfa94c23b2dec9c7aa029e72",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":100,
              "y":484},
            "size":{
              "width":320,
              "height":45}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"4e773bb10ad14c9ca6635502d30eb28d",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":100,
                  "y":484},
                "size":{
                  "width":320,
                  "height":45}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/举报药店/u42.png"}},
{
          "id":"6e838a50630a4f95a09e2feeda686ef6",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":108,
              "y":488},
            "size":{
              "width":305,
              "height":35},
            "borderFill":{
              "fillType":"solid",
              "color":0xFF999999},
            "cornerRadiusTopLeft":"8"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"d4deed299be845e6bee1709c0b8bb9cb",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":108,
                  "y":488},
                "size":{
                  "width":305,
                  "height":35},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF999999},
                "cornerRadiusTopLeft":"8"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/举报药店/u44.png"}},
{
          "id":"acabc47dda7b48448ddfda1b3ced0b12",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":379,
              "y":490},
            "size":{
              "width":30,
              "height":30}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"4ea7a43afb3b421c840d3ce9175f18c7",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":379,
                  "y":490},
                "size":{
                  "width":30,
                  "height":30}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/举报药店/u46.png"}},
{
          "id":"704afb375e61456da1d8967f5a2a4df5",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "fontName":"'Arial Normal', 'Arial'",
            "fontSize":"16px",
            "fontWeight":"400",
            "location":{
              "x":100,
              "y":20},
            "size":{
              "width":65,
              "height":19}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"ea7faa76f59a4aa9ac7fd2d00f9265b7",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Normal', 'Arial'",
                "fontSize":"16px",
                "fontWeight":"400",
                "location":{
                  "x":100,
                  "y":20},
                "size":{
                  "width":65,
                  "height":19}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"0bf7847142cd4bd8ba3eb4ac28475a53",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFCCCCCC,
              "opacity":1},
            "location":{
              "x":109,
              "y":140},
            "size":{
              "width":45,
              "height":45},
            "borderFill":{
              "fillType":"solid",
              "color":0xFF999999},
            "cornerRadiusTopLeft":"6"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"72a7791334744e8cb445f11c77bb9dc6",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC,
                  "opacity":1},
                "location":{
                  "x":109,
                  "y":140},
                "size":{
                  "width":45,
                  "height":45},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF999999},
                "cornerRadiusTopLeft":"6"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/发起咨询/u20.png"}},
{
          "id":"8c0ed6d20dfe4fd2ad03e5c9d2f8e93a",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":500,
              "y":48},
            "size":{
              "width":320,
              "height":480}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"8b6a829be871416a99f7af4ea3f13adb",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":500,
                  "y":48},
                "size":{
                  "width":320,
                  "height":480}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/我的问药/u0.png"}},
{
          "id":"12272c34d52b403e96827e53d04d1ec7",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":775,
              "y":294},
            "size":{
              "width":35,
              "height":35},
            "borderWidth":"-1",
            "borderFill":{
              "fillType":"solid",
              "color":0xFF000000}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"7c848c0da6764216b4a0ea23efe9d080",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":775,
                  "y":294},
                "size":{
                  "width":35,
                  "height":35},
                "borderWidth":"-1",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF000000}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/发起咨询/u24.png"}},
{
          "id":"6f1d2946f01946cc94d73fbad971b111",
          "label":"top",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":500,
              "y":48},
            "size":{
              "width":320,
              "height":20},
            "rotation":"0",
            "textRotation":"0",
            "borderWidth":"0",
            "cornerRadiusTopLeft":"0"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"9953a5bb0acb4f8db89947d6b7997211",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":500,
                  "y":48},
                "size":{
                  "width":320,
                  "height":20},
                "rotation":"0",
                "textRotation":"0",
                "borderWidth":"0",
                "cornerRadiusTopLeft":"0"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/我的问药/top_u2.png"}},
{
          "id":"a12a4d43af214a83adb645a14c9a89b1",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":500,
              "y":68},
            "size":{
              "width":320,
              "height":40}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"5511ef43e4294966b476d3ddea62e974",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":500,
                  "y":68},
                "size":{
                  "width":320,
                  "height":40}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/药店详情/u2.png"}},
{
          "id":"3c940ad3fdf84826ae34fa11fa25f438",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":506,
              "y":78},
            "size":{
              "width":22,
              "height":22},
            "borderWidth":"-1",
            "borderFill":{
              "fillType":"solid",
              "color":0xFF000000}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"6fb351e86e5340d9be6705d46a873fac",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":506,
                  "y":78},
                "size":{
                  "width":22,
                  "height":22},
                "borderWidth":"-1",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF000000}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/咨询药店/u25.png"}},
{
          "id":"e7e484ae118648e3aa2f1e7a6def84f6",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "fontName":"'Arial Normal', 'Arial'",
            "fontSize":"16px",
            "fontWeight":"400",
            "location":{
              "x":532,
              "y":80},
            "size":{
              "width":101,
              "height":19}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"2e2c097d695442f09edba08d4006a271",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Normal', 'Arial'",
                "fontSize":"16px",
                "fontWeight":"400",
                "location":{
                  "x":532,
                  "y":80},
                "size":{
                  "width":101,
                  "height":19}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"dc266ad136a747d78702eab1502fb44c",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "horizontalAlignment":"left",
            "location":{
              "x":560,
              "y":142},
            "size":{
              "width":210,
              "height":106},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFCCCCCC},
            "cornerRadiusTopLeft":"10"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"43ab131dbed547058e6c9cc8a5e56b7f",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "horizontalAlignment":"left",
                "location":{
                  "x":560,
                  "y":142},
                "size":{
                  "width":210,
                  "height":106},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC},
                "cornerRadiusTopLeft":"10"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/发起咨询/u34.png"}},
{
          "id":"10620a8af88c4beca460c48bf3bb4d60",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF666666,
              "opacity":1},
            "location":{
              "x":624,
              "y":116},
            "size":{
              "width":67,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"2390592cbb4541eeb376ede6f770e83a",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF666666,
                  "opacity":1},
                "location":{
                  "x":624,
                  "y":116},
                "size":{
                  "width":67,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"dedd6e650fcb43f29dbe0c2a9c26edd0",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "horizontalAlignment":"left",
            "location":{
              "x":560,
              "y":294},
            "size":{
              "width":210,
              "height":35},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFCCCCCC},
            "cornerRadiusTopLeft":"10"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"c6c60cc0ff5c4a47a90563b0c1039822",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "horizontalAlignment":"left",
                "location":{
                  "x":560,
                  "y":294},
                "size":{
                  "width":210,
                  "height":35},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC},
                "cornerRadiusTopLeft":"10"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/发起咨询/u38.png"}},
{
          "id":"2c9b539aaf68443db907c2b3b84e7db1",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":740,
              "y":300},
            "size":{
              "width":22,
              "height":22}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"a53c8a0520cd4c10933f681da19e8970",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":740,
                  "y":300},
                "size":{
                  "width":22,
                  "height":22}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/发起咨询/u40.png"}},
{
          "id":"562117f383884a6a9175814b2466e95c",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF666666,
              "opacity":1},
            "location":{
              "x":647,
              "y":268},
            "size":{
              "width":26,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"5422b3f656334e16861509d0552bd51b",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF666666,
                  "opacity":1},
                "location":{
                  "x":647,
                  "y":268},
                "size":{
                  "width":26,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"1b0c6d1ce0384531a0be4dfda4c12add",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":500,
              "y":484},
            "size":{
              "width":320,
              "height":45}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"aaa2f4198edf439da54be2cd1714e3b5",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":500,
                  "y":484},
                "size":{
                  "width":320,
                  "height":45}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/举报药店/u42.png"}},
{
          "id":"fed6392951954c15995a6c9ade001ff8",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "horizontalAlignment":"left",
            "location":{
              "x":508,
              "y":488},
            "size":{
              "width":305,
              "height":35},
            "borderFill":{
              "fillType":"solid",
              "color":0xFF999999},
            "cornerRadiusTopLeft":"8"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"d0ab04d43e0d41c08db17a93c522162c",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "horizontalAlignment":"left",
                "location":{
                  "x":508,
                  "y":488},
                "size":{
                  "width":305,
                  "height":35},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF999999},
                "cornerRadiusTopLeft":"8"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/举报药店/u44.png"}},
{
          "id":"a65e3314ea5b4bcfb6bd7178b366ce66",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":778,
              "y":492},
            "size":{
              "width":30,
              "height":30}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"a5f0ac643f5a487183d0559e4cec2da6",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":778,
                  "y":492},
                "size":{
                  "width":30,
                  "height":30}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/举报药店/u46.png"}},
{
          "id":"248f3142afab4080a0df54709705e515",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "fontName":"'Arial Normal', 'Arial'",
            "fontSize":"16px",
            "fontWeight":"400",
            "location":{
              "x":500,
              "y":20},
            "size":{
              "width":81,
              "height":19}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"02f7410f2b7745a0bb9eaab3275c17bf",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Normal', 'Arial'",
                "fontSize":"16px",
                "fontWeight":"400",
                "location":{
                  "x":500,
                  "y":20},
                "size":{
                  "width":81,
                  "height":19}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"1be4b82bf6a44921abaf97d46e6f8f79",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFCCCCCC,
              "opacity":1},
            "location":{
              "x":509,
              "y":142},
            "size":{
              "width":45,
              "height":45},
            "borderFill":{
              "fillType":"solid",
              "color":0xFF999999},
            "cornerRadiusTopLeft":"6"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"762ed5e8626940ca99539fd8c2f9e132",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC,
                  "opacity":1},
                "location":{
                  "x":509,
                  "y":142},
                "size":{
                  "width":45,
                  "height":45},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF999999},
                "cornerRadiusTopLeft":"6"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/发起咨询/u20.png"}},
{
          "id":"f4d48047c8034285897e092f24fa9a72",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":107,
              "y":82},
            "size":{
              "width":20,
              "height":15},
            "borderWidth":"-1",
            "borderFill":{
              "fillType":"solid",
              "color":0xFF000000}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"f8eb764c9339447198d9de5d3cec93da",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":107,
                  "y":82},
                "size":{
                  "width":20,
                  "height":15},
                "borderWidth":"-1",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF000000}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/咨询药店/u25.png"}}]}},
  "masters":{
},
  "objectPaths":{
    "941eda22cb6a4c45ba35a3acf63862c5":{
      "scriptId":"u0"},
    "5a779e6ada754fd8bcdae426c1931b89":{
      "scriptId":"u1"},
    "da69fe8608ea40bcbdb3415725a6ca93":{
      "scriptId":"u2"},
    "219c7462756e45a6897a017069e3fae7":{
      "scriptId":"u3"},
    "8d1dad9cc4a84a2ba27f60d2c12b0dc8":{
      "scriptId":"u4"},
    "e63618d98454498bbdd42614c83f7638":{
      "scriptId":"u5"},
    "0e0b1ba0e6324c5c9e641674388d04b1":{
      "scriptId":"u6"},
    "be38b149652144a2995fe773c7b8efdb":{
      "scriptId":"u7"},
    "536e3e087ea846f98f9b25a9aa9bc157":{
      "scriptId":"u8"},
    "213df2b12a67494dbcdd5e8e8204cc2c":{
      "scriptId":"u9"},
    "1d05e901c8734bab84463ddc5317d1dd":{
      "scriptId":"u10"},
    "d507fb3174a44a53863c2604091c027c":{
      "scriptId":"u11"},
    "cc399efadfa94c23b2dec9c7aa029e72":{
      "scriptId":"u12"},
    "4e773bb10ad14c9ca6635502d30eb28d":{
      "scriptId":"u13"},
    "6e838a50630a4f95a09e2feeda686ef6":{
      "scriptId":"u14"},
    "d4deed299be845e6bee1709c0b8bb9cb":{
      "scriptId":"u15"},
    "acabc47dda7b48448ddfda1b3ced0b12":{
      "scriptId":"u16"},
    "4ea7a43afb3b421c840d3ce9175f18c7":{
      "scriptId":"u17"},
    "704afb375e61456da1d8967f5a2a4df5":{
      "scriptId":"u18"},
    "ea7faa76f59a4aa9ac7fd2d00f9265b7":{
      "scriptId":"u19"},
    "0bf7847142cd4bd8ba3eb4ac28475a53":{
      "scriptId":"u20"},
    "72a7791334744e8cb445f11c77bb9dc6":{
      "scriptId":"u21"},
    "8c0ed6d20dfe4fd2ad03e5c9d2f8e93a":{
      "scriptId":"u22"},
    "8b6a829be871416a99f7af4ea3f13adb":{
      "scriptId":"u23"},
    "12272c34d52b403e96827e53d04d1ec7":{
      "scriptId":"u24"},
    "7c848c0da6764216b4a0ea23efe9d080":{
      "scriptId":"u25"},
    "6f1d2946f01946cc94d73fbad971b111":{
      "scriptId":"u26"},
    "9953a5bb0acb4f8db89947d6b7997211":{
      "scriptId":"u27"},
    "a12a4d43af214a83adb645a14c9a89b1":{
      "scriptId":"u28"},
    "5511ef43e4294966b476d3ddea62e974":{
      "scriptId":"u29"},
    "3c940ad3fdf84826ae34fa11fa25f438":{
      "scriptId":"u30"},
    "6fb351e86e5340d9be6705d46a873fac":{
      "scriptId":"u31"},
    "e7e484ae118648e3aa2f1e7a6def84f6":{
      "scriptId":"u32"},
    "2e2c097d695442f09edba08d4006a271":{
      "scriptId":"u33"},
    "dc266ad136a747d78702eab1502fb44c":{
      "scriptId":"u34"},
    "43ab131dbed547058e6c9cc8a5e56b7f":{
      "scriptId":"u35"},
    "10620a8af88c4beca460c48bf3bb4d60":{
      "scriptId":"u36"},
    "2390592cbb4541eeb376ede6f770e83a":{
      "scriptId":"u37"},
    "dedd6e650fcb43f29dbe0c2a9c26edd0":{
      "scriptId":"u38"},
    "c6c60cc0ff5c4a47a90563b0c1039822":{
      "scriptId":"u39"},
    "2c9b539aaf68443db907c2b3b84e7db1":{
      "scriptId":"u40"},
    "a53c8a0520cd4c10933f681da19e8970":{
      "scriptId":"u41"},
    "562117f383884a6a9175814b2466e95c":{
      "scriptId":"u42"},
    "5422b3f656334e16861509d0552bd51b":{
      "scriptId":"u43"},
    "1b0c6d1ce0384531a0be4dfda4c12add":{
      "scriptId":"u44"},
    "aaa2f4198edf439da54be2cd1714e3b5":{
      "scriptId":"u45"},
    "fed6392951954c15995a6c9ade001ff8":{
      "scriptId":"u46"},
    "d0ab04d43e0d41c08db17a93c522162c":{
      "scriptId":"u47"},
    "a65e3314ea5b4bcfb6bd7178b366ce66":{
      "scriptId":"u48"},
    "a5f0ac643f5a487183d0559e4cec2da6":{
      "scriptId":"u49"},
    "248f3142afab4080a0df54709705e515":{
      "scriptId":"u50"},
    "02f7410f2b7745a0bb9eaab3275c17bf":{
      "scriptId":"u51"},
    "1be4b82bf6a44921abaf97d46e6f8f79":{
      "scriptId":"u52"},
    "762ed5e8626940ca99539fd8c2f9e132":{
      "scriptId":"u53"},
    "f4d48047c8034285897e092f24fa9a72":{
      "scriptId":"u54"},
    "f8eb764c9339447198d9de5d3cec93da":{
      "scriptId":"u55"}}});