$axure.loadCurrentPage({
  "url":"举报药店.html",
  "generationDate":new Date(1409493101030.63),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"ffd82bfa7d784f31b31c9d5e67cc6577",
    "type":"Axure:Page",
    "name":"举报药店",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"应用字体",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"deeb28db8a1b43f984137055a372ab60",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "fontName":"'Arial Normal', 'Arial'",
            "fontSize":"16px",
            "fontWeight":"400",
            "location":{
              "x":100,
              "y":22},
            "size":{
              "width":90,
              "height":19}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"99e2638558634256bc5d464a868dccf9",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Normal', 'Arial'",
                "fontSize":"16px",
                "fontWeight":"400",
                "location":{
                  "x":100,
                  "y":22},
                "size":{
                  "width":90,
                  "height":19}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"397be94b9d2742dea05ebc6901db1123",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":100,
              "y":50},
            "size":{
              "width":320,
              "height":480}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"140aac753163460ca17c66af9e2d8c03",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":100,
                  "y":50},
                "size":{
                  "width":320,
                  "height":480}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/我的问药/u0.png"}},
{
          "id":"bbc796e9bf5c458393e9811d66e38011",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontSize":"15px",
            "location":{
              "x":100,
              "y":70},
            "size":{
              "width":320,
              "height":40}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"b2ffb967ce5746369bca49cf854d3623",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"15px",
                "location":{
                  "x":100,
                  "y":70},
                "size":{
                  "width":320,
                  "height":40}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/药店详情/u2.png"}},
{
          "id":"8f9eddfc44d74358895f5d915411424a",
          "label":"top",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":100,
              "y":50},
            "size":{
              "width":320,
              "height":20},
            "rotation":"0",
            "textRotation":"0",
            "borderWidth":"0",
            "cornerRadiusTopLeft":"0"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"4888272fa7664a3bacb4e2e0d9ad27fc",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":100,
                  "y":50},
                "size":{
                  "width":320,
                  "height":20},
                "rotation":"0",
                "textRotation":"0",
                "borderWidth":"0",
                "cornerRadiusTopLeft":"0"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/我的问药/top_u2.png"}},
{
          "id":"9be32a7eb3a54613aa6818b8c7503662",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":108,
              "y":80},
            "size":{
              "width":22,
              "height":22},
            "borderWidth":"-1",
            "borderFill":{
              "fillType":"solid",
              "color":0xFF000000}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"f94574961be14f81aa809c5bf2a1e90c",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":108,
                  "y":80},
                "size":{
                  "width":22,
                  "height":22},
                "borderWidth":"-1",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF000000}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/咨询药店/u25.png"}},
{
          "id":"6e3a1b0119814240912035f61b50e346",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "fontName":"'Arial Normal', 'Arial'",
            "fontSize":"16px",
            "fontWeight":"400",
            "location":{
              "x":134,
              "y":82},
            "size":{
              "width":65,
              "height":19}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"9eb90ed9046744ad9e99e885417cfca3",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Normal', 'Arial'",
                "fontSize":"16px",
                "fontWeight":"400",
                "location":{
                  "x":134,
                  "y":82},
                "size":{
                  "width":65,
                  "height":19}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"4f66cdd2a0bf409f92385eb6829d8f8d",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":108,
              "y":200},
            "size":{
              "width":110,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"c6335ab626744571936b29efac07a55d",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":108,
                  "y":200},
                "size":{
                  "width":110,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "annotation":{
            "描述":"举报原因为多选，必选，默认为空；"},
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"984e15fcc519408f866e819986893b97",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":108,
              "y":374},
            "size":{
              "width":110,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"25fc13fb37564bfba86630cd04ff95e2",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":108,
                  "y":374},
                "size":{
                  "width":110,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "annotation":{
            "描述":"非必填；"},
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"4568fe44f416470593bc3e3baaa14d1a",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"16px",
            "location":{
              "x":373,
              "y":80},
            "size":{
              "width":37,
              "height":19}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"aefa094536b643e08c6beb4e4bf39a00",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"16px",
                "location":{
                  "x":373,
                  "y":80},
                "size":{
                  "width":37,
                  "height":19}},
              "adaptiveStyles":{
}}],
          "annotation":{
            "描述":"点击提交按钮：<br>1、校验是否选择举报原因，如未选择则浮层提示“请至少选择一个举报原因”；<br>2、校验通过则提交成功，浮层提示“提交成功”，并返回至药店详情页；"},
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"78f219a90ba04e7f9787b0139569c882",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":108,
              "y":120},
            "size":{
              "width":302,
              "height":64}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"c9511f1b52e44a1aa9eed268caf91a50",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":108,
                  "y":120},
                "size":{
                  "width":302,
                  "height":64}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"15e6da6acfc94c4f912279ef51b21966",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'Arial Negreta', 'Arial'",
            "fontWeight":"700",
            "horizontalAlignment":"left",
            "location":{
              "x":108,
              "y":220},
            "size":{
              "width":302,
              "height":35}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"ef709b9aeb854758aac711c5f41c2fa9",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Negreta', 'Arial'",
                "fontWeight":"700",
                "horizontalAlignment":"left",
                "location":{
                  "x":108,
                  "y":220},
                "size":{
                  "width":302,
                  "height":35}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/举报药店/u20.png"}},
{
          "id":"ba5a26ef3c98471a84b917f0ddb0a217",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'Arial Negreta', 'Arial'",
            "fontWeight":"700",
            "horizontalAlignment":"left",
            "location":{
              "x":108,
              "y":254},
            "size":{
              "width":302,
              "height":35}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"28b85b9fb8dc4c2c9e7c9d52f762d523",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Negreta', 'Arial'",
                "fontWeight":"700",
                "horizontalAlignment":"left",
                "location":{
                  "x":108,
                  "y":254},
                "size":{
                  "width":302,
                  "height":35}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/举报药店/u20.png"}},
{
          "id":"a92a29428d20466a8d671ebf52643f23",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'Arial Negreta', 'Arial'",
            "fontWeight":"700",
            "horizontalAlignment":"left",
            "location":{
              "x":108,
              "y":288},
            "size":{
              "width":302,
              "height":35}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"4c6b02c2a6574398a246d6b1cf11f248",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Negreta', 'Arial'",
                "fontWeight":"700",
                "horizontalAlignment":"left",
                "location":{
                  "x":108,
                  "y":288},
                "size":{
                  "width":302,
                  "height":35}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/举报药店/u20.png"}},
{
          "id":"19eb08e27ee7457dba0d626f2296adc1",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'Arial Negreta', 'Arial'",
            "fontWeight":"700",
            "horizontalAlignment":"left",
            "location":{
              "x":108,
              "y":322},
            "size":{
              "width":302,
              "height":35}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"640a508cbc1347e7859b6e9ba657e2ed",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Negreta', 'Arial'",
                "fontWeight":"700",
                "horizontalAlignment":"left",
                "location":{
                  "x":108,
                  "y":322},
                "size":{
                  "width":302,
                  "height":35}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/举报药店/u20.png"}},
{
          "id":"d3fd5f8acd894d94b291e99bcf4252f5",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":375,
              "y":224},
            "size":{
              "width":25,
              "height":25},
            "borderWidth":"-1",
            "borderFill":{
              "fillType":"solid",
              "color":0xFF000000}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"87b7bc964e10403ba48ba0f25a8aa055",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":375,
                  "y":224},
                "size":{
                  "width":25,
                  "height":25},
                "borderWidth":"-1",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF000000}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/举报药店/u28.png"}},
{
          "id":"b1fb0f7a8fc340c99493c2b4700c9ccd",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "horizontalAlignment":"left",
            "verticalAlignment":"top",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF999999,
              "opacity":1},
            "location":{
              "x":108,
              "y":393},
            "size":{
              "width":302,
              "height":100}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"44205ce86a2149ecb34c1bec1b21d189",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "horizontalAlignment":"left",
                "verticalAlignment":"top",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF999999,
                  "opacity":1},
                "location":{
                  "x":108,
                  "y":393},
                "size":{
                  "width":302,
                  "height":100}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/举报药店/u30.png"}},
{
          "id":"a1b1868b7cee4ad187947ab0d725e9e7",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":500,
              "y":50},
            "size":{
              "width":320,
              "height":480}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"a210d703120841a1a2d9a3c0dc8fc527",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":500,
                  "y":50},
                "size":{
                  "width":320,
                  "height":480}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/我的问药/u0.png"}},
{
          "id":"635069b34c2f4d3fa384ab04543fc107",
          "label":"top",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":500,
              "y":50},
            "size":{
              "width":320,
              "height":20},
            "rotation":"0",
            "textRotation":"0",
            "borderWidth":"0",
            "cornerRadiusTopLeft":"0"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"f917b45eb18b4f15a9ac81d34de2d31a",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":500,
                  "y":50},
                "size":{
                  "width":320,
                  "height":20},
                "rotation":"0",
                "textRotation":"0",
                "borderWidth":"0",
                "cornerRadiusTopLeft":"0"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/我的问药/top_u2.png"}},
{
          "id":"72e09266aea548aca2561bc423868a8e",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":500,
              "y":70},
            "size":{
              "width":320,
              "height":40}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"88cc007b1e4e4c3a97e33bc7f81b38b7",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":500,
                  "y":70},
                "size":{
                  "width":320,
                  "height":40}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/药店详情/u2.png"}},
{
          "id":"77498b34261741f991ab340c94e65e3f",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":506,
              "y":80},
            "size":{
              "width":22,
              "height":22},
            "borderWidth":"-1",
            "borderFill":{
              "fillType":"solid",
              "color":0xFF000000}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"4439e4cc4afc491c81473dce213b5047",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":506,
                  "y":80},
                "size":{
                  "width":22,
                  "height":22},
                "borderWidth":"-1",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF000000}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/咨询药店/u25.png"}},
{
          "id":"2f5e87582406497d8f7ef287ab1481ac",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "fontName":"'Arial Normal', 'Arial'",
            "fontSize":"16px",
            "fontWeight":"400",
            "location":{
              "x":532,
              "y":82},
            "size":{
              "width":65,
              "height":19}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"7bba6ee65cda4b84adb1507a0c3b1b73",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Normal', 'Arial'",
                "fontSize":"16px",
                "fontWeight":"400",
                "location":{
                  "x":532,
                  "y":82},
                "size":{
                  "width":65,
                  "height":19}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"d40374ddd94b49ffa851af6842fa449b",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":500,
              "y":486},
            "size":{
              "width":320,
              "height":45}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"a95206078fc540f093065b700cad5dcb",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":500,
                  "y":486},
                "size":{
                  "width":320,
                  "height":45}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/举报药店/u42.png"}},
{
          "id":"1fe29f8e0b8b409d8cd5d205d8720652",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":508,
              "y":490},
            "size":{
              "width":305,
              "height":35},
            "borderFill":{
              "fillType":"solid",
              "color":0xFF999999},
            "cornerRadiusTopLeft":"8"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"411b1bdbe9ed43b4b0610e6936904875",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":508,
                  "y":490},
                "size":{
                  "width":305,
                  "height":35},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF999999},
                "cornerRadiusTopLeft":"8"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/举报药店/u44.png"}},
{
          "id":"8f5b8376111e46dd84c21544ee0f5cd9",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":777,
              "y":494},
            "size":{
              "width":30,
              "height":30}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"d883ac290092456f9d120158a107d39b",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":777,
                  "y":494},
                "size":{
                  "width":30,
                  "height":30}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/举报药店/u46.png"}},
{
          "id":"7fa0138818ed4d0a9170c1f8bf4029ab",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "horizontalAlignment":"left",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF666666,
              "opacity":1},
            "location":{
              "x":560,
              "y":144},
            "size":{
              "width":230,
              "height":66},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFCCCCCC},
            "cornerRadiusTopLeft":"10"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"cbcffd250b8f49f4b47ce4a20027bb4f",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "horizontalAlignment":"left",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF666666,
                  "opacity":1},
                "location":{
                  "x":560,
                  "y":144},
                "size":{
                  "width":230,
                  "height":66},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC},
                "cornerRadiusTopLeft":"10"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/举报药店/u48.png"}},
{
          "id":"eb1330a4d7d248b494b8b526ad4065ec",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF666666,
              "opacity":1},
            "location":{
              "x":626,
              "y":118},
            "size":{
              "width":62,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"d716f6ec613a44c1b9431cae4f090441",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF666666,
                  "opacity":1},
                "location":{
                  "x":626,
                  "y":118},
                "size":{
                  "width":62,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"f8d62c9c38bc4616ac85f8da228a4f3d",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFCCCCCC,
              "opacity":1},
            "location":{
              "x":509,
              "y":144},
            "size":{
              "width":45,
              "height":45},
            "borderFill":{
              "fillType":"solid",
              "color":0xFF999999}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"83c086a1d53745bdb68027b1648d5a45",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC,
                  "opacity":1},
                "location":{
                  "x":509,
                  "y":144},
                "size":{
                  "width":45,
                  "height":45},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF999999}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/我的问药/u34.png"}},
{
          "id":"c1147a78a5a04f37867313b7f2981248",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "horizontalAlignment":"left",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF666666,
              "opacity":1},
            "location":{
              "x":560,
              "y":256},
            "size":{
              "width":230,
              "height":66},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFCCCCCC},
            "cornerRadiusTopLeft":"10"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"4d9c6ece30494d10bf6e25f93d21c2c7",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "horizontalAlignment":"left",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF666666,
                  "opacity":1},
                "location":{
                  "x":560,
                  "y":256},
                "size":{
                  "width":230,
                  "height":66},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC},
                "cornerRadiusTopLeft":"10"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/举报药店/u48.png"}},
{
          "id":"5f54d88a4e344ae1b46a56b437d08655",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF666666,
              "opacity":1},
            "location":{
              "x":626,
              "y":230},
            "size":{
              "width":62,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"5c21c062b4964cbc98da447db21c717e",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF666666,
                  "opacity":1},
                "location":{
                  "x":626,
                  "y":230},
                "size":{
                  "width":62,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"e2ea8c7f4e7b42ee84f230fb7e77a81c",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFCCCCCC,
              "opacity":1},
            "location":{
              "x":509,
              "y":256},
            "size":{
              "width":45,
              "height":45},
            "borderFill":{
              "fillType":"solid",
              "color":0xFF999999}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"500cd07d2fd84a318507afbc841de834",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC,
                  "opacity":1},
                "location":{
                  "x":509,
                  "y":256},
                "size":{
                  "width":45,
                  "height":45},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF999999}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/我的问药/u34.png"}},
{
          "id":"b9661171442742e79cb25bff1f175549",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "fontName":"'Arial Normal', 'Arial'",
            "fontSize":"16px",
            "fontWeight":"400",
            "location":{
              "x":500,
              "y":21},
            "size":{
              "width":80,
              "height":19}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"dee77e331bff4c7798b83b0a5d73f2d1",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Normal', 'Arial'",
                "fontSize":"16px",
                "fontWeight":"400",
                "location":{
                  "x":500,
                  "y":21},
                "size":{
                  "width":80,
                  "height":19}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}}]}},
  "masters":{
},
  "objectPaths":{
    "deeb28db8a1b43f984137055a372ab60":{
      "scriptId":"u0"},
    "99e2638558634256bc5d464a868dccf9":{
      "scriptId":"u1"},
    "397be94b9d2742dea05ebc6901db1123":{
      "scriptId":"u2"},
    "140aac753163460ca17c66af9e2d8c03":{
      "scriptId":"u3"},
    "bbc796e9bf5c458393e9811d66e38011":{
      "scriptId":"u4"},
    "b2ffb967ce5746369bca49cf854d3623":{
      "scriptId":"u5"},
    "8f9eddfc44d74358895f5d915411424a":{
      "scriptId":"u6"},
    "4888272fa7664a3bacb4e2e0d9ad27fc":{
      "scriptId":"u7"},
    "9be32a7eb3a54613aa6818b8c7503662":{
      "scriptId":"u8"},
    "f94574961be14f81aa809c5bf2a1e90c":{
      "scriptId":"u9"},
    "6e3a1b0119814240912035f61b50e346":{
      "scriptId":"u10"},
    "9eb90ed9046744ad9e99e885417cfca3":{
      "scriptId":"u11"},
    "4f66cdd2a0bf409f92385eb6829d8f8d":{
      "scriptId":"u12"},
    "c6335ab626744571936b29efac07a55d":{
      "scriptId":"u13"},
    "984e15fcc519408f866e819986893b97":{
      "scriptId":"u14"},
    "25fc13fb37564bfba86630cd04ff95e2":{
      "scriptId":"u15"},
    "4568fe44f416470593bc3e3baaa14d1a":{
      "scriptId":"u16"},
    "aefa094536b643e08c6beb4e4bf39a00":{
      "scriptId":"u17"},
    "78f219a90ba04e7f9787b0139569c882":{
      "scriptId":"u18"},
    "c9511f1b52e44a1aa9eed268caf91a50":{
      "scriptId":"u19"},
    "15e6da6acfc94c4f912279ef51b21966":{
      "scriptId":"u20"},
    "ef709b9aeb854758aac711c5f41c2fa9":{
      "scriptId":"u21"},
    "ba5a26ef3c98471a84b917f0ddb0a217":{
      "scriptId":"u22"},
    "28b85b9fb8dc4c2c9e7c9d52f762d523":{
      "scriptId":"u23"},
    "a92a29428d20466a8d671ebf52643f23":{
      "scriptId":"u24"},
    "4c6b02c2a6574398a246d6b1cf11f248":{
      "scriptId":"u25"},
    "19eb08e27ee7457dba0d626f2296adc1":{
      "scriptId":"u26"},
    "640a508cbc1347e7859b6e9ba657e2ed":{
      "scriptId":"u27"},
    "d3fd5f8acd894d94b291e99bcf4252f5":{
      "scriptId":"u28"},
    "87b7bc964e10403ba48ba0f25a8aa055":{
      "scriptId":"u29"},
    "b1fb0f7a8fc340c99493c2b4700c9ccd":{
      "scriptId":"u30"},
    "44205ce86a2149ecb34c1bec1b21d189":{
      "scriptId":"u31"},
    "a1b1868b7cee4ad187947ab0d725e9e7":{
      "scriptId":"u32"},
    "a210d703120841a1a2d9a3c0dc8fc527":{
      "scriptId":"u33"},
    "635069b34c2f4d3fa384ab04543fc107":{
      "scriptId":"u34"},
    "f917b45eb18b4f15a9ac81d34de2d31a":{
      "scriptId":"u35"},
    "72e09266aea548aca2561bc423868a8e":{
      "scriptId":"u36"},
    "88cc007b1e4e4c3a97e33bc7f81b38b7":{
      "scriptId":"u37"},
    "77498b34261741f991ab340c94e65e3f":{
      "scriptId":"u38"},
    "4439e4cc4afc491c81473dce213b5047":{
      "scriptId":"u39"},
    "2f5e87582406497d8f7ef287ab1481ac":{
      "scriptId":"u40"},
    "7bba6ee65cda4b84adb1507a0c3b1b73":{
      "scriptId":"u41"},
    "d40374ddd94b49ffa851af6842fa449b":{
      "scriptId":"u42"},
    "a95206078fc540f093065b700cad5dcb":{
      "scriptId":"u43"},
    "1fe29f8e0b8b409d8cd5d205d8720652":{
      "scriptId":"u44"},
    "411b1bdbe9ed43b4b0610e6936904875":{
      "scriptId":"u45"},
    "8f5b8376111e46dd84c21544ee0f5cd9":{
      "scriptId":"u46"},
    "d883ac290092456f9d120158a107d39b":{
      "scriptId":"u47"},
    "7fa0138818ed4d0a9170c1f8bf4029ab":{
      "scriptId":"u48"},
    "cbcffd250b8f49f4b47ce4a20027bb4f":{
      "scriptId":"u49"},
    "eb1330a4d7d248b494b8b526ad4065ec":{
      "scriptId":"u50"},
    "d716f6ec613a44c1b9431cae4f090441":{
      "scriptId":"u51"},
    "f8d62c9c38bc4616ac85f8da228a4f3d":{
      "scriptId":"u52"},
    "83c086a1d53745bdb68027b1648d5a45":{
      "scriptId":"u53"},
    "c1147a78a5a04f37867313b7f2981248":{
      "scriptId":"u54"},
    "4d9c6ece30494d10bf6e25f93d21c2c7":{
      "scriptId":"u55"},
    "5f54d88a4e344ae1b46a56b437d08655":{
      "scriptId":"u56"},
    "5c21c062b4964cbc98da447db21c717e":{
      "scriptId":"u57"},
    "e2ea8c7f4e7b42ee84f230fb7e77a81c":{
      "scriptId":"u58"},
    "500cd07d2fd84a318507afbc841de834":{
      "scriptId":"u59"},
    "b9661171442742e79cb25bff1f175549":{
      "scriptId":"u60"},
    "dee77e331bff4c7798b83b0a5d73f2d1":{
      "scriptId":"u61"}}});